<html>
<?php echo $this->doctype("XHTML1_TRANSITIONAL"), PHP_EOL; ?>

 <meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <?php echo $this->headTitle('SIMENS '. $this->translate('Systeme Information Medical'))->setSeparator(' - ')->setAutoEscape(false) ?>

		
<?php 	
  echo $this->headLink()->prependStylesheet($this->basePath().'/css/bootstrap.min.css');
  echo $this->headLink()->prependStylesheet($this->basePath().'/css/uniform.css');
  echo $this->headLink()->prependStylesheet($this->basePath().'/css/select2.css');
  echo $this->headLink()->prependStylesheet($this->basePath().'/css/jquery.contextMenu.css');
  echo $this->headLink()->prependStylesheet($this->basePath().'/css/matrix-style.css');
  echo $this->headLink()->prependStylesheet($this->basePath().'/css/matrix-media.css');
  echo $this->headLink()->prependStylesheet($this->basePath().'/font-awesome/css/font-awesome.css');
  echo $this->headLink()->prependStylesheet($this->basePath().'/css/tooltipster.css');
  echo $this->headLink()->prependStylesheet($this->basePath().'/css/smoothness/jquery-ui.css');
  echo $this->headLink()->prependStylesheet($this->basepath().'/css/tooltipster.css');
  
  $this->headScript()->appendFile($this->basePath().'/js/jquery.min.js');
  $this->headScript()->appendFile($this->basePath().'/js/jquery.tooltipster.min.js');
  $this->headScript()->appendFile($this->basePath().'/js/bootstrap.min.js');
  $this->headScript()->appendFile($this->basePath().'/js/jquery.uniform.js');
  $this->headScript()->appendFile($this->basePath().'/js/select2.min.js');
  $this->headScript()->appendFile($this->basePath().'/js/jquery.dataTables.min.js');
  $this->headScript()->appendFile($this->basePath().'/js/jquery-ui.js');
  
  $this->headScript()->appendFile($this->basePath().'/js/jquery.maskedinput.js');
  $this->headScript()->appendFile($this->basePath().'/js/controle_saisie/controle_saisie.js');
?>
<?php echo $this->headScript();?>
  
<head>
</head>

<?php
$user = $this->layout()->user; 
$nom = $user['Nom'];
$prenom = $user['Prenom'];
$service = $user['NomService'];
if($user['role'] == 'superAdmin') { $service = "INFORMATIQUE";}

$info = null;
if($user['role'] == 'major') {$info = '<i style="color: #48f07f; padding-left: 10px;">(Major)</i>';}

$sexe = $user['Sexe'];
$civilite =  'Mme';
if($sexe == 'Masculin'){$civilite = 'M';}
?>

<body id = "bodbod">
<!--Header-part-->
<div id="logoSimens" style=" height: 70px;">
			<div style="font-size: 28px; color: red; padding-top: 20px; padding-left: 35px;">+<div style="font-size: 27px; color: #48ce77; font-family: Bookman Old Style; float:left; ">SIMENS</div></div>
	</div>
	
	<!--close-Header-part-->
	<!--top Menu au dessus -->
<div id="user-nav" class="navbar navbar-inverse" style="padding-top: 0px; padding-left: 0px; width: 83%;">
 <div style="width:100%;">
  <ul class="nav" style="width:100%;">
    <li  class="dropdown" style=" width: 30%;"><a title=""  class="dropdown-toggle">
      <i> <span style="color: white; font-size: 13px;">Service: </span></i>
      <b class="caret" ></b> <span style="font-size: 15px; color: white; font-family: Times  New Roman;"><?php echo $service;?> <?php echo $info;?></span></a>
    </li>

    <li  class="dropdown" style=" width: 55%;"><a title="" class="dropdown-toggle">
      
      <i><img id="modifierPassword" style="cursor:pointer; position:relative; top:-2px;" title="" src="<?php echo $this->basePath().'/img/light/admin_user_2.png';?>"/>
      </i><span style="color: white; font-size: 13px;"><i>Bienvenue: </i> <?php echo $civilite;?>.</span>
      <b class="caret" ></b> <span style="font-size: 15px; color: white;font-family: Times  New Roman;"><?php echo $prenom.'  '.$nom;?></span></a>
    </li>

    <li style="width: 15%;"><a title="" style="" href="<?php echo $this->url('admin', array('action'=>'logout'));?>">
      <i><img src="<?php echo $this->basePath().'/img/light/bended_arrow_right.png';?>"/></i> <span style="color: white; font-size: 14px; font-family: Times  New Roman;"><i>D&eacute;connexion</i></span></a>
    </li>
  </ul>
 </div>
</div>
	<!--Menu de droite-->
	<div id="sidebar">
  <?php echo $this->partial('layout/menugauchehospi'); ?>
</div>
	<div id="content">
		<div id="content-header">
			<div style="width: 96%; margin-left: 25px;">
				<hr>
				<div class="row-fluid">
	         <?php echo $this->content; ?>
         </div>
			</div>
		</div>
	</div>
	<!--Pied de Page debut-->
	<div class="row-fluid">
		<div id="footer" class="span12" style="color: white;" ><?php echo $this->partial('layout/piedpage'); ?> </div>
	</div>
	<!--Fin de pied de page-->
</body>
</html>

<style>
.ui-tooltip {
	padding: 8px;
	position: absolute;
	z-index: 9999;
	max-width: 300px;
	-webkit-box-shadow: 0 0 5px #aaa;
	box-shadow: 0 0 5px #aaa;
}

body .ui-tooltip {
	border-width: 2px;
}

#bodbod { 
 	min-width: 1345px;
 	overflow-x:scroll;  
} 
 
#user-nav { 
 	min-width: 1100px;
 	 
 } 
</style>

<script>
var base_url = window.location.toString();
var tabUrl = base_url.split("public");

jQuery(document).ready(function($){
    $('a,img,hass').tooltip({
        animation: true,
        html: true,
        placement: 'bottom',
        show: {
            effect: "slideDown",
            delay: 250
          }
    });

    $('#modifierPassword').click(function(){
        var role = "<?php echo $user['role'];?>";

        var id = 0;
        if(role == 'infirmier') {id = 4;}
        if(role == 'laborantin'){id = 5;}
        if(role == 'radiologie'){id = 6;}
        if(role == 'anesthesie'){id = 7;}
        if(role == 'major')     {id = 8;}
        
    	vart=tabUrl[0]+'public/admin/modifier-password/'+id;
        $(location).attr("href",vart);
    });
});
</script>
