<html>
<?php echo $this->doctype("XHTML1_TRANSITIONAL"), PHP_EOL; ?>

 <meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />

<?php
// $this->jQuery()->enable();
// $this->jQuery()->uiEnable();
// echo $this->jQuery();

 echo $this->headLink()->prependStylesheet($this->basePath().'/css/bootstrap.min.css');
 echo $this->headLink()->prependStylesheet($this->basePath().'/css/uniform.css');
 echo $this->headLink()->prependStylesheet($this->basePath().'/css/select2.css');
 echo $this->headLink()->prependStylesheet($this->basePath().'/css/jquery.contextMenu.css');
 echo $this->headLink()->prependStylesheet($this->basePath().'/css/matrix-style.css');
 echo $this->headLink()->prependStylesheet($this->basePath().'/css/matrix-media.css');
 echo $this->headLink()->prependStylesheet($this->basePath().'/css/tooltipster.css');
 echo $this->headLink()->appendStylesheet($this->basePath().'/css/jquery-ui.css');

 $this->headScript()->appendFile($this->basePath().'/js/jquery.min.js');
 $this->headScript()->appendFile($this->basePath().'/js/jquery.tooltipster.min.js');
 $this->headScript()->appendFile($this->basePath().'/js/bootstrap.min.js');
 $this->headScript()->appendFile($this->basePath().'/js/jquery.uniform.js');
 $this->headScript()->appendFile($this->basePath().'/js/select2.min.js');
 $this->headScript()->appendFile($this->basePath().'/js/jquery.dataTables.min.js');
 $this->headScript()->appendFile($this->basePath().'/js/jquery-ui.js');
 echo $this->headTitle($this->pageTitle);?>
		<?php echo $this->headScript();?>
<head>
</head>

<?php
//RECUPERER LES INFOS SUR LE MEDECIN

// $identity = (array) Zend_Auth::getInstance()->getIdentity();
// if($identity){
//   $nom = $identity['name'];
//   $prenom = $identity['prenom'];
//   $service = $identity['service'];
// }else{
//   $nom ='';
//   $prenom = '';
//   $service = '';
// }
?>

<body id = "bodbod">
<!--Header-part-->
<div id="header">
  <h1><a href="">Simens admin panel</a></h1>
</div>
<!--close-Header-part-->
<!--top Menu au dessus -->
<div id="user-nav" class="navbar navbar-inverse" style="padding-top: 15px; width: 90%;">

  <ul class="nav" style="width:100%;">
    <li  class="dropdown" id="" style=" width: 20%;"><a title=""  class="dropdown-toggle">
    <i> <span style="color: white; font-size: 13px;">Service: </span></i>
    <b class="caret" ></b> <span style="font-size: 18px; color: white; font-family: Times  New Roman;"> <?php //echo $service;?></span></a>
    </li>

    <li  class="dropdown" id="" style=" width: 60%;"><a title="" class="dropdown-toggle">
    <i class="icon icon-user"></i>  <span style="color: white; font-size: 13px;"><i>Bienvenue: </i> M.</span>
    <b class="caret" ></b> <span style="font-size: 18px; color: white;font-family: Times  New Roman;"><?php //echo $prenom.' '.$nom;?></span></a>
    </li>

    <li class="" style="width: 15%;"><a title="" style="" href="">
    <i class="icon icon-share-alt"></i> <span style="color: white;">D&eacute;connexion</span></a>
    </li>
  </ul>

</div>
<!--Menu de droite-->
<div id="sidebar">
  <?php echo $this->partial('layout/menugauche-pharmacie'); ?>
</div>
<div id="content">
  	<div id="content-header">
    <div style="width: 96%; margin-left:25px; ">
    	<hr>
   		 <div class="row-fluid">
	         <?php echo $this->content; ?>
         </div>
  	</div>
	</div>
</div>
<!--Pied de Page debut-->
<div class="row-fluid">
	 <div id="footer" class="span12"><?php echo $this->partial('layout/piedpage-pharmacie'); ?> </div>
</div>
<!--Fin de pied de page-->
</body>
</html>

<style>
.my-custom-theme {

    border-top-left-radius: 5px;
    border-top-right-radius: 5px;
    border-bottom-right-radius: 5px;
    border-bottom-left-radius: 5px;
    background-color: #ffffff;
    background-image: none;
    background-repeat: repeat;
    background-attachment: scroll;
    background-position: 0% 0%;
    background-clip: border-box;
    background-origin: padding-box;
    background-size: auto auto;
    box-shadow: 0px 0px 14px rgba(0, 0, 0, 0.9);
    color: #2c2c2c;
    font-family: 'Arial',sans-serif;
    font-size: 14px;
    line-height: 16px;
    padding-top: 5px;
    /*padding-right: 8px;*/
    padding-bottom: 5px;
    /*padding-left: 10px; */
    font-weight: 400;
    text-align: center;
    weight: bold;
}

.my-custom-theme .tooltipster-content {
    font-family: Arial, sans-serif;
    font-size: 17px;
    line-height: 16px;
    padding: 8px 10px;
}

td {
	font-family: Baskerville Old Face;
	font-size : 17px;
}
</style>


<script>
$(document).ready(function() {
	   $('img').tooltipster({
		   animation: 'grow',
		   delay: 100,
		   theme: '.my-custom-theme',
		   touchDevices: false,
		   trigger: 'hover',
		   position: 'bottom'
		});

});
</script>