<style>
#sidebarMenu {
	visibility: hidden
}
</style>

<script>
$(window).load(function () {

	$('#waitMenuGauche').toggle(false);
	$('#sidebarMenu').fadeIn().css({'visibility':'visible'});
	 
});
</script>

<div id="waitMenuGauche"
	style="color: #cccccc; font-size: 13px; margin-top: 80px; margin-left: 60px;">
	<span> Chargement ... </span>
</div>



<ul id="sidebarMenu">
	<!-- MENU ***DOSSIER PATIENT*** -->
	<li id="dossier_patient"><a href=""> <span
			style="margin-left: 0px; color: #48ce77; font-weight: bold; font-size: 20px; font-family: Times New Roman;">
				<img id="image" style="display: inline;"
				src='<?php echo $this->basePath().'/images_icons/plus-green1.png'?>'
				alt='Liste' /> Dossier patient
		</span></a></li>

	<li id="plus_dossier_patient" style="background: #4a5765;">

		<div style="margin-left: 30px; height: 40px; padding-top: 20px;">
			<a
				
				href="<?php echo $this->url('secretariat', array('action'=> 'ajouter-patient'));?>">
				<span id="nouveau_style"
				style="margin-left: 5px; color: white; font-size: 15px; font-family: Times New Roman;"><img
					style="display: inline;"
					src='<?php echo $this->basePath().'/images_icons/dossier.PNG'?>'
					alt='Liste' /> Nouveau</span>
			</a>
		</div>

		<div style="margin-left: 30px; height: 40px;">
			<a
				href="<?php echo $this->basePath()."/secretariat/liste-patient";?>">
				<img style="margin-left: 5px; display: inline;"
				src='<?php echo $this->basePath().'/images_icons/liste.PNG'?>'
				alt='Liste' /> <span id="liste_dossier_patient_style"
				style="font-size: 15px; color: white; font-family: Times New Roman;">Liste</span>
			</a>
		</div>
	</li>
	<!-- MENU ***ADMISSION ORL*** -->
	<li id="admission_orl"><a href="">
	   <span style="margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;"> <img id="image" style="display: inline;" src='<?php echo $this->basePath().'/images_icons/plus-green1.png'?>' alt='Liste' /> Admission </span></a> 
	</li>

	<li id="plus_admission_orl" style="background: #4a5765;" >

	   <div style="margin-left:30px; height:40px; padding-top:20px;"><a href="<?php echo $this->basePath()."/secretariat/admission";?>"  >
	      <span id="admission_style" style="margin-left:5px; color: white; font-size:15px; font-family:Times New Roman;"><img style="display: inline;" src='<?php echo $this->basePath().'/images_icons/dossier.PNG'?>' alt='Liste' /> Admettre</span></a>
	   </div>

	   <div style="margin-left:30px; height:40px;"><a href="<?php echo $this->basePath()."/secretariat/liste-patients-admis";?>">
	      <img style="margin-left:5px; display: inline;" src='<?php echo $this->basePath().'/images_icons/liste.PNG'?>' alt='Liste' />
	      <span id="liste_admission_style" style="font-size:15px; color: white; font-family:Times New Roman;">Liste des admis</span></a>
	   </div>
	  
	</li>
	
	
	
	
	
		<!-- MENU ***RENDEZ-VOUS*** -->
	<li id="rendez_vous_orl"><a href="">
	   <span style="margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;"> <img id="image" style="display: inline;" src='<?php echo $this->basePath().'/images_icons/plus-green1.png'?>' alt='Liste' /> Rendez-vous </span></a>
	</li>
	
		<li id="plus_rendez_vous_orl" style="background: #4a5765;" >

	   <div style="margin-left:30px; height:40px; padding-top:20px;"><a href="<?php echo $this->basePath()."/secretariat/fixer-rendez-vous";?>"  >
	      <span id="fixer_rendez_vous_style" style="margin-left:5px; color: white; font-size:15px; font-family:Times New Roman;"><img style="display: inline;" src='<?php echo $this->basePath().'/images_icons/dossier.PNG'?>' alt='Liste' /> Fixer RV</span></a>
	   </div>
	   
	   	<div style="margin-left:30px; height:40px;"><a href="<?php echo $this->basePath()."/secretariat/programmer-rendez-vous";?>">
	      <img style="margin-left:5px; display: inline;" src='<?php echo $this->basePath().'/images_icons/liste.PNG'?>' alt='Liste' />
	      <span id="programmer_style" style="font-size:15px; color: white; font-family:Times New Roman;">Programmer RV</span></a>
	   </div>
	   <div style="margin-left:30px; height:40px;"><a href="<?php echo $this->basePath()."/secretariat/liste-rendez-vous";?>">
	      <img style="margin-left:5px; display: inline;" src='<?php echo $this->basePath().'/images_icons/liste.PNG'?>' alt='Liste' />
	      <span id="liste_rendez_vous_style" style="font-size:15px; color: white; font-family:Times New Roman;">Liste des rendez-vous</span></a>
	   </div> 
	   
	   </li>
	
	
	
	
	<!-- MENU ***SURVEILLANT DE SERVICE*** -->
	<!-- MENU ***SURVEILLANT DE SERVICE*** -->
	<!-- MENU ***SURVEILLANT DE SERVICE*** -->
	<li id="naissance"><a href=""> <span
			style="margin-left: 0px; color: #48ce77; font-weight: bold; font-size: 20px; font-family: Times New Roman;">
				<img id="image" style="display: inline;"
				src='<?php echo $this->basePath().'/images_icons/plus-green1.png'?>'
				alt='Liste' /> Consultations
		</span></a></li>

	<li id="plus_naissance" style="background: #4a5765;">
		<div style="margin-left: 30px; height: 40px; padding-top: 20px;">
			<a
				href="<?php echo $this->url('consultation', array('action'=> 'recherche'));?>">
				<span id="ajouter_style"
				style="margin-left: 5px; color: white; font-size: 15px; font-family: Times New Roman;"><img
					style="display: inline;"
					src='<?php echo $this->basePath().'/images_icons/dossier.PNG'?>'
					alt='Liste' /> En cours ...</span>
			</a>
		</div>
		<div id="liste_naiss" style="margin-left: 30px; height: 40px;">
			<a
				href="<?php echo $this->url('consultation', array('action'=> 'espace-recherche-surv'));?>">
				<img style="margin-left: 5px; display: inline;"
				src='<?php echo $this->basePath().'/images_icons/Search_22.PNG'?>'
				alt='Liste' /> <span id="liste_style"
				style="font-size: 15px; color: white; font-family: Times New Roman;">Recherche</span>
			</a>
		</div>
	</li>
		<!-- MENU ***DECES** -->
		<li id="deces"><a href=""> <span
			style="margin-left: 0px; color: #48ce77; font-weight: bold; font-size: 20px; font-family: Times New Roman;">
				<img id="image" style="display: inline;"
				src='<?php echo $this->basePath().'/images_icons/plus-green1.png'?>'
				alt='Liste' /> Consultations
		</span></a></li>

	<li id="plus_deces" style="background: #4a5765;">

		<div style="margin-left: 30px; height: 40px; padding-top: 20px;">
			<a
				href="<?php echo $this->url('orl', array('action'=> 'liste-consultation'));?>">
				<span id="declarer_style"
				style="margin-left: 5px; color: white; font-size: 15px; font-family: Times New Roman;"><img
					style="display: inline;"
					src='<?php echo $this->basePath().'/images_icons/dossier.PNG'?>'
					alt='Liste' /> En cours ...</span>
			</a>
		</div>

		<div style="margin-left: 30px; height: 40px;">
			<a
				href="<?php echo $this->url('orl', array('action'=> 'espace-recherche-med'));?>">
				<!-- test-mp3 ---- espace-recherche-med --> <img
				style="margin-left: 5px; display: inline;"
				src='<?php echo $this->basePath().'/images_icons/Search_22.PNG'?>'
				alt='Liste' /> <span id="liste_recherche_style"
				style="font-size: 15px; color: white; font-family: Times New Roman;">
					Recherche </span>
			</a>
		</div>
	</li>
		

	<!-- MENU ***MEDECIN DE SERVICE*** -->
	<!-- MENU ***MEDECIN DE SERVICE*** -->
	<!-- MENU ***MEDECIN DE SERVICE*** -->

	<!-- MENU ***ADMISSION AU BLOC*** -->
	<li id="admissionbloc"><a href=""> <span
			style="margin-left: 0px; color: #48ce77; font-weight: bold; font-size: 20px; font-family: Times New Roman;">
				<img id="image" style="display: inline;"
				src='<?php echo $this->basePath().'/images_icons/plus-green1.png'?>'
				alt='Liste' /> Bloc op&eacute;ratoire
		</span></a></li>

	<li id="plus_admissionbloc" style="background: #4a5765;">

		<div style="margin-left: 30px; height: 40px; padding-top: 20px;">
			<a href="<?php echo $this->basePath()."/orl/protocole-operatoire";?>">
				<span id="admissionbloc_style"
				style="margin-left: 5px; color: white; font-size: 15px; font-family: Times New Roman;"><img
					style="display: inline;"
					src='<?php echo $this->basePath().'/images_icons/dossier.PNG'?>'
					alt='Liste' /> C.R.O</span>
			</a>
		</div>

		<div style="margin-left: 30px; height: 40px;">
			<a
				href="<?php echo $this->basePath()."/orl/liste-protocole-operatoire";?>">
				<img style="margin-left: 5px; display: inline;"
				src='<?php echo $this->basePath().'/images_icons/liste.PNG'?>'
				alt='Liste' /> <span id="liste_admissionbloc_style"
				style="font-size: 15px; color: white; font-family: Times New Roman;">Liste</span>
			</a>
		</div>

	</li>


	
	<!-- Menu ***Hospitalisation*** -->
	<li id="dossier_personnel"><a href=""> <span
			style="margin-left: 0px; color: #48ce77; font-weight: bold; font-size: 20px; font-family: Times New Roman;">
				<img id="image" style="display: inline;"
				src='<?php echo $this->basePath().'/images_icons/plus-green1.png'?>'
				alt='Liste' /> Hospitalisations
		</span></a></li>

	<li id="plus_dossier_personnel" style="background: #4a5765;">
		<div style="margin-left: 30px; height: 40px; padding-top: 20px;">
			<a href="<?php echo $this->basePath().'/orl/en-cours';?>"> <img
				style="margin-left: 5px; display: inline;"
				src='<?php echo $this->basePath().'/images_icons/liste.png'?>'
				alt='Liste' /> <span id="en_cours_style"
				style="font-size: 15px; color: white; font-family: Times New Roman;">En
					cours ...</span></a>
		</div>
	</li>

	<li id="separateurMenuArchive"><a> <span>...............................................</span></a>
	</li>
	<li id='archivage'>

		<div style="margin-left: 30px; height: 40px;">
			<a
				href="<?php echo $this->url('archivage', array('action'=> 'liste-dossiers-patients'));?>">
				<img style="margin-left: 5px;"
				src='<?php echo $this->basePath().'/images_icons/Folders2.png'?>' />
				<span
				style="font-size: 15px; color: white; font-family: Times New Roman;">Archivage</span>
			</a>
		</div>
	</li>
</ul>

<?php
// CHOISIR LE MENU A AFFICHER SELON QUE C'EST LE MEDECIN OU C'EST LE SURVEILLANT
$user = $this->layout ()->user;
$role = $user ['role'];

if ($role == 'surveillant') {
	?>
<script>
$("#deces").toggle(false);
$("#dossier_personnel").toggle(false);
$("#archivage").toggle(false);
</script>
<?php
} else if ($role == 'medecin') {
	?>
<script>
$("#naissance,#dossier_patient,#admission_orl").toggle(false);
</script>
<?php
}else if ($role == 'secretaire'){
?>
<script>
$('#naissance, #deces,#dossier_personnel,#admissionbloc,#archivage').toggle(false); //samedi
</script>
<?php
 } 
?>




<script>
//*********************************************************************************************************************************
//DOSSIER PATIENT
function dep_dossier_patient1(){
	$('#dossier_patient').click(function(){
		$("#dossier_patient").replaceWith("<li id='dossier_patient'><a href=''><span style='margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='../images_icons/plus-green1.png' alt='Liste' /> Dossier Patient </span></a></li>");
		dep_dossier_patient2();
	    $('#plus_dossier_patient').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

function dep_dossier_patient2(){
	$('#dossier_patient').click(function(){
		$("#dossier_patient").replaceWith("<li id='dossier_patient' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='../images_icons/moin-green2.png' alt='Liste' /> Dossier Patient </span></a></li>");
		dep_dossier_patient1();
	    $('#plus_dossier_patient').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

$('#plus_dossier_patient').toggle(false);
$('#dossier_patient').click(function(){
	$("#dossier_patient").replaceWith("<li id='dossier_patient' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='../images_icons/moin-green2.png' alt='Liste' /> Dossier Patient </span></a></li>");
	dep_admission_orl1();
$('#plus_dossier_patient').animate({
height : 'toggle'
},1000);
return false;
});
//*******************************************************************************************************************************
//admission-orl
function dep_admission_orl1(){
	$('#admission_orl').click(function(){
		$("#admission_orl").replaceWith("<li id='admission_orl'><a href=''><span style='margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='../images_icons/plus-green1.png' alt='Liste' /> Admission </span></a></li>");
		dep_admission_orl2();
	    $('#plus_admission_orl').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

function dep_admission_orl2(){
	$('#admission_orl').click(function(){
		$("#admission_orl").replaceWith("<li id='admission_orl' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='../images_icons/moin-green2.png' alt='Liste' /> Admission </span></a></li>");
		dep_admission_orl1();
	    $('#plus_admission_orl').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

$('#plus_admission_orl').toggle(false);
$('#admission_orl').click(function(){
	$("#admission_orl").replaceWith("<li id='admission_orl' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='../images_icons/moin-green2.png' alt='Liste' /> Admission </span></a></li>");
	dep_admission_orl1();
$('#plus_admission_orl').animate({
height : 'toggle'
},1000);
return false;
});
//********************************************************************************************************************************
//Rendez_vous_orl

function dep_rendez_vous_orl1(){
	$('#rendez_vous_orl').click(function(){
		$("#rendez_vous_orl").replaceWith("<li id='rendez_vous_orl'><a href=''><span style='margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='../images_icons/plus-green1.png' alt='Liste' /> Rendez-vous </span></a></li>");
		dep_rendez_vous_orl2();
	    $('#plus_rendez_vous_orl').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

function dep_rendez_vous_orl2(){
	$('#rendez_vous_orl').click(function(){
		$("#rendez_vous_orl").replaceWith("<li id='rendez_vous_orl' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='../images_icons/moin-green2.png' alt='Liste' />Rendez-vous </span></a></li>");
		dep_rendez_vous_orl1();
	    $('#plus_rendez_vous_orl').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

$('#plus_rendez_vous_orl').toggle(false);
$('#rendez_vous_orl').click(function(){
	$("#rendez_vous_orl").replaceWith("<li id='rendez_vous_orl' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='../images_icons/moin-green2.png' alt='Liste' /> Rendez-vous </span></a></li>");
	dep_rendez_vous_orl1();
$('#plus_rendez_vous_orl').animate({
height : 'toggle'
},1000);
return false;
});

//*******************************************************************************************************************************







//NAISSANCE
function dep1(){
	$('#naissance').click(function(){
		$("#naissance").replaceWith("<li id='naissance'><a href=''><span style='margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='../images_icons/plus-green1.png' alt='Liste' /> Consultations </span></a></li>");
		dep2();
	    $('#plus_naissance').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

function dep2(){
	$('#naissance').click(function(){
		$("#naissance").replaceWith("<li id='naissance' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='../images_icons/moin-green2.PNG' alt='Liste' /> Consultations </span></a></li>");
		dep1();
	    $('#plus_naissance').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

$('#plus_naissance').toggle(false);
$('#naissance').click(function(){
	$("#naissance").replaceWith("<li id='naissance' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='../images_icons/moin-green2.png' alt='Liste' /> Consultations </span></a></li>");
	dep1();
    $('#plus_naissance').animate({
        height : 'toggle'
    },1000);
 return false;
});

//*******************************************************************************************************************************
//MEDECIN DE SERVICE
function dep_deces1(){
	$('#deces').click(function(){
		$("#deces").replaceWith("<li id='deces'><a href=''><span style='margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='../images_icons/plus-green1.png' alt='Liste' /> Consultations </span></a></li>");
		dep_deces2();
	    $('#plus_deces').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

function dep_deces2(){
	$('#deces').click(function(){
		$("#deces").replaceWith("<li id='deces' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='../images_icons/moin-green2.png' alt='Liste' /> Consultations </span></a></li>");
		dep_deces1();
	    $('#plus_deces').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

$('#plus_deces').toggle(false);
$('#deces').click(function(){
	$("#deces").replaceWith("<li id='deces' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='../images_icons/moin-green2.png' alt='Liste' /> Consultations </span></a></li>");
	dep_deces1();
$('#plus_deces').animate({
    height : 'toggle'
},1000);
return false;
});

//*******************************************************************************************************************************
//HOSPITALISATION
function dep_dossier_personnel1(){
	$('#dossier_personnel').click(function(){
		$("#dossier_personnel").replaceWith("<li id='dossier_personnel'><a href=''><span style='margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='../images_icons/plus-green1.png' alt='Liste' /> Hospitalisations </span></a></li>");
		dep_dossier_personnel2();
	    $('#plus_dossier_personnel').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

function dep_dossier_personnel2(){
	$('#dossier_personnel').click(function(){
		$("#dossier_personnel").replaceWith("<li id='dossier_personnel' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='../images_icons/moin-green2.png' alt='Liste' /> Hospitalisations </span></a></li>");
		dep_dossier_personnel1();
	    $('#plus_dossier_personnel').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

$('#plus_dossier_personnel').toggle(false);
$('#dossier_personnel').click(function(){
	$("#dossier_personnel").replaceWith("<li id='dossier_personnel' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='../images_icons/moin-green2.png' alt='Liste' /> Hospitalisations </span></a></li>");
	dep_dossier_personnel1();
$('#plus_dossier_personnel').animate({
height : 'toggle'
},1000);
return false;
});

//*******************************************************************************************************************************
//ADMISSION
function dep_admissionbloc1(){
	$('#admissionbloc').click(function(){
		$("#admissionbloc").replaceWith("<li id='admissionbloc'><a href=''><span style='margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='../images_icons/plus-green1.png' alt='Liste' /> Bloc op&eacute;ratoire </span></a></li>");
		dep_admissionbloc2();
	    $('#plus_admissionbloc').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

function dep_admissionbloc2(){
	$('#admissionbloc').click(function(){
		$("#admissionbloc").replaceWith("<li id='admissionbloc' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='../images_icons/moin-green2.png' alt='Liste' /> Bloc op&eacute;ratoire </span></a></li>");
		dep_admissionbloc1();
	    $('#plus_admissionbloc').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

$('#plus_admissionbloc').toggle(false);
$('#admissionbloc').click(function(){
	$("#admissionbloc").replaceWith("<li id='admissionbloc' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='../images_icons/moin-green2.png' alt='Liste' /> Bloc op&eacute;ratoire </span></a></li>");
	dep_admissionbloc1();
$('#plus_admissionbloc').animate({
height : 'toggle'
},1000);
return false;
});

</script>