
<?php use Facturation\View\Helper\DateHelper; ?>

<!-- SCRIPT DU NOUVEAU CODE POUR LA GESTION DES IMAGES  -->
<!-- SCRIPT DU NOUVEAU CODE POUR LA GESTION DES IMAGES  -->
<!-- SCRIPT DU NOUVEAU CODE POUR LA GESTION DES IMAGES  -->
<?php 
    echo $this->headLink()->appendStylesheet($this->basePath().'/css/pikachoose/bottom.css');
    echo  $this->headScript()->appendFile($this->basePath().'/js/plugins/pikachoose/jquery.jcarousel.min.js');
    echo  $this->headScript()->appendFile($this->basePath().'/js/plugins/pikachoose/jquery.pikachoose.min.js');
?>

<!-- les scripts des images dans examen morphologique   -->
<?php echo $this->headScript()->appendFile($this->basePath().'/js/plugins/fancybox/source/jquery.fancybox.js');?>
<?php echo $this->headLink()->appendStylesheet($this->basePath().'/js/plugins/fancybox/source/jquery.fancybox.css');?>
<?php echo $this->headScript()->appendFile($this->basePath().'/js/orl/complementcons_accordeon_controle.js');
      echo $this->headLink()->appendStylesheet($this->basePath().'/css/mescss/bloquerDate.css'); //DatePicker
      echo $this->headScript()->appendFile($this->basePath().'/js/mesjs/bloquerDate.js'); //Pour bloquer certaines dates
      echo $this->headScript()->appendFile($this->basePath().'/js/orl/sousDossierr.js'); //Pour les sous dossiers?>

  <?php
      //RECUPERATION DE LA LISTE DES MEDICAMENTS
      $hopital = $this->liste_med;
  ?>
<script>
$(function(){
  document.getElementById('service_accueil').value="";
  document.getElementById('heure_rv').value="";
});


//POUR LE MENU GAUCHE dans -elementgauche.phtml
$('#plus_deces').toggle(true);
$("#deces").replaceWith("<li id='deces' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='<?php echo $this->basePath().'/images_icons/moin-green2.PNG';?>' alt='Liste' /> Consultations </span></a></li>");
dep_deces1();
$('#declarer_style').css({'font-weight':'bold','color':'white','font-size':'22px'});
</script>

<!--************************************************************************************************************-->
<!--===================================== BLOCAGE DES JOURS NON CONSULTABLE ====================================-->
<!--===================================== BLOCAGE DES JOURS NON CONSULTABLE ====================================-->
<!--************************************************************************************************************-->
<?php
  $Control = new DateHelper();
  $today = new \DateTime();
  $AnneeActuelle =  $today->format('Y');

  /*****Mois 1 *****/
  $leMois1 = $today->format('m'); //C'est le mois actuel ï¿½ l'heure du calendrier
  $Dimanche1 = $Control->lePremierDimancheDuMois();
  /*****Mois 2 *****(Sauf pour le douzieme mois)*/
  $leMois2 = $leMois1 +1;
  if($leMois2 == 13){ $leMois2 = 1; $AnneeActuelle = $AnneeActuelle + 1;}
  $Dimanche2 = $Control->lePremierDimancheDuMoisByDate($leMois2, $AnneeActuelle);
  /*****Mois 3 *****/
  $leMois3 = $leMois2 +1;
  if($leMois3 == 13){ $leMois3 = 1; $AnneeActuelle = $AnneeActuelle + 1;}
  $Dimanche3 = $Control->lePremierDimancheDuMoisByDate($leMois3, $AnneeActuelle);
  /*****Mois 4 *****/
  $leMois4 = $leMois3 +1;
  if($leMois4 == 13){ $leMois4 = 1; $AnneeActuelle = $AnneeActuelle + 1;}
  $Dimanche4 = $Control->lePremierDimancheDuMoisByDate($leMois4, $AnneeActuelle);

?>

<script>
  //Bloquer les 90 jours non consultable a patir du jour, du mois actuel
  /*****Mois 1*****/
  mois1 = '<?php echo $leMois1?>';
  dimanche1 = <?php echo $Dimanche1?>;
  /*****Mois 2 *****/
  if(<?php echo $leMois2?> > 9){mois2 = <?php echo $leMois2?>;}else{mois2 = '0'+'<?php echo $leMois2?>';}
  dimanche2 = <?php echo $Dimanche2?>;
  /*****Mois 3 *****/
  if(<?php echo $leMois3?> > 9){mois3 = <?php echo $leMois3?>;}else{mois3 = '0'+'<?php echo $leMois3?>';}
  dimanche3 = <?php echo $Dimanche3?>;
  /*****Mois 4 *****/
  if(<?php echo $leMois4?> > 9){mois4 = <?php echo $leMois4?>;}else{mois4 = '0'+'<?php echo $leMois4?>';}
  dimanche4 = <?php echo $Dimanche4?>;

  /***ANNEE EN COURS***/
  annee = '<?php echo $AnneeActuelle?>';

  /****************************
  *===========================
   **************************/
          bloquerDate();
  /**************************
   * ========================
   **************************/

  /*<!--************************************************************************************************************-->
    <!--===================================== FIN BLOCAGE DES JOURS NON CONSULTABLE ================================-->
    <!--===================================== FIN BLOCAGE DES JOURS NON CONSULTABLE ================================-->
    <!--************************************************************************************************************--*/

</script>
<!-- *****************images dans EXAMEN MORPHOLOGIQUE (plugins fancybox) *************** -->
<!-- *****************images dans EXAMEN MORPHOLOGIQUE (plugins fancybox) *************** -->
<!-- *****************images dans EXAMEN MORPHOLOGIQUE (plugins fancybox) *************** -->
<script>
    function getservices(cle)
    { 
         $.ajax({
            type: 'POST',
            url: '<?php echo $this->basePath().'/orl/services' ?>',
            data: 'id='+cle,
            success: function(data) {
                var result = jQuery.parseJSON(data);
                $("#service_accueil").html(result);
          },
          error:function(e){console.log(e);alert("Une erreur interne est survenue!");},
            dataType: "html"
        });

        return false;
     }

    //CODE POUR LA PARTIE DES ANTECEDENTS
    $(function() {
    	$( "#tabsSousDossier" ).tabs();
    	$( "#tabsAntecedents" ).tabs();
    	$( "#tabs" ).tabs();
    	$( "#tabsInstrumental" ).tabs();
    	$('#tabs-traitement-chirurgical').tabs();
    	$('#tabsCompteRendu').tabs();
    	$('#tabsSurveillance').tabs();
    });
    //pagination2();
    //pagination();
    AntecedentScript();
</script>

<style type='text/css'>
#choix_sous_dossier td {
	border: 2px solid #eeeeee;
	padding-left: 5px;
	font-family: times new roman;
}

#choix_sous_dossier td input {
	margin-left: 5px;
}

/*** Bouton input submit***/
/*** Bouton input submit***/
/*** Bouton input submit***/
.transf,.rendezvous,.ordonnance {
	width: 32px;
	height: 32px;
	background: url(<? php //echo $ this- > basePath()."/images_icons/pdf.PNG"?>)
		no-repeat right top;
}

.annulertransfert,.annulerrendezvous,.annulerhospitalisation {
	position: relative;
	width: 32px;
	height: 32px;
	background: url(<? php //echo $ this- > basePath()."/images_icons/annuler.PNG"?>)
		no-repeat right top;
	display: inline;
	float: right;
	border: transparent;
	margin-bottom: 5px;
}

.transf,.rendezvous {
	display: inline;
	float: left;
	border: transparent;
	margin-bottom: 5px;
	title: 'Imprimer';
}

.ordonnance {
	display: inline;
	border: transparent;
	margin-bottom: 5px;
	title: 'Imprimer';
	position: relative;
	float: right;
}

.transf input,.rendezvous input,.ordonnance input,.annulertransfert input,.annulerrendezvous input,.annulerhospitalisation input
	{
	right: 0;
	top: 0;
	font-size: 100px;
	opacity: 0;
	-moz-opacity: 0;
	filter: alpha(opacity = 0);
	cursor: pointer;
	text-align: right;
	width: 32px;
	height: 32px;
}
</style>

<!-- *****************FINNNNNN images dans EXAMEN MORPHOLOGIQUE (plugins fancybox) *********** -->
<!-- *****************FINNNNNN images dans EXAMEN MORPHOLOGIQUE (plugins fancybox) *********** -->

<style>
#medicament input[type="text"] { /*le input ou le textarea*/
	background-color: #fffffa; /*la couleur du champ*/
	height: 25px; /*la hauteur du champ input*/
	width: 190px; /* la largeur du champ input*/
}

#posologie input[type="text"] { /*le input ou le textarea*/
	background-color: #fffffa; /*la couleur du champ*/
	height: 25px; /*la hauteur du champ input*/
	width: 190px; /* la largeur du champ input*/
}

#quantite input[type="text"] { /*le input ou le textarea*/
	background-color: #fffffa; /*la couleur du champ*/
	height: 25px; /*la hauteur du champ input*/
	width: 190px; /* la largeur du champ input*/
}

#duree input[type="text"] { /*le input ou le textarea*/
	background-color: #fffffa; /*la couleur du champ*/
	height: 25px; /*la hauteur du champ input*/
	width: 190px; /* la largeur du champ input*/
}

#etat_civil {
	color: green;
	width: 70%;
}

#etat_civil td {
	vertical-align: top;
}

#etat_civil td p {
	margin-right: 15px;
	max-height: 46px;
	max-width: 95%;
	overflow: auto;
}

#etat_civil tr {
	width: 70%;
}

#contenu {
	visibility: hidden
}
</style>

<script>
    $(window).load(function () {

    	$('#wait').toggle(false);
    	$('#contenu').fadeIn().css({'visibility':'visible'});
    	 
    });
</script>

<div id="wait"
	style="color: gray; font-size: 20px; text-align: center; margin-top: 80px;">
	<span> Chargement ... </span>
</div>

<div id="contenu">
    <?php echo $this->headLink()->appendStylesheet($this->basePath().'/css/messtyles.css');?>

    <?php 
    $form = $this->form;
    $form->setName('AVIS');
    $form->setAttribute('action', $this->url('orl', array('action'=>'impression-Pdf')));
    $form->setAttribute('target', '_blank');
    $form->setAttribute('method', 'post');
    $form->prepare();
    echo $this->form()->openTag($form); ?>

<div id="accordions">
		<!-- couleur bleu du logo//#49afcd-->

		<!--*************** Accordeon ETAT CIVIL ******************-->
		<!--*************** Accordeon ETAT CIVIL ********************-->
		<!--*************** Accordeon ETAT CIVIL ********************-->
		<!--*1*-->
		<div
			style='width: 160px; font-family: police2; font-size: 17px; font-weight: bold;'>Etat
			Civil</div>
		<div id="divEtatcivil" style='max-height: 350px;'>

			<img id="faces"
				src='<?php echo $this->basePath().'/img/photos_patients/'.$this->image;?>'
				alt="Jonathan Verrecchia"
				style='float: left; margin-right: 40px; width: 105px; height: 105px;' />

			<div
				style='left: 50px; top: 160px; font-family: time new romans; position: absolute;'>
				Age: <span
					style='font-size: 19px; font-family: time new romans; color: green; font-weight: bold;'> <?php echo $this->lesdetails['AGE']; ?> ans </span>
			</div>

			<p style='color: white; opacity: 0.09;'>
				<img id="faces"
					src='<?php echo $this->basePath().'/img/photos_patients/'.$this->image;?>'
					alt="Jonathan Verrecchia"
					style='float: right; margin-right: 15px; width: 95px; height: 95px;' />
			</p>
			<table id="etat_civil">
				<tr>
					<td style='width: 27%; font-family: police1; font-size: 12px;'>
						<div id="aa">
							<a style="text-decoration: underline;">Pr&eacute;nom</a><br>
							<p style='font-weight: bold; font-size: 17px;'><?php echo $this->lesdetails['PRENOM'];?></p>
						</div>
					</td>

					<td style='width: 35%; font-family: police1; font-size: 12px;'>
						<div id="aa">
							<a style="text-decoration: underline;">Lieu de naissance</a><br>
							<p style='font-weight: bold; font-size: 17px;'><?php echo $this->lesdetails['LIEU_NAISSANCE'];?></p>
						</div>
					</td>

					<td style='width: 38%; font-family: police1; font-size: 12px;'>
						<div id="aa">
							<a style="text-decoration: underline;">T&eacute;l&eacute;phone</a><br>
							<p style='font-weight: bold; font-size: 17px;'><?php echo $this->lesdetails['TELEPHONE'];?></p>
						</div>
					</td>

				</tr>

				<tr>
					<td style='font-family: police1; font-size: 12px;'>
						<div id="aa">
							<a style="text-decoration: underline;">Nom</a><br>
							<p style='font-weight: bold; font-size: 19px;'><?php echo $this->lesdetails['NOM'];?></p>
						</div>
					</td>

					<td style='font-family: police1; font-size: 12px;'>
						<div id="aa">
							<a style="text-decoration: underline;">Nationalit&eacute; origine</a><br>
							<p style='font-weight: bold; font-size: 19px;'><?php echo $this->lesdetails['NATIONALITE_ORIGINE'];?></p>
						</div>
					</td>

					<td style='font-family: police1; font-size: 12px;'>
						<div id="aa">
							<a style="text-decoration: underline;">Email</a><br>
							<p style='font-weight: bold; font-size: 19px;'><?php echo $this->lesdetails['EMAIL'];?></p>
						</div>
					</td>

				</tr>

				<tr>
					<td style='font-family: police1; font-size: 12px;'>
						<div id="aa">
							<a style="text-decoration: underline;">Sexe</a><br>
							<p style='font-weight: bold; font-size: 19px;'><?php echo $this->lesdetails['SEXE'];?></p>
						</div>
					</td>

					<td style='font-family: police1; font-size: 12px;'>
						<div id="aa">
							<a style="text-decoration: underline;">Nationalit&eacute;
								actuelle</a><br>
							<p style='font-weight: bold; font-size: 19px;'><?php echo $this->lesdetails['NATIONALITE_ACTUELLE'];?></p>
						</div>
					</td>

					<td style='font-family: police1; font-size: 12px;'>
						<div id="aa">
							<a style="text-decoration: underline;">Profession</a><br>
							<p style='font-weight: bold; font-size: 19px;'><?php echo $this->lesdetails['PROFESSION'];?></p>
						</div>
					</td>

				</tr>

				<tr>
					<td
						style='width: 27%; font-family: police1; font-size: 12px; vertical-align: top;'>

						<div id="aa">
							<a style="text-decoration: underline;">Date de naissance</a><br>
							<p style='font-weight: bold; font-size: 19px;'>
			   		    <?php 
			   		    $date_naissance = $this->lesdetails['DATE_NAISSANCE'];
			   		    if($date_naissance){ echo $Control->convertDate($this->lesdetails['DATE_NAISSANCE']); }else{ echo "";}
			   		    ?> 
			   		  </p>
						</div>

					</td>

					<td
						style='display: "block"; font-family: police1; font-size: 12px;'>
						<div id="aa">
							<a style="text-decoration: underline;">Adresse</a><br>
							<p style='font-weight: bold; font-size: 19px;'><?php echo $this->lesdetails['ADRESSE'];?></p>
						</div>

					</td>

					<td
						style='display: "block"; font-family: police1; font-size: 12px; text-align: right;'>
			   	
			   	    <?php if($this->resultRV){?>
			   	       <span id='image-neon'
						style='color: red; font-weight: bold; font-size: 17px;'>Rendez-vous &agrave; <?php echo $this->resultRV; ?> </span>
			   	       
			   	    <?php } ?>
			   	</td>
				</tr>
			</table>

			<script>
          function FaireClignoterImage (){
                  $('#image-neon').fadeOut(900).delay(300).fadeIn(800);
          }
          setInterval('FaireClignoterImage()',2200);
		    </script>

			<div id="barre"></div>
			<div
				style='color: white; opacity: 1; width: 95px; height: 40px; float: right'>
				<img src='<?php echo $this->basePath().'/images_icons/fleur1.jpg'?>'
					alt="fleur1" />
			</div>

			<table id="numero" style="padding-top: 5px; width: 550px;">
				<tr style="width: 550px;">
					<td style="padding-top: 5px; width: 70px; font-size: 12px;">
						Consultation:</td>
					<td style="font-weight: bold;"> <?php echo $this->id_cons;?></td>
					<td style="font-weight: bold; width: 10px;">|</td>
					<td style="padding-top: 5px; width: 80px; font-size: 12px;">Date ET
						Heure:</td>
					<td style="font-weight: bold;"> <?php echo $Control->convertDate($this->dateonly);?>  -  <?php echo $this->heure_cons;?></td>
				</tr>
			</table>

		</div>
		
		
		
		   	    <!-- ******************** SOUS-DOSSIERS TEMPORAIRE ******************-->
				<!-- ******************** SOUS-DOSSIERS TEMPORAIRE ******************-->
				<!-- ******************** SOUS-DOSSIERS TEMPORAIRE******************-->
        
    

				<div
					style='font-family: police2; font-size: 17px; font-weight: bold;'>Sous-Dossiers
				</div>
				
	            <div style="max-height: 100px; padding-bottom: 0px;">
				
				  <table   class="sous_dossier" style="width: 20%;">
				
					 <tr class="form-rendezvous" style="width: 100%;">
					
					   <th class="form-rendezvous2" style="width: 17%;"> <?php echo $this->formRow($form->get('sous_dossier'));?> </th>
					
					 </tr>
				
				  </table>
          
	            </div>
		



		<!-- ********************Antécédents ou Terrain particulier ******************-->
		<!-- ********************Antécédents ou Terrain particulier ******************-->
		<!-- ********************Antécédents ou Terrain particulier ******************-->

		<div style='font-family: police2; font-size: 17px; font-weight: bold;'>Ant&eacutec&eacutedents
			ou Suivie</div>
		<div style='max-height: 410px;'>
			<div id="tabsAntecedents">
				<ul>
					<li><a href="#tabss-1">Ant&eacutec&eacutedents G&eacuten&eacuteraux</a></li>
					<li><a href="#tabss-2">Ant&eacutec&eacutedents Sp&eacutecifiques</a></li>
					<li><a href="#tabss-3">Suivie</a></li>
				</ul>

				<div id="tabss-1">

					<!--****** ================== ANTECEDENTS TERRAIN PARTICULIER ================== ****** -->
					<!--****** ================== ANTECEDENTS TERRAIN PARTICULIER ================== ****** -->
					<!--****** ================== ANTECEDENTS TERRAIN PARTICULIER ================== ****** -->
					<table id="MenuTerrainParticulier" style="width: 100%;">
						<tr style="width: 100%;">
							<td style="width: 50%;">
								<div>
									<img class="image1_TP"
										style='cursor: pointer; position: relative; left: 15%; width: 60%; height: 60%;'
										src='<?php echo $this->basepath().'/images_icons/antecedentPers2.png'?>' />
								</div>
							</td>
							<td style="width: 50%;">
								<div>
									<img class="image2_TP"
										style='cursor: pointer; position: relative; left: 15%; width: 60%; height: 60%;'
										src='<?php echo $this->basepath().'/images_icons/antecedentsfam.png'?>' />
								</div>
							</td>
						</tr>
					</table>

					<!--****** ================== ANTECEDENTS PERSONNELS ================== ****** -->
					<!--****** ================== ANTECEDENTS PERSONNELS ================== ****** -->
					<table id="MenuAntecedentPersonnel" style="width: 100%;">
						<tr style="width: 100%;">
							<td style=""><img class="image_fleche" style='cursor: pointer;'
								src='<?php echo $this->basepath().'/images_icons/flecheg.png'?>'
								title="pr&eacute;c&eacute;dent" style='' /></td>
						</tr>
						<tr style="width: 100%;">
							<td style="width: 25%;">
								<div>
									<img class="image1_AP" style='cursor: pointer; width: 100%;'
										src='<?php echo $this->basepath().'/images_icons/image1_AP.png'?>'
										style='' />
								</div>
							</td>
							<td style="width: 25%;">
								<div>
									<img class="image2_AP" style='cursor: pointer; width: 100%;'
										src='<?php echo $this->basepath().'/images_icons/image2_AP.png'?>'
										style='' />
								</div>
							</td>
							<td style="width: 25%;">
								<div>
									<img class="image3_AP" style='cursor: pointer; width: 100%;'
										src='<?php echo $this->basepath().'/images_icons/image3_AP.png'?>'
										style='' />
								</div>
							</td>
							<td style="width: 25%;"></td>
						</tr>
					</table>
					<script> 
             $(".image4_AP").toggle(false);
             if("<?php echo $this->lesdetails['SEXE'];?>" != "Masculin" ){ $(".image4_AP").toggle(true); }
           </script>

					<table id="HabitudesDeVie" style="width: 100%;">
						<tr style="width: 100%;">
							<td style="">
								<div
									style="width: 100%; font-family: Times New Roman; color: green; font-size: 17px; font-weight: bold; padding-bottom: 10px;">
									<iS style='font-size: 25px;'>&curren;</iS>
									LES HABITUDES DE VIE
								</div>
							</td>
						</tr>
						<tr style="width: 100%;">
							<td id="BUcheckbox" style="">
								<div style="float: left;">
									<label style="width: 100px; height: 30px; text-align: right;">Alcoolique <?php echo $this->formRow($form->get('AlcooliqueHV'));?></label>
								</div>
								<div style="float: left" id="dateDebAlcoolique">
									<label style="width: 220px; height: 30px; text-align: right;">Date d&eacute;but <?php echo $this->formRow($form->get('DateDebutAlcooliqueHV'));?> </label>
								</div>
								<div style="float: left" id="dateFinAlcoolique">
									<label style="width: 220px; height: 30px; text-align: right;">Date d'arr&ecirc;t <?php echo $this->formRow($form->get('DateFinAlcooliqueHV'));?></label>
								</div>
							</td>
						</tr>
						<tr style="width: 100%;">
							<td id="BUcheckbox" style="">
								<div style="float: left;">
									<label style="width: 100px; height: 30px; text-align: right;">Fumeur <?php echo $this->formRow($form->get('FumeurHV'));?></label>
								</div>
								<div style="float: left" id="dateDebFumeur">
									<label style="width: 220px; height: 30px; text-align: right;">Date d&eacute;but <?php echo $this->formRow($form->get('DateDebutFumeurHV'));?></label>
								</div>
								<div style="float: left" id="dateFinFumeur">
									<label style="width: 220px; height: 30px; text-align: right;">Date d'arr&ecirc;t <?php echo $this->formRow($form->get('DateFinFumeurHV'));?></label>
								</div>
								<div style="float: left" id="nbPaquetJour">
									<label style="width: 190px; height: 30px; text-align: right;">Nbre de paquets/jour <?php echo $this->formRow($form->get('nbPaquetFumeurHV'));?></label>
								</div>
								<div style="float: left" id="nbPaquetAnnee">
									<label style="width: 110px; height: 30px; text-align: right;">
										--- nbPaquet/an --- </label>
								</div>
							</td>
						</tr>
						<tr style="width: 100%;">
							<td id="BUcheckbox" style="">
								<div style="float: left;">
									<label style="width: 100px; height: 30px; text-align: right;">Drogu&eacute;  <?php echo $this->formRow($form->get('DroguerHV'));?></label>
								</div>
								<div style="float: left" id="dateDebDroguer">
									<label style="width: 220px; height: 30px; text-align: right;">Date d&eacute;but <?php echo $this->formRow($form->get('DateDebutDroguerHV'));?></label>
								</div>
								<div style="float: left" id="dateFinDroguer">
									<label style="width: 220px; height: 30px; text-align: right;">Date d'arr&ecirc;t <?php echo $this->formRow($form->get('DateFinDroguerHV'));?></label>
								</div>
							</td>
						</tr>
						<tr style="width: 100%;">
							<td id="BUcheckbox" style="">
								<div style="float: left;">
									<label style="width: 100px; height: 30px; text-align: right;">Autres  <?php echo $this->formRow($form->get('AutresHV'));?></label>
								</div>
								<div style="float: left" id="DivNoteAutresHV">
									<label style="width: 350px; height: 30px; text-align: right;">Note <?php echo $this->formRow($form->get('NoteAutresHV'));?></label>
								</div>
							</td>
						</tr>


						<tr style="width: 100%;">
							<td class='block' id='thoughtbot'
								style='display: inline-block; vertical-align: bottom; width: 100%; padding-bottom: 5px; padding-top: 15px;'><div
									style="float: left;" id="TerminerHabitudeDeVie">Terminer</div></td>
						
						
						<tr>
					
					</table>

					<table id="AntecedentMedicaux" style="width: 100%;">
						<tr style="width: 100%;">
							<td colspan="3" style="width: 60%;">
								<div
									style="font-family: Times New Roman; color: green; font-size: 17px; font-weight: bold; padding-bottom: 10px;">
									<iS style='font-size: 25px;'>&curren;</iS>
									LES ANT&Eacute;C&Eacute;DENTS M&Eacute;DICAUX
								</div>
							</td>
							<td></td>
							<td></td>
						</tr>
						<tr style="width: 100%; height: 50px;">
							<td id="BUcheckbox" style="width: 20%;">
								<div>
									<label
										style="width: 90%; height: 30px; text-align: right; font-family: time new romans; font-size: 18px;">
										<span> <img class="imageValiderDiabeteAM"
											style='cursor: pointer; padding-right: 10px;'
											src='<?php echo $this->basepath().'/images_icons/tick-icon2.png'?>' />
									</span> 
                         
                         Diab&egrave;te 
                         <?php echo $this->formRow($form->get('DiabeteAM'));?>
                      </label>
								</div>
							</td>

							<td id="BUcheckbox" style="width: 20%;">
								<div>
									<label
										style="width: 90%; height: 30px; text-align: right; font-family: time new romans; font-size: 18px;">
										<span> <img class="imageValiderHtaAM"
											style='cursor: pointer; padding-right: 10px;'
											src='<?php echo $this->basepath().'/images_icons/tick-icon2.png'?>' />
									</span> 
                         
                        HTA 
                        <?php echo $this->formRow($form->get('htaAM'));?>
                     </label>
								</div>
							</td>

							<td id="BUcheckbox" style="width: 20%;">
								<div>
									<label
										style="width: 90%; height: 30px; text-align: right; font-family: time new romans; font-size: 18px;">
										<span> <img class="imageValiderDrepanocytoseAM"
											style='cursor: pointer; padding-right: 0px;'
											src='<?php echo $this->basepath().'/images_icons/tick-icon2.png'?>' />
									</span> 
                        
                        Dr&eacute;panocytose <?php echo $this->formRow($form->get('drepanocytoseAM'));?>
                     </label>
								</div>
							</td>

							<td id="BUcheckbox" style="width: 20%;">
								<div>
									<label
										style="width: 90%; height: 30px; text-align: right; font-family: time new romans; font-size: 18px;">
										<span> <img class="imageValiderDislipidemieAM"
											style='cursor: pointer; padding-right: 10px;'
											src='<?php echo $this->basepath().'/images_icons/tick-icon2.png'?>' />
									</span>  
                        
                        Dislipid&eacute;mie  <?php echo $this->formRow($form->get('dislipidemieAM'));?>
                     </label>
								</div>
							</td>

							<td id="BUcheckbox" style="width: 20%;">
								<div>
									<label
										style="width: 90%; height: 30px; text-align: right; font-family: time new romans; font-size: 18px;">
										<span> <img class="imageValiderAsthmeAM"
											style='cursor: pointer; padding-right: 10px;'
											src='<?php echo $this->basepath().'/images_icons/tick-icon2.png'?>' />
									</span> 
                     
                        Asthme  <?php echo $this->formRow($form->get('asthmeAM'));?>
                     </label>
								</div>
							</td>

						</tr>
                <tr id="labelDesAntecedentsMedicaux_1" style="width:100%;">
                  <!-- Emplacement des autres antecedents médicaux ajouter à partir du champ autre -->
                </tr>
                
                
                <tr style="width:100%;">
                  <td id="BUcheckbox" colspan="3" style="width:60%;" >
                    <div id="imageIconeAjouterLabel">
                      <?php echo $this->formRow($form->get('nbCheckboxAM'));?>
                      <label style="width: 55%; height:30px; text-align:right;">
                        Autres  <?php echo $this->formRow($form->get('autresAM'));?>
                        <img id="imgIconeAjouterLabel" style='cursor: pointer; padding-right: 5px; padding-left: 10px; padding-bottom: 6px;' src='<?php echo $this->basepath().'/images_icons/Add14X14.png'?>' />  
                      </label>
                    </div>
                  </td>
                  <td>  </td>
                  <td>  </td>
                  <td>  </td>
                  <td>  </td>
                </tr>
                
                <tr style="width:100%;">
                   <td class='block' id='thoughtbot' style='display: inline-block;  vertical-align: bottom; width:20%; padding-bottom: 5px; padding-top: 35px;'><div style="float:left;" id="TerminerAntecedentMedicaux">Terminer</div></td>
                   <td>  </td>
                   <td>  </td>
                   <td>  </td>
                   <td>  </td>
                <tr>
           </table>
           
           
           <script> 
              var myArrayAntMed = [''];
              var i = 1;
           </script>
           <?php foreach ($this->listeAntMed as $antMed){ ?>
             <script> myArrayAntMed[i++] =  "<?php echo $antMed['libelle']; ?>" </script>
           <?php } ?>
           <script> 
        	  autocompletionAntecedent(myArrayAntMed);
           </script>
           
           
           
           <script> 
              var myArrayAntMedPat = [''];
              var i = 1;
           </script>
           <?php foreach ($this->antMedPat as $antMed){ ?>
             <script> myArrayAntMedPat[i++] =  "<?php echo $antMed['libelle']; ?>" </script>
           <?php } ?>
           <script> 
           $('#nbCheckboxAM').val('<?php echo $this->nbAntMedPat;?>');
           setTimeout(function(){
        	   affichageAntecedentsMedicauxDuPatient('<?php echo $this->nbAntMedPat;?>' , myArrayAntMedPat);
           }, 500);
           </script>

					<table id="AntecedentChirurgicaux" style="width: 100%;">
						<tr style="width: 100%;">
							<td style="">
								<div
									style="width: 100%; font-family: Times New Roman; color: green; font-size: 17px; font-weight: bold; padding-bottom: 10px;">
									<iS style='font-size: 20px;'>&curren;</iS>
									LES ANT&Eacute;C&Eacute;DENTS CHIRURGICAUX
								</div>
							</td>
						</tr>
						<tr class="form-chirurgical" style="width: 100%;">
							<td style="width: 33%;"> <?php //echo $this->formRow($form->get('observation'));?> </td>
						</tr>

						<tr style="width: 100%;">
							<td class='block' id='thoughtbot'
								style='display: inline-block; vertical-align: bottom; width: 100%; padding-bottom: 5px;'><div
									style="float: left;" id="TerminerAntecedentChirurgicaux">Terminer</div></td>
						
						
						<tr>
					
					</table>

					<table id="GynecoObstetrique" style="width: 100%;">
						<tr style="width: 100%;">
							<td style="">
								<div
									style="width: 100%; font-family: Times New Roman; color: green; font-size: 17px; font-weight: bold; padding-bottom: 10px;">
									<iS style='font-size: 25px;'>&curren;</iS>
									GYNECO-OBST&Eacute;TRIQUE
								</div>
							</td>
						</tr>
						<tr style="width: 100%;">
							<td id="BUcheckbox" style="">
								<div style="float: left;">
									<label style="width: 120px; height: 30px; text-align: right;">M&eacute;narche <?php echo $this->formRow($form->get('MenarcheGO'));?></label>
								</div>
								<div style="float: left" id="NoteMonarche">
									<label style="width: 260px; height: 30px; text-align: right;">Note <?php echo $this->formRow($form->get('NoteMenarcheGO'));?></label>
								</div>
							</td>
						</tr>
						<tr style="width: 100%;">
							<td id="BUcheckbox" style="">
								<div style="float: left;">
									<label style="width: 120px; height: 30px; text-align: right;">Gestit&eacute; <?php echo $this->formRow($form->get('GestiteGO'));?></label>
								</div>
								<div style="float: left" id="NoteGestite">
									<label style="width: 260px; height: 30px; text-align: right;">Note <?php echo $this->formRow($form->get('NoteGestiteGO'));?></label>
								</div>
							</td>
						</tr>
						<tr style="width: 100%;">
							<td id="BUcheckbox" style="">
								<div style="float: left;">
									<label style="width: 120px; height: 30px; text-align: right;">Parit&eacute; <?php echo $this->formRow($form->get('PariteGO'));?></label>
								</div>
								<div style="float: left" id="NoteParite">
									<label style="width: 260px; height: 30px; text-align: right;">Note <?php echo $this->formRow($form->get('NotePariteGO'));?></label>
								</div>
							</td>
						</tr>
						<tr style="width: 100%;">
							<td id="BUcheckbox" style="">
								<div style="float: left;">
									<label style="width: 120px; height: 30px; text-align: right;">Cycle <?php echo $this->formRow($form->get('CycleGO'));?></label>
								</div>
								<div style="float: left;" id="DureeGO">
									<label style="width: 120px; height: 30px; text-align: right;">Dur&eacute;e <?php echo $this->formRow($form->get('DureeCycleGO'));?> </label>
								</div>

								<div style="float: left" id="RegulariteON">
									<label style="width: 160px; height: 30px; text-align: right;">
                         R&eacute;gularit&eacute; 
                         <?php echo $this->formRow($form->get('RegulariteCycleGO'));?>
                      </label>
								</div>
								<div style="float: left" id="DysmenorrheeON">
									<label style="width: 160px; height: 30px; text-align: right;">
                         Dysm&eacute;norrh&eacute;e
                         <?php echo $this->formRow($form->get('DysmenorrheeCycleGO'));?>
                      </label>
								</div>

							</td>
						</tr>
						<tr style="width: 100%;">
							<td id="BUcheckbox" style="">
								<div style="float: left;">
									<label style="width: 120px; height: 30px; text-align: right;">Autres <?php echo $this->formRow($form->get('AutresGO'));?></label>
								</div>
								<div style="float: left" id="DivNoteAutresGO">
									<label style="width: 260px; height: 30px; text-align: right;">Note <?php echo $this->formRow($form->get('NoteAutresGO'));?></label>
								</div>
							</td>
						</tr>

						<tr style="width: 100%;">
							<td class='block' id='thoughtbot'
								style='display: inline-block; vertical-align: bottom; width: 100%; padding-bottom: 5px; padding-top: 15px;'><div
									style="float: left;" id="TerminerGynecoObstetrique">Terminer</div></td>
						
						
						<tr>
					
					</table>
					<script>
             var temoinAlcoolique = <?php echo $this->donneesAntecedentsPersonnels['AlcooliqueHV'];?>;
             var temoinFumeurHV   = <?php echo $this->donneesAntecedentsPersonnels['FumeurHV'];?>; var nbPaquetFumeurHV = <?php echo (float)$this->donneesAntecedentsPersonnels['nbPaquetFumeurHV'];?>;
             var temoinDroguerHV  = <?php echo $this->donneesAntecedentsPersonnels['DroguerHV'];?>;

             var temoinDiabeteAM = <?php echo $this->donneesAntecedentsPersonnels['DiabeteAM'];?>;
             var temoindrepanocytoseAM = <?php echo $this->donneesAntecedentsPersonnels['drepanocytoseAM'];?>;
             var temoinhtaAM = <?php echo $this->donneesAntecedentsPersonnels['htaAM'];?>;
             var temoindislipidemieAM = <?php echo $this->donneesAntecedentsPersonnels['dislipidemieAM'];?>;
             var temoinasthmeAM = <?php echo $this->donneesAntecedentsPersonnels['asthmeAM'];?>;
             
             var temoinMenarcheGO = <?php echo $this->donneesAntecedentsPersonnels['MenarcheGO'];?>;
             var temoinGestiteGO = <?php echo $this->donneesAntecedentsPersonnels['GestiteGO'];?>;
             var temoinPariteGO = <?php echo $this->donneesAntecedentsPersonnels['PariteGO'];?>;
             var temoinCycleGO = <?php echo $this->donneesAntecedentsPersonnels['CycleGO'];?>;
            
           </script>


					<!--****** ================== ANTECEDENTS FAMILIAUX ================== ****** -->
					<!--****** ================== ANTECEDENTS FAMILIAUX ================== ****** -->
					<table id="AntecedentsFamiliaux" style="width: 100%;">
						<tr style="width: 100%;">
							<td style="">
								<div
									style="width: 100%; font-family: Times New Roman; color: green; font-size: 17px; font-weight: bold; padding-bottom: 10px;">
									<iS style='font-size: 25px;'>&curren;</iS>
									ANT&Eacute;C&Eacute;DENTS FAMILIAUX
								</div>
							</td>
						</tr>
						<tr style="width: 100%;">
							<td id="BUcheckbox" style="">
								<div style="float: left;">
									<label style="width: 230px; height: 30px; text-align: right;">Diab&egrave;te <?php echo $this->formRow($form->get('DiabeteAF'));?></label>
								</div>
								<div style="float: left" id="DivNoteDiabeteAF">
									<label style="width: 260px; height: 30px; text-align: right;">Note <?php echo $this->formRow($form->get('NoteDiabeteAF'));?></label>
								</div>
							</td>
						</tr>
						<tr style="width: 100%;">
							<td id="BUcheckbox" style="">
								<div style="float: left;">
									<label style="width: 230px; height: 30px; text-align: right;">Dr&eacute;panocytose <?php echo $this->formRow($form->get('DrepanocytoseAF'));?></label>
								</div>
								<div style="float: left" id="DivNoteDrepanocytoseAF">
									<label style="width: 260px; height: 30px; text-align: right;">Note <?php echo $this->formRow($form->get('NoteDrepanocytoseAF'));?></label>
								</div>
							</td>
						</tr>
						<tr style="width: 100%;">
							<td id="BUcheckbox" style="">
								<div style="float: left;">
									<label style="width: 230px; height: 30px; text-align: right;">HTA <?php echo $this->formRow($form->get('htaAF'));?></label>
								</div>
								<div style="float: left" id="DivNoteHtaAF">
									<label style="width: 260px; height: 30px; text-align: right;">Note <?php echo $this->formRow($form->get('NoteHtaAF'));?></label>
								</div>
							</td>
						</tr>
						<tr style="width: 100%;">
							<td id="BUcheckbox" style="">
								<div style="float: left;">
									<label style="width: 230px; height: 30px; text-align: right;">Autres <?php echo $this->formRow($form->get('autresAF'));?></label>
								</div>
								<div style="float: left" id="DivNoteAutresAF">
									<label style="width: 260px; height: 30px; text-align: right;">Note <?php echo $this->formRow($form->get('NoteAutresAF'));?></label>
								</div>
							</td>
						</tr>


						<tr style="width: 100%;">
							<td class='block' id='thoughtbot'
								style='display: inline-block; vertical-align: bottom; width: 100%; padding-bottom: 5px; padding-top: 15px;'><div
									style="float: left;" id="TerminerAntecedentsFamiliaux">Terminer</div></td>
						
						
						<tr>
					
					</table>
					<script>
               var temoinDiabeteAF = <?php echo $this->donneesAntecedentsFamiliaux['DiabeteAF'];?>;
               var temoinDrepanocytoseAF = <?php echo $this->donneesAntecedentsFamiliaux['DrepanocytoseAF'];?>;
               var temoinhtaAF = <?php echo $this->donneesAntecedentsFamiliaux['htaAF'];?>;
           </script>

					<!--****** ================== FIN ANTECEDENTS TERRAIN PARTICULIER ================== ****** -->
					<!--****** ================== FIN ANTECEDENTS TERRAIN PARTICULIER ================== ****** -->
					<!--****** ================== FIN ANTECEDENTS TERRAIN PARTICULIER ================== ****** -->

				</div>
				
				<div id="tabss-2">
				
				</div>


				<div id="tabss-3">
					<table id="MenuAntecedent" style="width: 100%;">
						<tr style="width: 100%;">
							<td style="width: 25%;">
								<div>
									<img class="image1"
										style='cursor: pointer; width: 100%; height: 200px;'
										src='<?php echo $this->basepath().'/images_icons/Consultant_logo.jpg'?>' />
								</div>
							</td>
							<td style="width: 25%;">
								<div>
									<img class="image2"
										style='cursor: pointer; width: 100%; height: 200px;'
										src='<?php echo $this->basepath().'/images_icons/hospitalisatione.jpg'?>' />
								</div>
							</td>
							<td style="width: 25%;">
								<div>
									<img class="image3"
										style='cursor: pointer; width: 100%; height: 200px;'
										src='<?php echo $this->basepath().'/images_icons/examens.jpg'?>' />
								</div>
							</td>
							<td style="width: 25%;">
								<div>
									<img class="image4"
										style='cursor: pointer; width: 100%; height: 200px;'
										src='<?php echo $this->basepath().'/images_icons/Autres.jpg'?>' />
								</div>
							</td>
						</tr>
					</table>

					<!-- LISTE DES CONSULTATIONS DU PATIENT -->
					<!-- LISTE DES CONSULTATIONS DU PATIENT -->
					<!-- LISTE DES CONSULTATIONS DU PATIENT -->

					<div id="titreTableauConsultation"
						style="width: 100%; font-family: Times New Roman; color: green; font-size: 17px; font-weight: bold; padding-bottom: 5px;">
						<iS style='font-size: 25px;'>&curren;</iS>
						LISTE DES CONSULTATIONS PR&Eacute;C&Eacute;DENTES
					</div>

					<div id='ListeCons'>
						<table class="table table-bordered  tab_list_mini"
							id="ListeConsultationPatient" style="width: 100%;">
							<thead>
								<tr style="height: 40px; width: 100%;">
									<th style="width: 25%;">DATE ET HEURE</th>
									<th style="width: 35%;">SURVEILLANT DE SERVICE</th>
									<th style="width: 35%;">M&Eacute;DECIN CONSULTANT</th>
									<th style="width: 5%;">Vue</th>
								</tr>
							</thead>

							<tbody>
			  <?php foreach($this->liste as $donnees) :?>
                 <tr style="width: 100%;">
									<td style="width: 25%;"> <?php echo $Control->convertDateTime($donnees['DATE']);?> </td>
									<td style="width: 35%;"> <?php echo $donnees['PrenomSurveillant'];?>  <?php echo $donnees['NomSurveillant'];?></td>
									<td style="width: 35%;"> <?php echo $donnees['PRENOM'];?>  <?php echo $donnees['NOM'];?> </td>
									<td style="width: 5%;"><a
										href="<?php echo $this->url('orl', array('action'=>'visualisation-consultation'),  array('query'=>array('id_patient'=>$this->escapeHtml($donnees['ID_PATIENT']),'id_cons'=>$this->escapeHtml($donnees['ID_CONS']))));?>"
										target="_blank"> <img style="display: inline;"
											src='<?php echo $this->basepath().'/images_icons/voird.PNG'?>'
											alt='Constantes'
											title="Voir les d&eacute;tails de la consultation" />
									</a>&nbsp;</td>
								</tr>
              <?php endforeach; ?>
              </tbody>
						</table>
					</div>

					<table id="boutonTerminerConsultation" style="width: 100%;">
						<tr style="width: 100%;">
							<td class='block' id='thoughtbot'
								style='display: inline-block; vertical-align: bottom; width: 100%; padding-bottom: 5px;'><div
									style="float: left;" id="TerminerConsultation">Terminer</div></td>
						
						
						<tr>
					
					</table>
					<!-- FIN LISTE DES CONSULTATIONS DU PATIENT -->
					<!-- FIN LISTE DES CONSULTATIONS DU PATIENT -->
					<!-- FIN LISTE DES CONSULTATIONS DU PATIENT -->


					<!-- LISTE DES HOSPITALISATIONS DU PATIENT -->
					<!-- LISTE DES HOSPITALISATIONS DU PATIENT -->
					<!-- LISTE DES HOSPITALISATIONS DU PATIENT -->

					<div id="titreTableauHospitalisation"
						style="width: 100%; font-family: Times New Roman; color: green; font-size: 17px; font-weight: bold; padding-bottom: 5px;">
						<iS style='font-size: 25px;'>&curren;</iS>
						LISTE DES HOSPITALISATIONS PR&Eacute;C&Eacute;DENTES
					</div>
					<!-- b style="font-family: Felix Titling; font-size: 25px;"> PAS ENCORE FAIT </b> ... <i style="font-family: Times New Roman; font-size: 20; color: red;"> C'est pour bient&ocirc;t!  </i-->

					<div id='ListeHospi'>
						<table class="table table-bordered  tab_list_mini"
							id="ListeHospitalisation" style="width: 100%;">
							<thead>
								<tr style="height: 40px; width: 100%;">
									<th style="width: 25%;">DATE & HEURE</th>
									<th style="width: 35%;">PR&Eacute;NOM & NOM M&eacute;decin</th>
									<th style="width: 35%;">DATE & HEURE de Sortie</th>
									<th style="width: 5%;">Vue</th>
								</tr>
							</thead>
							<tbody>	
			  <?php foreach($this->listeHospitalisation as $donnees) :?>
                 <tr style="width: 100%;">
									<td style="width: 25%;"> <?php echo $Control->convertDateTime($donnees['date_debut']);?> </td>
									<td style="width: 35%;"> <?php echo $donnees['PrenomMedecin'];?>  <?php echo $donnees['NomMedecin'];?></td>
									<td style="width: 35%;"> <?php echo $Control->convertDateTime($donnees['date_fin']);?>  </td>
									<td style="width: 5%;"><a
										href="<?php echo $this->url('orl', array('action'=>'visualisation-consultation'),  array('query'=>array('id_patient'=>$this->escapeHtml($donnees['id']),'id_cons'=>$this->escapeHtml($donnees['id_cons']), 'id_demande_hospi'=>$this->escapeHtml($donnees['id_demande_hospi']))));?>"
										target="_blank"> <img style="display: inline;"
											src='<?php echo $this->basepath().'/images_icons/voird.PNG'?>'
											alt='Constantes'
											title="Voir les d&eacute;tails sur l'hospitalisation" />
									</a>&nbsp;</td>
								</tr>
              <?php endforeach; ?>
              </tbody>
						</table>
					</div>

					<table id="boutonTerminerHospitalisation" style="width: 100%;">
						<tr style="width: 100%;">
							<td class='block' id='thoughtbot2'
								style='display: inline-block; vertical-align: bottom; width: 100%; padding-bottom: 5px;'><div
									style="float: left;" id="TerminerHospitalisation">Terminer</div></td>
						
						
						<tr>
					
					</table>
					<!-- FIN LISTE DES HOSPITALISATIONS DU PATIENT -->
					<!-- FIN LISTE DES HOSPITALISATIONS DU PATIENT -->
					<!-- FIN LISTE DES HOSPITALISATIONS DU PATIENT -->

				</div>

			</div>
		</div>
		
		
		
											

						
						
		
		
		
		<!-- ************** Accordeon NOUVELLES CONSTANTES ******************-->
		<!-- ************** Accordeon NOUVELLES CONSTANTES ******************-->
		<!-- ************** Accordeon NOUVELLES CONSTANTES ******************-->

		<!--*2*-->
		<div id='motifsAdmissionConstanteClick'
			style='font-family: police2; font-size: 17px; font-weight: bold;'>
			Motif de consultation</div>
		<div style='max-height: 460px;'>

           <?php echo $this->formHidden($form->get('id_patient'));?>
           <?php echo $this->formHidden($form->get('id_medecin'));?>
           <?php echo $this->formHidden($form->get('id_cons'));?>

          <!--**************************************************************************************** -->
			<!-- SOUS ACCORDEON MOTIF D'ADMISSION ET CONSTANTES -->
			<div id="accordionss">
				<!--**************** sous accordeon LES MOTIFS D ADMISSIONS ************************-->
				<!--**************** sous accordeon LES MOTIFS D ADMISSIONS ************************-->
				<!-- **1** -->
				<div
					style='font-family: police2; font-size: 17px; font-weight: bold;'>
					Motifs d'admission</div>
				<div>
                    <?php echo  $this->headScript()->appendFile($this->basePath().'/js/orl/ajouterMotifs.js');?>
                    <div style='width: 100%; height: 30px;'>
						<div style='width: 70%; float: left;'>
							<table id="respondeMotif" style='width: 100%;'>
								<tr class="form-author" id="motif1">
									<th><?php echo $this->formRow($form->get('motif_admission1'));?> <span
										id="labelSupMotif"> <img class='supprimerMotif1'
											style='cursor: pointer;' src='../images/images/sup.png'
											title='supprimer' />
									</span></th>
								</tr>
								<tr class="form-author" id="motif2">
									<th><?php echo $this->formRow($form->get('motif_admission2'));?> <span
										id="labelSupMotif"> <img class='supprimerMotif2'
											style='cursor: pointer;' src='../images/images/sup.png'
											title='supprimer' />
									</span></th>
								</tr>
								<tr class="form-author" id="motif3">
									<th><?php echo $this->formRow($form->get('motif_admission3'));?> <span
										id="labelSupMotif"> <img class='supprimerMotif3'
											style='cursor: pointer;' src='../images/images/sup.png'
											title='supprimer' />
									</span></th>
								</tr>
								<tr class="form-author" id="motif4">
									<th><?php echo $this->formRow($form->get('motif_admission4'));?> <span
										id="labelSupMotif"> <img class='supprimerMotif4'
											style='cursor: pointer;' src='../images/images/sup.png'
											title='supprimer' />
									</span></th>
								</tr>
								<tr class="form-author" id="motif5">
									<th><?php echo $this->formRow($form->get('motif_admission5'));?> <span
										id="labelSupMotif"> <img class='supprimerMotif5'
											style='cursor: pointer;' src='../images/images/sup.png'
											title='supprimer' />
									</span></th>
								</tr>
							</table>


							<!--********************* BOUTON AJOUTER-SUPPRIMER ************************-->
							<!--********************* BOUTON AJOUTER-SUPPRIMER ************************-->
							<div id="controls_motifs" style="margin-top: 10px; width: 100%;">
								<div style="width: 100%;">
									<div style="width: 4.5%; height: 1px; float: left;"
										id="supprimer_donnee">
										<img id="supprimer_motif_img"
											style='margin-left: 5px; cursor: pointer;'
											src='../images_icons/moin-green.png' title='supprimer' />
									</div>
									<div style="width: 4.5%; height: 1px; float: left;"
										id="ajouter_donnee">
										<img id="ajouter_motif_img"
											style='margin-left: 5px; cursor: pointer;'
											src='../images_icons/plus-green.png' title='ajouter' />
									</div>
								</div>
							</div>

							<!--********************* BOUTON VALIDER-MODIFIER ************************-->
							<!--********************* BOUTON VALIDER-MODIFIER ************************-->
							<table style="width: 86%; position: relative; top: 0px;">
								<tr style="width: 100%;">
									<th style="width: 65%;">
										<div style="float: right;">
											<button id='bouton_motif_valider'>Valider</button>
										</div>
										<div style="float: right;">
											<button id='bouton_motif_modifier'>Modifier</button>
										</div>
									</th>
								</tr>
							</table>

							<script>
                            var nbMotif = "<?php echo $this->nbMotifs;?>";
                            cacherToutMotif();
                            if(nbMotif == 0){ nbMotif = 1; }
                            afficherMotif(nbMotif);
                            supprimerUnMotif();
                         </script>

						</div>

						<div style='width: 27%; float: left;'>
							<p style='color: white; opacity: 0.5;'>
								<img id="faces"
									src='<?php echo $this->basePath().'/images_icons/consult-motif.jpg'?>'
									alt="consult-motif"
									style='margin-right: 5px; width: 100%; height: 315px;' />
							</p>
						</div>
					</div>

				</div>
			</div>


			<script>
                if(<?php echo $this->temoin;?> != 1){ 
            			 $('#BUcheckbox').toggle(false);
             			 dep();
        			  }else {
        				  $("#depliantBandelette").replaceWith("<img id='depliantBandelette' style='cursor: pointer; position: absolute; padding-right: 120px; margin-left: -5px;' src='../img/light/minus.png' />");
        				    dep1();
        				 }

             /****** MASK DE SAISIE ********/
          	 maskSaisie();
            </script>
			<!-- ************************************************************************************* -->

		</div>		

	<!-- ************************  SOUS-DOSSIERS *******************************************-->

				<!-- ******************** SOUS-DOSSIERS ******************-->
				<!-- ******************** SOUS-DOSSIERS ******************-->
				<!-- ******************** SOUS-DOSSIERS ******************-->
		

		<div style='font-family: police2; font-size: 17px; font-weight: bold;'>Histoire de la maladie</div>
		<div style='max-height: 540px;'>

			<div id="tabs">
				<ul>
					<li><a href="#tabs-Fiche-observation-clinique">Fiche d'observation clinique</a></li>
					<li><a href="#tabs-thyroide">thyroide</a></li>
					<li><a href="#tabs-tumeur-parotidienne">tumeur parotidienne</a></li>
					<li><a href="#tabs-corps-etrangers">corps etrangers</a></li>
					<li><a href="#tabs-lesions-sphere-ORL">lesions sphere ORL</a></li>
				</ul>


				<div id="tabs-Fiche-observation-clinique">
					<div style='height: 475px;'>
					 <table id="hospitalisation" style="width: 63%;">
                                        <tr>
                                            <th class="form-hospitalisation" style="width: 60%;"> <?php echo $this->formRow($form->get('examen_clinique'));?> </th>
                                        </tr>
                                    </table>
						
                          <?php echo  $this->headScript()->appendFile($this->basePath().'/js/orl/ajouterDonnees.js');?>
                          <table id="responde" style="width: 65%;">
							<tr id="donnee1" class="form-author">
								<th><?php echo $this->formRow($form->get('examen_donnee1'));?> <span
									id="labelSupDonnee"> <img class='supprimerDonnee1'
										style='cursor: pointer;' src='../images/images/sup.png'
										title='supprimer' />
								</span></th>
							</tr>
							<tr id="donnee2" class="form-author">
								<th><?php echo $this->formRow($form->get('examen_donnee2'));?> <span
									id="labelSupDonnee"> <img class='supprimerDonnee2'
										style='cursor: pointer;' src='../images/images/sup.png'
										title='supprimer' />
								</span></th>
							</tr>
							<tr id="donnee3" class="form-author">
								<th><?php echo $this->formRow($form->get('examen_donnee3'));?> <span
									id="labelSupDonnee"> <img class='supprimerDonnee3'
										style='cursor: pointer;' src='../images/images/sup.png'
										title='supprimer' />
								</span></th>
							</tr>
							<tr id="donnee4" class="form-author">
								<th><?php echo $this->formRow($form->get('examen_donnee4'));?> <span
									id="labelSupDonnee"> <img class='supprimerDonnee4'
										style='cursor: pointer;' src='../images/images/sup.png'
										title='supprimer' />
								</span></th>
							</tr>
							<tr id="donnee5" class="form-author">
								<th><?php echo $this->formRow($form->get('examen_donnee5'));?> <span
									id="labelSupDonnee"> <img class='supprimerDonnee5'
										style='cursor: pointer;' src='../images/images/sup.png'
										title='supprimer' />
								</span></th>
							</tr>
						</table>
						<!--********************* BOUTON AJOUTER-SUPPRIMER ************************-->
         <!--********************* BOUTON AJOUTER-SUPPRIMER ************************-->
		 <div id="controls_donnees" style="margin-top: 10px; width: 100%;">
		    <div style="width: 100%; ">
		      <div style="width: 3%; height: 1px; float: left; " id="supprimer_donnee">
			     <img id="supprimer_donnee_img" style='margin-left: 5px; cursor: pointer;' src='../images_icons/moin-green.png' title='supprimer' />
			  </div>
			  <div style="width: 3%; height: 1px; float: left; " id="ajouter_donnee">
				 <img id="ajouter_donnee_img" style='margin-left: 5px; cursor: pointer;' src='../images_icons/plus-green.png' title='ajouter' />
			  </div>
		    </div>
		 </div>
		 <!--********************* BOUTON VALIDER-MODIFIER ************************-->
         <!--********************* BOUTON VALIDER-MODIFIER ************************-->		            
         <table style="width: 59%; position: relative; top: 0px;">
              <tr style="width: 90%;">
                <th style="width:65%;">
                    <div style="float:right;">
                       <button id='bouton_donnee_valider'>Valider</button>
                    </div>
                    <div style="float:right;">
                       <button id='bouton_donnee_modifier'>Modifier</button>
                    </div>
                </th>
              </tr>
         </table>
         <script>
         var nbexamendonnee = 1;
          cacherTouteDonnee();
          afficher(nbexamendonnee);
          supprimerUneDonnee();
         </script>
		 

					</div>

				</div>
				
				
	<div id="tabs-thyroide" >
							<!------------------ ANTECEDENTS ----------------------------------------------->
							<span class='titre_info_tyroide' id='titre_info_antecedent'
								style='margin-left: -5px; cursor: pointer;'> <img
								src='../img/light/plus.png' /> ANTECEDENTS
							</span>
							<div class='barre_tyroide'></div>
							<div class='infos_tyroide' id='infos_tyroide_contenu_antecedent'>
								<table id="AntecedentMedicaux" style="width: 100%;">
									<tr style="width: 50%; height: 50px;">
										<td id="BUcheckbox" style="width: 45%;"><label
											id="irradiation"
											style="width: 90%; height: 30px; text-align: right; font-family: time new romans; font-size: 18px;">
												<span style='margin-right: 10px;'> <span
													style='margin-right: 10px;'> </span> Irradiation cervicale
													anterieure
											</span>
                                    <?php echo $this->formRow($form->get('irradiation_cervical_anterieur'));?>
                                 </label></td>
										<td id="BUcheckbox" style="width: 55%;"><label id="goitre"
											style="width: 95%; height: 30px; text-align: right; font-family: time new romans; font-size: 18px;">
												<span style="margin-right: 5px;"><span
													style="margin-right: 5px;"></span>  
                                        Goitre Familiale ou ATCD de tyreopatie familiale 
                                        <?php echo $this->formRow($form->get('goitre_atcd'));?>
                                    </span>
										</label></td>
									</tr>
									<tr id="labelDesAntecedentsMedicaux_1" style="width: 100%;">
										<!-- Emplacement des autres antecedents médicaux ajouter à partir du champ autre -->
									</tr>
									<tr style="width: 100%;">
										<td id="BUcheckbox" colspan="3" style="width: 60%;">
											<div id="imageIconeAjouterLabel">
                                  <?php echo $this->formRow($form->get('nbCheckboxAM'));?>
                                  <label
													style="width: 55%; height: 30px; text-align: right;">
                                    Autres  <?php echo $this->formRow($form->get('autresAntecedent'));?>
                                    <img id="imgIconeAjouterLabel"
													style='cursor: pointer; padding-right: 5px; padding-left: 10px; padding-bottom: 6px;'
													src='<?php echo $this->basepath().'/images_icons/Add14X14.png'?>' />
												</label>
											</div>
										</td>
										<td></td>
										<td></td>
										<td></td>
										<td></td>
									</tr>
									<tr style="width: 100%;">
										<td></td>
										<td></td>
										<td></td>
										<td></td>
									
									
									<tr>
								
								</table>
					</div>
							<div style='height: 20px; width: 100px;'> <!-- ESPACEMENT --> </div>
							
							
							
							<!------------------- MOTIFS DHOSPITALISATION ---------------------------->

							<span class='titre_info_tyroide' id='titre_info_motifs'
								style='margin-left: -5px; cursor: pointer;'> <img
								src='../img/light/plus.png' /> MOTIFS DE CONSULTATION
							</span>
							<div class='barre_tyroide'></div>
							<div class='infos_tyroide' id='infos_tyroide_contenu_motifs'>
							
							
							<table id="AntecedentMedicaux" style="width: 100%; height: 220px; margin-top: 15px;">
							   <tr style="width: 100%; height: 150px;">
							      <td style="width: 50%; height: 100px; vertical-align: top; ">
							          
							          <div id="BUcheckbox" style="width: 95%;"><label
											id="tumefaction"
											style="width: 90%; height: 30px; text-align: right; font-family: time new romans; font-size: 18px;">
												<span style="margin-right: 10px;"><span
													style="margin-right: 10px;"></span> Tum&eacute;faction
													cervicale ant&eacute;rieure </span>
                                            <?php echo $this->formRow($form->get('tumefaction_cervical_anterieur'));?>
                                            </label>
                                       </div>
                                       
                                       <div id="BUcheckbox" style="width: 95%;"><label
											id="signeCompression"
											style="width: 90%; height: 30px; text-align: right; font-family: time new romans; font-size: 18px;">
												<span style="margin-right: 10px;"><span
													style="margin-right: 10px;"></span>Signes compression </span>
                                            <?php echo $this->formRow($form->get('signe_compression'));?>
                                            </label>
									   </div>
                                       
                                       <div id="BUcheckbox" style="width: 95%;"><label
											id="signesThyroxicose"
											style="width: 90%; height: 30px; text-align: right; font-family: time new romans; font-size: 18px;">
												<span style="margin-right: 10px;"><span
													style="margin-right: 10px;"></span> Signes de thyrotoxicose
											</span>
                                            <?php echo $this->formRow($form->get('signes_thyroxicose'));?>
                                            </label>
                                       </div>

							      
							      </td>
							      
							      <td  style="width: 50%; height: 100px;vertical-align: top;">
							      		
										<div id="BUcheckbox" class= "signeCompression"  style="width: 95%;"><label id="dysphagie"
											style="width: 80%; height: 30px; text-align: right; font-family: time new romans; font-size: 18px;">
												<span style="margin-right: 10px;"><span
													style="margin-right: 10px;"></span> Dysphagie </span>
                                            <?php echo $this->formRow($form->get('groupeIa'));?>
                                            </label>
                                        </div>
                                 	    <div id="BUcheckbox" class= "signeCompression" style="width: 95%;"><label id="dysfonie"
											style="width: 80%; height: 30px; text-align: right; font-family: time new romans; font-size: 18px;">
												<span style="margin-right: 10px;"><span
													style="margin-right: 10px;"></span> Dysphonie </span>
                                            <?php echo $this->formRow($form->get('groupeIb'));?>
                                            </label>
                                        </div>
                                        <div id="BUcheckbox" class= "signeCompression" style="width: 95%;"><label id="dyspnee"
											style="width: 80%; height: 30px; text-align: right; font-family: time new romans; font-size: 18px;">
												<span style="margin-right: 10px;"><span
													style="margin-right: 10px;"></span> Dyspn&eacute;e </span>
                                            <?php echo $this->formRow($form->get('groupeIc'));?>
                                            </label>
                                        </div>
							      
							       
							      </td>
							   </tr>
							   
									<tr style="width: 100%;">
									    <td id="BUcheckbox" style="width: 50%;">
										   <div id="imageIconeAjouterLabel" style="width: 95%;">
                                             <?php echo $this->formRow($form->get('nbCheckboxAM'));?>
                                             <label
											 style="width: 90%; height: 30px; text-align: right;">
                                             Autres  <?php echo $this->formRow($form->get('autresMotifHospitalisation'));?>
                                             <img id="imgIconeAjouterLabel"
													style='cursor: pointer; padding-right: 5px; padding-left: 10px; padding-bottom: 6px;'
													src='<?php echo $this->basepath().'/images_icons/Add14X14.png'?>' />
												</label>
										   </div>
										</td>
										
										<td style="width: 50%;">
										</td>
										
									</tr>
									
							</table>
							
							</div>
							
							<div style='height: 20px; width: 100px;'>
								<!-- ESPACEMENT -->
							</div>
							
					<!------------------- HISTOIRE DE LA MALADIE-------------------------------->
					
							<span class='titre_info_tyroide' id='titre_info_histoireMaladie'
								style='margin-left: -5px; cursor: pointer;'> <img
								src='../img/light/plus.png' /> HISTOIRE DE LA MALADIE
							</span>
							<div class='barre_tyroide'></div>
							<div class='infos_tyroide' id='infos_tyroide_contenu_histoireMaladie'>
								<table id="transfert" style="width: 100%;">
									<tr class="form-transfert" style="width: 100%;">
										<th style="width: 45%;"><?php echo $this->formRow($form->get('histoire_maladie'));?></th>
									</tr>
								</table>
							</div>
							<div style='height: 20px; width: 100px;'> <!-- ESPACEMENT --> </div>
							
										<!------------------- PEAU CERVICO-FACIALE ------------------------------>
							<span class='titre_info_tyroide' id='titre_info_peau'
								style='margin-left: -5px; cursor: pointer;'> <img
								src='../img/light/plus.png' /> PEAU CERVICO FACIALE
							</span>
							<div class='barre_tyroide'></div>
							<div class='infos_tyroide' id='infos_tyroide_contenu_peau'>
								<table id="AntecedentMedicaux" style="width: 100%;">
									<tr style="width: 50%; height: 50px;">
										<td id="BUcheckbox" style="width: 50%;"><label
											id="depigmentation"
											style="width: 80%; height: 30px; text-align: right; font-family: time new romans; font-size: 18px;">
												<span style="margin-right: 10px;"><span
													style="margin-right: 10px;"></span>D&eacute;pigmentation
													artificielle </span>
                                  <?php echo $this->formRow($form->get('depigmentation_artificielle'));?>
                                </label></td>
										<td id="BUcheckbox" style="width: 50%;"><label id="cicatrices"
											style="width: 80%; height: 30px; text-align: right; font-family: time new romans; font-size: 18px;">
												<span style="margin-right: 10px;"><span
													style="margin-right: 10px;"></span>Cicatrices-Fistules-Taches
											</span>
                                  <?php echo $this->formRow($form->get('cicatrices_taches_fistules'));?>
                                </label></td>
									</tr>
									<tr style="width: 100%;">
										<td></td>
										<td></td>
										<td></td>
										<td></td>
									
									
									<tr>
									
									
									<tr id="labelDesAntecedentsMedicaux_1" style="width: 100%;">
										<!-- Emplacement des autres antecedents médicaux ajouter à partir du champ autre -->
									</tr>
									<tr style="width: 100%;">
										<td id="BUcheckbox" colspan="3" style="width: 60%;">
											<div id="imageIconeAjouterLabel">
                                  <?php echo $this->formRow($form->get('nbCheckboxAM'));?>
                                  <label
													style="width: 55%; height: 30px; text-align: right;">
                                    Autres  <?php echo $this->formRow($form->get('autresMotifHospitalisation'));?>
                                    <img id="imgIconeAjouterLabel"
													style='cursor: pointer; padding-right: 5px; padding-left: 10px; padding-bottom: 6px;'
													src='<?php echo $this->basepath().'/images_icons/Add14X14.png'?>' />
												</label>
											</div>
										</td>
										<td></td>
										<td></td>
										<td></td>
										<td></td>
									</tr>
									<tr style="width: 100%;">
										<td></td>
										<td></td>
										<td></td>
										<td></td>
									</tr>

								</table>
							</div>
							<div style='height: 20px; width: 100px;'>
								<!-- ESPACEMENT -->
							</div>
							
										<!------------------- TYROIDE ------------------------------>
							<span class='titre_info_tyroide' id='titre_info_soustyroide'
								style='margin-left: -5px; cursor: pointer;'> <img
								src='../img/light/plus.png' /> GLANDE THYROIDE
							</span>
							<div class='barre_tyroide'></div>
							<div class='infos_tyroide' id='infos_tyroide_contenu_soustyroide'>
								<p style="font-family: time new romans; font-size: 18px;">Hypertrophie:</p>
								<table id="HabitudesDeVie" style="width: 100%;">
									<tr style="width: 50%; height: 50px;">
										<td id="BUcheckbox" style="width: 50%;"><label id="globale"
											style="width: 80%; height: 30px; text-align: right; font-family: time new romans; font-size: 18px;">
												<span style="margin-right: 10px;"><span
													style="margin-right: 10px;"></span>Globale </span>
                                  <?php echo $this->formRow($form->get('hypertrophie_globale'));?>
                                </label></td>
										<td id="BUcheckbox" style="width: 50%;"><label id="localise"
											style="width: 80%; height: 30px; text-align: right; font-family: time new romans; font-size: 18px;">
												<span style="margin-right: 10px;"><span
													style="margin-right: 10px;"></span>Localis&eacute;e </span>
                                  <?php echo $this->formRow($form->get('hypertrophie_localise'));?>
                                </label></td>
									</tr>
									<tr>
										<td id="BUcheckbox" style="width: 50%;"><label id="nodulaire"
											style="width: 80%; height: 30px; text-align: right; font-family: time new romans; font-size: 18px;">
												<span style="margin-right: 10px;"><span
													style="margin-right: 10px;"></span>Nodulaire </span>
                                  <?php echo $this->formRow($form->get('hypertrophie_nodulaire'));?>
                                </label></td>
										<td id="BUcheckbox" style="width: 50%;"><label
											id="sensibilite"
											style="width: 80%; height: 30px; text-align: right; font-family: time new romans; font-size: 18px;">
												<span style="margin-right: 10px;"><span
													style="margin-right: 10px;"></span>Sensibilit&eacute; </span>
                                  <?php echo $this->formRow($form->get('hypertrophie_sensibilite'));?>
                                </label></td>
									</tr>
									<tr>
										<td id="BUcheckbox" style="width: 50%;"><label
											id="consistance"
											style="width: 80%; height: 30px; text-align: right; font-family: time new romans; font-size: 18px;">
												<span style="margin-right: 10px;"><span
													style="margin-right: 10px;"></span>Consistance </span>
                                  <?php echo $this->formRow($form->get('consistance'));?>
                                </label></td>
										<td id="BUcheckbox" style="width: 50%;"><label id="mobilite"
											style="width: 80%; height: 30px; text-align: right; font-family: time new romans; font-size: 18px;">
												<span style="margin-right: 10px;"><span
													style="margin-right: 10px;"></span>Mobilit&eacute;
													transversale </span>
                                  <?php echo $this->formRow($form->get('mobilite_transversale'));?>
                                </label></td>
									</tr>
									<tr class="form-transfert" style="width: 100%;">
										<th style="width: 45%;"><?php echo $this->formRow($form->get('taille_tyroide'));?></th>
									</tr>
								</table>
							</div>
							<div style='height: 20px; width: 100px;'>
								<!-- ESPACEMENT -->
							</div>
	
							<!------------------ GROUPES GANGLIONNAIRES-------------------------------->
							<span class='titre_info_tyroide' id='titre_info_ganglions'
								style='margin-left: -5px; cursor: pointer;'> <img
								src='../img/light/plus.png' /> AIRES GANGLIONNAIRES
							</span>
							<div class='barre_tyroide'></div>
							<div class='infos_tyroide' id='infos_tyroide_contenu_ganglions'>
					<table style="width: 100%;">
						<tr style="width:100%; " >
						    <td style="width:40%; height: 100px; vertical-align: top;">
							    <div id="BUcheckbox" style="width: 95%; ">
                                     <label id="labelLibre" style="width: 80%; height:30px; text-align:right; font-family: time new romans; font-size: 18px;">
                                        <span style="margin-right: 10px;"><span style="margin-right: 10px;"></span>libre
                                        </span>
                                      <?php echo $this->formRow($form->get('libre'));?>
                                    </label> 
                                  </div>
                                  <div id="BUcheckbox" style="width: 95%; ">
                                     <label id="labelAtteinte" style="width: 80%; height:30px; text-align:right; font-family: time new romans; font-size: 18px;">
                                          <span style="margin-right: 10px;"><span style="margin-right: 10px;"></span>atteinte
                                          </span>
                                      <?php echo $this->formRow($form->get('atteinte'));?>
                                    </label> 
                                  </div>
						
							</td>
							<td style="width:60%; height: 100px;vertical-align: top;">
							<div id="BUcheckbox" class="labelAtteinte" style="width: 100%;">
												<label id= "SousMentoMaxillaire"
													style="width: 95%; height: 30px; text-align: left; font-family: time new romans; font-size: 18px;">
													<span> <img class="imageValiderHtaAM"
														style='cursor: pointer; padding-right: 10px;'
														src='<?php echo $this->basepath().'/images_icons/tick-icon2.png'?>' />
												</span> 
                                    Groupe sous mento-maxillaire
                                    <?php echo $this->formRow($form->get('groupeI'));?>
                                 </label>
							</div>
							<div id="BUcheckbox" class="labelAtteinte"  style="width: 95%;">
												<label id= "JuguloCarotidien"
													style="width: 100%; height: 30px; text-align: left; font-family: time new romans; font-size: 18px;">
													<span> <img class="imageValiderHtaAM"
														style='cursor: pointer; padding-right: 10px;'
														src='<?php echo $this->basepath().'/images_icons/tick-icon2.png'?>' />
												</span> 
                                     Groupe jugulo-carotidien sup&eacute;rieur(groupe sous digastrique) 
                                    <?php echo $this->formRow($form->get('groupeIIa'));?>
                                 </label>
							</div>
							<div id="BUcheckbox" class="labelAtteinte" style="width: 95%;">
											
												<label
													style="width: 100%; height: 30px; text-align: left; font-family: time new romans; font-size: 18px;">
													<span> <img class="imageValiderHtaAM"
														style='cursor: pointer; padding-right: 10px;'
														src='<?php echo $this->basepath().'/images_icons/tick-icon2.png'?>' />
												</span> 
                                    Groupe r&eacute;tro-spinal haut
                                    <?php echo $this->formRow($form->get('groupeIIb'));?>
                                 </label>
							</div>
						    <div id="BUcheckbox" class="labelAtteinte" style="width: 95%;">	
										<label
										    style="width: 100%; height: 30px; text-align: left; font-family: time new romans; font-size: 18px;">
										       <span> <img class="imageValiderHtaAM"
														style='cursor: pointer; padding-right: 10px;'
														src='<?php echo $this->basepath().'/images_icons/tick-icon2.png'?>' />
												</span> 
                                     Groupe jugulo-carotidien moyen
                                    <?php echo $this->formRow($form->get('groupeIII'));?>
                                 </label>
							</div>
							<div id="BUcheckbox" class="labelAtteinte" style="width: 95%;">
											
												<label
													style="width: 100%; height: 30px; text-align: left; font-family: time new romans; font-size: 18px;">
													<span> <img class="imageValiderHtaAM"
														style='cursor: pointer; padding-right: 10px;'
														src='<?php echo $this->basepath().'/images_icons/tick-icon2.png'?>' />
												    </span> 
                                    Groupe jugulo-carotidien inf&eacute;rieur
                                    <?php echo $this->formRow($form->get('groupeIV'));?>
                                                 </label>		
							</div>
							<div id="BUcheckbox" class="labelAtteinte" style="width: 95%;">
											
												<label
													style="width: 100%; height: 30px; text-align: left; font-family: time new romans; font-size: 18px;" title="Groupe post&eacute;ro-inf&eacute;rieur + groupes spinaux, moyen et inf&eacute;rieur + partie post&eacute;rieure du groupe cervical transverse">
													<span> <img class="imageValiderHtaAM"
														style='cursor: pointer; padding-right: 10px;'
														src='<?php echo $this->basepath().'/images_icons/tick-icon2.png'?>' />
												    </span> 
                                     Groupe post&eacute;ro-inf&eacute;rieur + groupes spinaux, moyen et inf&eacute;rieur ...
                                      
                                    <?php echo $this->formRow($form->get('groupeV'));?>
                                                 </label>		
							</div>
								
								<div id="BUcheckbox" class="labelAtteinte" style="width: 95%;">
											
										<label
													style="width: 100%; height: 30px; text-align: left; font-family: time new romans; font-size: 18px;">
													<span> <img class="imageValiderHtaAM"
														style='cursor: pointer; padding-right: 10px;'
														src='<?php echo $this->basepath().'/images_icons/tick-icon2.png'?>' />
												   </span> 
                                    Groupe ant&eacute;rieur(axe visc&eacute;ral m&eacute;dian)
                                    <?php echo $this->formRow($form->get('groupeVI'));?>
                                         </label>
							  </div>
							</td>
							</tr>
					</table>	
									
							</div>
							<div style='height: 20px; width: 100px;'>
								<!-- ESPACEMENT -->
							</div>
							
								<!------------------- EXAMENS COMPLEMENTAIRES ------------------------------>
							<span class='titre_info_tyroide'
								id='titre_info_examComplementair'
								style='margin-left: -5px; cursor: pointer;'> <img
								src='../img/light/plus.png' /> LES EXAMENS COMPLEMENTAIRES
							</span>
							<div class='barre_tyroide'></div>
							<div class='infos_tyroide' id='infos_tyroide_contenu_examComplementair'>
							<table id="transfert" style="width: 100%;">
									<tr class="form-transfert" style="width: 100%;">
										<th style="width: 45%;"><?php echo $this->formRow($form->get('examen_complementaire'));?></th>
									</tr>
								</table>
								
							</div>
							<div style='height: 20px; width: 100px;'> <!-- ESPACEMENT --> </div>
			


							<!------------------- HORMONES TYROIDIENNES ---------------------------->
							<span class='titre_info_tyroide' id='titre_info_hormones'
								style='margin-left: -5px; cursor: pointer;'> <img
								src='../img/light/plus.png' /> LES HORMONES TYROIDIENNES
							</span>
							<div class='barre_tyroide'></div>
							<div class='infos_tyroide' id='infos_tyroide_contenu_hormones'>
								<table id="respond" style="width: 100%; margin-bottom: 30px;">
									<tr class="comment-form-author" style="width: 100%;">
										<td style="width: 33%;"><?php echo $this->formRow($form->get('t4'));?></td>
										<td style="width: 33%;"><?php echo $this->formRow($form->get('tsh'));?></td>
									</tr>
									<tr class="comment-form-author" style="width: 100%;">
			                         <td id="BUcheckbox" style="width: 33%;">
											<div>
												<label
													style="width: 60%; height: 30px; text-align: left; font-family: time new romans; font-size: 18px;">
													<span> <img class="imageValiderHtaAM"
														style='cursor: pointer; padding-right: 10px;'
														src='<?php echo $this->basepath().'/images_icons/tick-icon2.png'?>' />
												    </span> 
                                    hyperthyroide
                                    <?php echo $this->formRow($form->get('groupeIIIa'));?>
                                               </label>
											</div>
										</td>
										<td id="BUcheckbox" style="width: 33%;">
											<div>
												<label
													style="width: 60%; height: 30px; text-align: left; font-family: time new romans; font-size: 18px;">
													<span> <img class="imageValiderHtaAM"
														style='cursor: pointer; padding-right: 10px;'
														src='<?php echo $this->basepath().'/images_icons/tick-icon2.png'?>' />
												    </span> 
                                    euthyroide
                                    <?php echo $this->formRow($form->get('groupeIIIb'));?>
                                               </label>
											</div>
										</td>
										<td id="BUcheckbox" style="width: 33%;">
											<div>
												<label
													style="width: 60%; height: 30px; text-align: left; font-family: time new romans; font-size: 18px;">
													<span> <img class="imageValiderHtaAM"
														style='cursor: pointer; padding-right: 10px;'
														src='<?php echo $this->basepath().'/images_icons/tick-icon2.png'?>' />
												    </span> 
                                    hypothyroide
                                    <?php echo $this->formRow($form->get('groupeIIIc'));?>
                                               </label>
											</div>
										</td>
									</tr>
								</table>
								<table id="ajustementChampsTextarea" style="width: 100%;">
									<tr class="form-transfert">
										<td style="width: 33%;"><?php echo $this->formRow($form->get('cytologie'));?></td>
										<td style="width: 33%;"><?php echo $this->formRow($form->get('echographie_cervicale'));?></td>
										<td style="width: 33%;"><?php echo $this->formRow($form->get('autres'));?></td>

									</tr>
								</table>
							</div>
							<div style='height: 20px; width: 100px;'><!-- ESPACEMENT --> </div>
							
							<!------------------- INFORMATIONS OPERATOIRES ---------------------------->
							<span class='titre_info_tyroide' id='titre_info_operation'
								style='margin-left: -5px; cursor: pointer;'> <img
								src='../img/light/plus.png' /> COMPTE RENDU OPERATOIRE
							</span>
							<div class='barre_tyroide'></div>
							<div class='infos_tyroide' id='infos_tyroide_contenu_operation'>
									<div id="tabsCompteRendu">
										<ul>
											<li><a href="#tabs-indications">Indications</a></li>
											<li><a href="#tabs-incidents">Incidents...</a></li>
											<li><a href="#tabs-compteRendu">Compte rendu...</a></li>
										</ul>
										
							 <div id="tabs-indications">
                                  <table  id="ajustementChampsTextarea" style="width: 100%; margin-bottom: 80px;">
                                    <tr class="comment-form-author textareaIndication" style="width: 100%;">
                                        <td style="width: 50%;" ><?php echo $this->formRow($form->get('indication_preoperatoire'));?></td>
                                        <td style="width: 50%;"><?php echo $this->formRow($form->get('indication_peroperatoire'));?></td>
                                    </tr>
                                  </table>
                              </div>
                               <div id="tabs-incidents">
                                <p style="font-family: time new romans; font-size: 18px;">Incidents et Accidents PER-OPERATOIRES</p>
                                
                                <table style="width:100%;" >
                                  <tr style="width:100%; " >
                                    <td style="width:50%; height: 100px;" >
                                       <div id="BUcheckbox" style="width: 95%; ">
                                          <label id="incidentAnesthesique" style="width: 80%; height:30px; text-align:right; font-family: time new romans; font-size: 18px;">
                                             <span style="margin-right: 10px;"><span style="margin-right: 10px;"></span>Anesth&eacute;siques
                                             </span>
                                               <?php echo $this->formRow($form->get('incident_anesthesique'));?>
                                          </label> 
                                       </div>
                                  <div id="BUcheckbox" style="width: 95%; ">
                                     <label id="incidentChirurgicaux" style="width: 80%; height:30px; text-align:right; font-family: time new romans; font-size: 18px;">
                                      <span style="margin-right: 10px;"><span style="margin-right: 10px;"></span>Chirurgicaux
                                      </span>
                                      <?php echo $this->formRow($form->get('incident_chirurgicaux'));?>
                                    </label> 
                                  </div>
                                  <div id="BUcheckbox" style="width: 95%; ">
                                     <label id="incidentTracheotomie" style="width: 80%; height:30px; text-align:right; font-family: time new romans; font-size: 18px;">
                                      <span style="margin-right: 10px;"><span style="margin-right: 10px;"></span>Trach&eacute;otomie
                                      </span>
                                      <?php echo $this->formRow($form->get('incident_tracheotomie'));?>
                                    </label> 
                                  </div>
                                       <div id="BUcheckbox" style="width: 95%; ">
                                         <label id="incidentGlandulaire" style="width: 80%; height:30px; text-align:right; font-family: time new romans; font-size: 18px;">
                                         <span style="margin-right: 10px;"><span style="margin-right: 10px;"></span>Glandulaires
                                         </span>
                                         <?php echo $this->formRow($form->get('incident_glandulaire'));?>
                                         </label> 
                                      </div>
                                    </td>
                                    
                                    <td style="width:50%;">
                                  <div id="BUcheckbox" class="incidentChirurgicaux" style="width: 50%;">
                                     <label id="incidentNerveux" style="width: 80%; height:30px; text-align:right; font-family: time new romans; font-size: 18px;">
                                      <span style="margin-right: 10px;"><span style="margin-right: 10px;"></span>Nerveux
                                      </span>
                                      <?php echo $this->formRow($form->get('groupeIVa'));?>
                                    </label>
                                    </div>
                                                                      
                                    <div id="BUcheckbox" class="incidentChirurgicaux" style="width: 50%;">
                                     <label id="incidentHemoragique" style="width: 80%; height:30px; text-align:right; font-family: time new romans; font-size: 18px;">
                                      <span style="margin-right: 10px;"><span style="margin-right: 10px;"></span>H&eacute;moragiques
                                      </span>
                                      <?php echo $this->formRow($form->get('groupeIVb'));?>
                                    </label> 
                                    </div>
                                    </td>
                                  </tr>
                                </table>

                              </div>
                              <div id="tabs-compteRendu">
                                <table  id="ajustementChampsTextarea" style="width: 100%;">
                                    <tr class="comment-form-author">
                                        <td style="width: 33%;" ><?php echo $this->formRow($form->get('anesthesie'));?></td>
                                        <td style="width: 33%;"><?php echo $this->formRow($form->get('incision'));?></td>
                                        <td style="width: 33%;"><?php echo $this->formRow($form->get('exploitation'));?></td>
                                    </tr>
                                </table>
                                <table id="HabitudesDeVie" style="width:100%;">
                                  <tr style="width:50%; height: 50px; ">
                                    <td id="BUcheckbox" style="width: 50%; ">
                                       <label id="gesteNerf" style="width: 80%; height:30px; text-align:right; font-family: time new romans; font-size: 18px;">
                                        <span style="margin-right: 10px;"><span style="margin-right: 10px;"></span>Sur les nerfs
                                        </span>
                                        <?php echo $this->formRow($form->get('geste_sur_nerf'));?>
                                      </label> 
                                    </td>
                                    <td id="BUcheckbox" style="width: 50%; ">
                                       <label id="labelLoboithmectomie" style="width: 80%; height:30px; text-align:right; font-family: time new romans; font-size: 18px;">
                                        <span style="margin-right: 10px;"><span style="margin-right: 10px;"></span>Loboisthmectomie
                                        </span>
                                        <?php echo $this->formRow($form->get('loboithmectomie'));?>
                                      </label> 
                                    </td>
                                  </tr>
                                  <tr>
                                    <td id="BUcheckbox" style="width: 50%; ">
                                       <label id="labelIthmectomie" style="width: 80%; height:30px; text-align:right; font-family: time new romans; font-size: 18px;">
                                        <span style="margin-right: 10px;"><span style="margin-right: 10px;"></span>Ithmectomie
                                        </span>
                                        <?php echo $this->formRow($form->get('ithmectomie'));?>
                                      </label> 
                                    </td>
                                    <td id="BUcheckbox" style="width: 50%; ">
                                       <label id="thyroidectomieSubtotale" style="width: 80%; height:30px; text-align:right; font-family: time new romans; font-size: 18px;">
                                        <span style="margin-right: 10px;"><span style="margin-right: 10px;"></span>Thyroidectomie subtotale
                                        </span>
                                        <?php echo $this->formRow($form->get('thyroidectomie_subtotale'));?>
                                      </label> 
                                    </td>
                                  </tr>
                                  <tr>
                                    <td id="BUcheckbox" style="width: 50%; ">
                                       <label id="thyroidectomieTotal" style="width: 80%; height:30px; text-align:right; font-family: time new romans; font-size: 18px;">
                                        <span style="margin-right: 10px;"><span style="margin-right: 10px;"></span>Thyroidectomie totale
                                        </span>
                                        <?php echo $this->formRow($form->get('thyroidectomie_totale'));?>
                                      </label> 
                                    </td>
                                    <td id="BUcheckbox" style="width: 50%; ">
                                       <label id="glandeParathyroides" style="width: 80%; height:30px; text-align:right; font-family: time new romans; font-size: 18px;">
                                        <span style="margin-right: 10px;"><span style="margin-right: 10px;"></span>Sur les glandes parathyroide
                                        </span>
                                        <?php echo $this->formRow($form->get('glande_parathyroide'));?>
                                      </label> 
                                    </td>
                                  </tr>
                                   <tr id="ajustementChampsTextarea" class="comment-form-author textareaHT">
                                      <td style="width: 50%;" ><?php echo $this->formRow($form->get('description_piece'));?></td>
                                        <td style="width: 50%;"><?php echo $this->formRow($form->get('fermeture'));?></td>
                                    </tr>
                                </table>
                                
                              </div>
										
						       </div>
						    </div>
						    
						    <div style='height: 20px; width: 100px;'> <!-- ESPACEMENT --> </div>
						    <!------------------- SURVEILLANCE ------------------------------>
						<span class='titre_info_tyroide' id='titre_info_surveillance'
							style='margin-left: -5px; cursor: pointer;'> <img
							src='../img/light/plus.png' /> SURVEILLANCE
						</span>
						<div class='barre_tyroide'></div>
						<div class='infos_tyroide' id='infos_tyroide_contenu_surveillance'>
						<div id="tabsSurveillance">
						 <ul>
                                <li><a href="#tabs-periodePostop">P&eacute;riode Postop&eacute;ratoire precoce</a></li>
                                <li><a href="#tabs-histologie">Histologie</a></li>
                                <li><a href="#tabs-surveillanceTardive">P&eacute;riode Postop&eacute;ratoire tardive</a></li> 
                              </ul>
						<div id="tabs-periodePostop">
                                <p style="font-family: time new romans; font-size: 18px;">PERIODE POST-OPERATOIRES PRECOCE</p>
                                <table  id="ajustementChampsTextarea" style="width: 100%;">
                                    <tr class="comment-form-author">
                                        <td style="width: 50%;" ><?php echo $this->formRow($form->get('calcemie'));?></td>
                                        <td style="width: 50%;"><?php echo $this->formRow($form->get('laryngectomie_indirecte'));?></td>
                                    </tr>
                                    <tr class="comment-form-author">
                                        <td style="width: 50%;" ><?php echo $this->formRow($form->get('ablation_drain'));?></td>
                                        <td style="width: 50%;"><?php echo $this->formRow($form->get('ablation_fil'));?></td>
                                    </tr>
                                </table>
                                <table id="AntecedentMedicaux" style="width:100%;">
                                  <tr style="width:50%; height: 50px; ">
                                    <td id="BUcheckbox" style="width: 45%; ">
                                       <label id="accidentHemoragie" style="width: 90%; height:30px; text-align:right; font-family: time new romans; font-size: 18px;">
                                           <span style='margin-right: 10px;'> <span style='margin-right: 10px;'>  </span> Accident H&eacute;morragique </span>
                                          <?php echo $this->formRow($form->get('accident_hemoragie'));?>
                                       </label>
                                    </td>
                                    <td id="BUcheckbox" style="width: 55%; ">
                                       <label id="accidentInfectieux" style="width: 95%; height:30px; text-align:right; font-family: time new romans; font-size: 18px;">
                                          <span style="margin-right: 5px;"><span style="margin-right: 5px;"></span>  
                                              Accident Infectieux 
                                              <?php echo $this->formRow($form->get('accident_infectieux'));?>
                                          </span>
                                       </label>
                                    </td>
                                  </tr> 
                                  <tr id="labelDesAntecedentsMedicaux_1" style="width:100%;">
                                    <!-- Emplacement des autres antecedents médicaux ajouter à partir du champ autre -->
                                  </tr>
                                  <tr style="width:100%;">
                                    <td id="BUcheckbox" colspan="3" style="width:60%;" >
                                      <div id="imageIconeAjouterLabel">
                                        <?php echo $this->formRow($form->get('nbCheckboxAM'));?>
                                        <label style="width: 55%; height:30px; text-align:right;">
                                          Autres  <?php echo $this->formRow($form->get('autresAntecedent'));?>
                                          <img id="imgIconeAjouterLabel" style='cursor: pointer; padding-right: 5px; padding-left: 10px; padding-bottom: 6px;' src='<?php echo $this->basepath().'/images_icons/Add14X14.png'?>' />  
                                        </label>
                                      </div>
                                    </td>
                                    <td>  </td>
                                    <td>  </td>
                                    <td>  </td>
                                    <td>  </td>
                                  </tr>
                               </table> 
                              </div>
                               <div id="tabs-histologie">
                                <table id="transfert" style="width: 100%;">
                                    <tr class="form-transfert" style="width: 100%;">
                                        <th style="width: 45%;"><?php echo $this->formRow($form->get('histologie'));?></th>
                                    </tr>
                                </table>
                              </div>
                              <div id="tabs-surveillanceTardive">
                                 <table  id="respond" style="width: 100%; margin-bottom: 80px;">
                                    <tr class="comment-form-author" style="width: 100%;">
                                        <td style="width: 25%;" ><?php echo $this->formRow($form->get('plainte'));?></td>
                                        <td style="width: 25%;"><?php echo $this->formRow($form->get('qualite_voix_parlee'));?></td>
                                        <td style="width: 25%;"><?php echo $this->formRow($form->get('qualite_voix_chantee'));?></td>
                                        <td style="width: 25%;"><?php echo $this->formRow($form->get('qualite_cicatrice'));?></td>
                                    </tr>
                                </table>
                                <table  id="ajustementChampsTextarea" style="width: 100%;">
                                    <tr class="comment-form-author textareaHT">
                                        <td style="width: 33%;" ><?php echo $this->formRow($form->get('laryngoscopie_indirecte'));?></td>
                                        <td style="width: 33%;"><?php echo $this->formRow($form->get('palpation_cou'));?></td>
                                        <td style="width: 33%;"><?php echo $this->formRow($form->get('radiographie_pulmonaire'));?></td>
                                    </tr>
                                </table>
                              </div>
                             
                            </div>
                          </div>
                     
						<div style='height: 20px; width: 100px;'> <!-- ESPACEMENT --> </div>		
							
							
		
	</div>
				
				
				<div id="tabs-tumeur-parotidienne">
				
				</div>
				
				<div id="tabs-corps-etrangers">
				
				</div>
				
				<div id="tabs-lesions-sphere-ORL">
				
				</div>
				
			</div>
			
			</div>
			
			<!-- ********************************-Examen clinique *******************************************-->
			
			
        
    		<div style='font-family: police2; font-size: 17px; font-weight: bold;'>Examen clinique</div>
				<div style='max-height: 200px;'>

					<div id="accordionsss_exam_clinik" style=''>
						<!--******************* DEMANDE ************************-->
						<!--*******************DEMANDE ************************-->
						<div
							style='font-family: police2; font-size: 17px; font-weight: bold;'> Examen clinique
						</div> 
							
					 <div>
					 
					 <table  id="ajustementChampsTextarea" style="width: 60%;">
                                    <tr class="comment-form-author textareaHT">
										<th style="width: 55%;"><?php echo $this->formRow($form->get('examen_clinique'));?></th>
									</tr>
				     </table>
				     </div>
				     </div> 
				  	</div>  
        

				<!-- ********************************-DOSSIERS *******************************************-->




				<!-- ********************Examen complementaire (examen et analyse)******************-->
				<!-- ********************Examen complementaire (examen et analyse)******************-->
				<!-- ********************Examen complementaire (examen et analyse)******************-->
				<!--*4*-->
				<div
					style='font-family: police2; font-size: 17px; font-weight: bold;'>Actes
					et Examens compl&eacute;mentaires</div>
				<div style='max-height: 600px;'>

					<div id="accordionsss" style=''>
						<!--******************* DEMANDE ************************-->
						<!--*******************DEMANDE ************************-->
						<div
							style='font-family: police2; font-size: 17px; font-weight: bold;'>
							Demande</div>
						<div style=''>
							<div
								style="padding-bottom: 0px; margin-bottom: 5px; border-bottom: 2px solid green; margin-left: 0px;"></div>
							<!-- LE PDF POUR IMPRESSION-->
							<div class="rendezvous">
								<hass>
								<input type="submit" title="Imprimer"
									name="demandeExamenBioMorpho" id="demandeExamenBioMorpho"> </hass>
							</div>
							<div
								style="padding-bottom: 40px; margin-bottom: 10px; border-bottom: 1px dashed green; margin-left: 0px; margin-right: 0px;"></div>

							<div id="accordions_demande">
                          
                          <?php 
                          /**
                           *===========================================================================
                           *===================== Les Actes  --- Les Actes  ===========================
                           *===================== Les Actes  --- Les Actes  ===========================
                           *===================== Les Actes  --- Les Actes  ===========================
                           *===========================================================================
                           **/?>
                          <div
									style='font-family: police2; font-size: 15px; font-weight: bold; color: green;'>
									Actes</div>
								<div>
									<div
										style="margin-bottom: 5px; border-bottom: 1.5px solid #cccccc; margin-top: -15px;"></div>

                           <?php 
                           /**
                            *=============================================================================================
                            *=============================================================================================
                            *=============================================================================================
                            **/
                            echo  $this->headScript()->appendFile($this->basePath().'/js/orl/ajouterActes.js');
                           ?>    
                                   
				            <div id="lesActes" style="width: 100%; height: 260px;">

										<table class="table table-bordered"
											style="width: 100%; margin-bottom: 0px; margin-left: 0px;">
											<thead style="width: 100%;">
												<tr style="width: 100%; height: 40px; font-family: police2;">
													<th style="width: 4%; font-weight: bold; font-size: 15px;">N&ordm;</th>
													<th
														style="width: 35%; font-weight: bold; font-size: 15px; text-align: left;">Acte</th>
													<th
														style="width: 15%; font-weight: bold; font-size: 15px; text-align: left;">Tarif
														(frs)</th>
													<th
														style="width: 37%; font-weight: bold; font-size: 15px; text-align: left;">Note</th>
													<th style="width: 9%; font-weight: bold; font-size: 15px;">Options</th>
												</tr>
											</thead>
										</table>

										<div id="Acte_0">
											<!-- A ne pas enlever -->
										</div>

										<!--********************* BOUTON AJOUTER-SUPPRIMER ************************-->
										<!--********************* BOUTON AJOUTER-SUPPRIMER ************************-->
										<div id="controls_acte" style="margin-top: 20px; width: 100%;">
											<div style="width: 100%;">
												<div style="width: 3%; float: left; cursor: pointer;"
													id="supprimer_acte">
													<img style='margin-left: 5px;'
														src='../images_icons/moin-green.png' title='supprimer' />
												</div>
												<div style="width: 3%; float: left; cursor: pointer;"
													id="ajouter_acte">
													<img style='margin-left: 5px;'
														src='../images_icons/plus-green.png' title='ajouter' />
												</div>
											</div>
										</div>

										<!--********************* BOUTON VALIDER OU MODIFIER ************************-->
										<!--********************* BOUTON VALIDER OU MODIFIER ************************-->
										<table
											style="width: 90%; float: right; position: relative; right: 0;">
											<tr style="width: 100%;">
												<th style="height: 15px;">
													<div id='bouton_Acte_valider_demande' style="float: right;">
														<button>Valider</button>
													</div>
													<div id='bouton_Acte_modifier_demande'
														style="float: right;">
														<button>Modifier</button>
													</div>
												</th>
											</tr>
										</table>

									</div>


									<!--********************* CHARGEMENT DES DONNEES  ************************-->
									<!--********************* CHARGEMENT DES DONNEES  ************************-->
									<!--********************* CHARGEMENT DES DONNEES  ************************-->
									<script> 
                               ValiderDemandeActe();
                            
                               var myArrayActe = [''];
                               var i = 1;

                               <?php foreach ($this->listeActes as $listeActes){ ?>
                                       myArrayActe[i++] =  "<?php echo $listeActes['designation']; ?>";
                               <?php } ?>
                               
                               partDefautActe(myArrayActe, 1);
                               
                               //Descactiver la visualisation des resultats pour afficher uniquement ceux selectionnés
                               setTimeout(function(){ desactiverResutatsActe (); }, 500);
                            </script>

								</div>
                          
                          
                          
                          <?php 
                          /**
                           *=============================================================================================
                           *===================== Examens Biologiques --- Examens Biologiques ===========================
                           *===================== Examens Biologiques --- Examens Biologiques ===========================
                           *===================== Examens Biologiques --- Examens Biologiques ===========================
                           *=============================================================================================
                           **/?>
                          <div
									style='font-family: police2; font-size: 15px; font-weight: bold; color: green;'>
									Examens Biologiques</div>
								<div>
									<div
										style="margin-bottom: 5px; border-bottom: 1.5px solid #cccccc; margin-top: -15px;"></div>

                           <?php 
                           /**
                            *=============================================================================================
                            *=============================================================================================
                            *=============================================================================================
                            **/
                            echo  $this->headScript()->appendFile($this->basePath().'/js/orl/ajouterExamensBio.js');
                           ?>    
                                   
				            <div id="lesExamensBiologiques"
										style="width: 100%; height: 260px;">

										<table class="table table-bordered"
											style="width: 100%; margin-bottom: 0px; margin-left: 0px;">
											<thead style="width: 100%;">
												<tr style="width: 100%; height: 40px; font-family: police2;">
													<th style="width: 4%; font-weight: bold; font-size: 15px;">N&ordm;</th>
													<th
														style="width: 28%; font-weight: bold; font-size: 15px; text-align: left;">Examen</th>
													<th
														style="width: 59%; font-weight: bold; font-size: 15px; text-align: left;">Note</th>
													<th style="width: 9%; font-weight: bold; font-size: 15px;">Options</th>
												</tr>
											</thead>
										</table>

										<div id="ExamenBio_0">
											<!-- A ne pas enlever -->
										</div>

										<!--********************* BOUTON AJOUTER-SUPPRIMER ************************-->
										<!--********************* BOUTON AJOUTER-SUPPRIMER ************************-->
										<div id="controls_examenBio"
											style="margin-top: 20px; width: 100%;">
											<div style="width: 100%;">
												<div style="width: 3%; float: left; cursor: pointer;"
													id="supprimer_examenBio">
													<img style='margin-left: 5px;'
														src='../images_icons/moin-green.png' title='supprimer' />
												</div>
												<div style="width: 3%; float: left; cursor: pointer;"
													id="ajouter_examenBio">
													<img style='margin-left: 5px;'
														src='../images_icons/plus-green.png' title='ajouter' />
												</div>
											</div>
										</div>

										<!--********************* BOUTON VALIDER OU MODIFIER ************************-->
										<!--********************* BOUTON VALIDER OU MODIFIER ************************-->
										<table
											style="width: 90%; float: right; position: relative; right: 0;">
											<tr style="width: 100%;">
												<th style="height: 15px;">
													<div id='bouton_ExamenBio_valider_demande'
														style="float: right;">
														<button>Valider</button>
													</div>
													<div id='bouton_ExamenBio_modifier_demande'
														style="float: right;">
														<button>Modifier</button>
													</div>
												</th>
											</tr>
										</table>

									</div>


									<!--********************* CHARGEMENT DES DONNEES  ************************-->
									<!--********************* CHARGEMENT DES DONNEES  ************************-->
									<!--********************* CHARGEMENT DES DONNEES  ************************-->
									<script> 
                               ValiderDemandeExamenBio();
                            
                               var myArrayExamenBio = [''];
                               var i = 1;
                            </script>
                            
                            <?php foreach ($this->listeDesExamensBiologiques as $examensBioListe){ ?>
                                <script> myArrayExamenBio[i++] =  "<?php echo $examensBioListe['libelleExamen']; ?>" </script>
                            <?php } ?>
                            
                            <script> 
                               partDefautExamenBio(myArrayExamenBio, 1);
                               //Descactiver la visualisation des resultats pour afficher uniquement ceux selectionnés
                               desactiverResutatsBio ();
                            </script>

								</div>
                            
                           <?php 
                          /**
                           *=============================================================================================
                           *================== Examens Morphologiques --- Examens Morphologiques ========================
                           *================== Examens Morphologiques --- Examens Morphologiques ========================
                           *================== Examens Morphologiques --- Examens Morphologiques ========================
                           *=============================================================================================
                          **/?>
                          <div
									style='font-family: police2; font-size: 15px; font-weight: bold; color: green;'>
									Examens Morphologiques</div>
								<div style="max-height: 250px;">
									<div
										style="margin-bottom: 5px; border-bottom: 1.5px solid #cccccc; margin-top: -15px;"></div>
                                        
                            <?php 
                            /**
                             *=============================================================================================
                             *=============================================================================================
                             *=============================================================================================
                            **/
                            echo  $this->headScript()->appendFile($this->basePath().'/js/orl/ajouter.js');
                            ?>    
                                   
				            <div id="lesElements" style="width: 100%;">
										<table class="table table-bordered"
											style="width: 100%; margin-bottom: 0px; margin-left: 0px;">
											<thead style="width: 100%;">
												<tr style="width: 100%; height: 40px; font-family: police2;">
													<th style="width: 4%; font-weight: bold; font-size: 15px;">N&ordm;</th>
													<th
														style="width: 28%; font-weight: bold; font-size: 15px; text-align: left;">Examen</th>
													<th
														style="width: 59%; font-weight: bold; font-size: 15px; text-align: left;">Note</th>
													<th style="width: 9%; font-weight: bold; font-size: 15px;">Options</th>
												</tr>
											</thead>
										</table>

										<div id="Element_0">
											<!-- A ne pas enlever -->
										</div>

									</div>

									<!--********************* BOUTON AJOUTER-SUPPRIMER ************************-->
									<!--********************* BOUTON AJOUTER-SUPPRIMER ************************-->
									<div id="controls_element"
										style="margin-top: 20px; width: 100%;">
										<div style="width: 100%;">
											<div style="width: 3%; float: left; cursor: pointer;"
												id="supprimer_element">
												<img style='margin-left: 5px;'
													src='../images_icons/moin-green.png' title='supprimer' />
											</div>
											<div style="width: 3%; float: left; cursor: pointer;"
												id="ajouter_element">
												<img style='margin-left: 5px;'
													src='../images_icons/plus-green.png' title='ajouter' />
											</div>
										</div>
									</div>

									<!--********************* BOUTON VALIDER OU MODIFIER ************************-->
									<!--********************* BOUTON VALIDER OU MODIFIER ************************-->
									<table
										style="width: 90%; float: right; position: relative; right: 0;">
										<tr style="width: 100%;">
											<th style="height: 15px;">
												<div id='bouton_morpho_valider_demande'
													style="float: right;">
													<button>Valider</button>
												</div>
												<div id='bouton_morpho_modifier_demande'
													style="float: right;">
													<button>Modifier</button>
												</div>
											</th>

										</tr>
									</table>
									<!--********************* CHARGEMENT DES DONNEES  ************************-->
									<!--********************* CHARGEMENT DES DONNEES  ************************-->
									<!--********************* CHARGEMENT DES DONNEES  ************************-->
                            <?php 
                            $nbDemande = count($this->listeDemandesMorphologiques);
                            if($nbDemande == 0){$nbDemande = 1;}
                            $tableauDesExamens = array();
                            ?>
                            
                            <script> 
                               ValiderDemande();
                               var myArray = [''];
                               var icmpt = 8;
                            </script>
                            <?php foreach ($this->listeDesExamensMorphologiques as $examensMorphoListe){ ?>
                               <script> myArray[icmpt++] =  "<?php echo $examensMorphoListe['libelleExamen']; ?>" </script>
                            <?php } ?>
                           
                            <script> 
                               partDefaut(myArray, '<?php echo $nbDemande; ?>');
                               var indligne = 0;
                            </script>

									<script>
                               //SELECTION DES LIGNES ET CHARGEMENT DE LEUR CONTENU 
                               <?php foreach($this->listeDemandesMorphologiques as $Liste) {
                                     $tableauDesExamens[] = $Liste['idExamen'];
                               	?>
                                   //Faire attention aux caracteres " et ' 
                                   chargementModification( indligne++, "<?php echo $Liste['idExamen'];?>" , "<?php echo $Liste['noteDemande'];?>");   
                               <?php } ?>
                            </script>
                            
                            <?php
                            /**
                             *=============================================================================================
                             *=============================================================================================
                             *=============================================================================================
                             **/
                            ?>      
                                   
                                </div>


							</div>
						</div>
						<!--**************** RESULTAT ************************-->
						<!--**************** RESULTAT ************************-->
						<div
							style='font-family: police2; font-size: 17px; font-weight: bold;'>
							R&eacute;sultats</div>
						<div>
							<div id="accordions_resultat" style='height: 470px;'>

								<!--**************** Actes ************************-->
								<!--**************** ACtes ************************-->
								<div
									style='font-family: police2; font-size: 15px; font-weight: bold; color: green;'>
									Actes</div>
								<div style='max-height: 320px;'>
									<div
										style="margin-bottom: 20px; border-bottom: 1px solid #cccccc; margin-top: -15px;"></div>
									<div style="width: 100%;">

										<div style="width: 80%; float: left; height: 1px;">
											<table id="ActeResponde" style="width: 100%;">

												<tr id="acte_1" class="" style="width: 100%;">
													<th> <?php echo $this->formRow($form->get('doppler_couleur_pulse'));?> </th>
												</tr>

												<tr id="acte_2" class="" style="width: 100%;">
													<th> <?php echo $this->formRow($form->get('echographie_de_stress'));?> </th>
												</tr>

												<tr id="acte_3" class="" style="width: 100%;">
													<th> <?php echo $this->formRow($form->get('holter_ecg'));?> </th>
												</tr>

												<tr id="acte_4" class="" style="width: 100%;">
													<th> <?php echo $this->formRow($form->get('holter_tensionnel'));?> </th>
												</tr>

												<tr id="acte_5" class="" style="width: 100%;">
													<th> <?php echo $this->formRow($form->get('fibroscopie_bronchique'));?> </th>
												</tr>

												<tr id="acte_6" class="" style="width: 100%;">
													<th> <?php echo $this->formRow($form->get('fibroscopie_gastrique'));?> </th>
												</tr>

												<tr id="acte_7" class="" style="width: 100%;">
													<th> <?php echo $this->formRow($form->get('colposcopie'));?> </th>
												</tr>

												<tr id="acte_8" class="" style="width: 100%;">
													<th> <?php echo $this->formRow($form->get('echographie_gynecologique'));?> </th>
												</tr>

												<tr id="acte_9" class="" style="width: 100%;">
													<th> <?php echo $this->formRow($form->get('echographie_obstetrique'));?> </th>
												</tr>

												<tr id="acte_10" class="" style="width: 100%;">
													<th> <?php echo $this->formRow($form->get('cpn'));?> </th>
												</tr>

												<tr id="acte_11" class="" style="width: 100%;">
													<th> <?php echo $this->formRow($form->get('consultation_senologie'));?> </th>
												</tr>

												<tr id="acte_12" class="" style="width: 100%;">
													<th> <?php echo $this->formRow($form->get('plannification_familiale'));?> </th>
												</tr>

												<tr id="acte_13" class="" style="width: 100%;">
													<th> <?php echo $this->formRow($form->get('ecg'));?> </th>
												</tr>

												<tr id="acte_14" class="" style="width: 100%;">
													<th> <?php echo $this->formRow($form->get('eeg'));?> </th>
												</tr>

												<tr id="acte_15" class="" style="width: 100%;">
													<th> <?php echo $this->formRow($form->get('efr'));?> </th>
												</tr>

												<tr id="acte_16" class="" style="width: 100%;">
													<th> <?php echo $this->formRow($form->get('emg'));?> </th>
												</tr>

												<tr id="acte_17" class="" style="width: 100%;">
													<th> <?php echo $this->formRow($form->get('circoncision'));?> </th>
												</tr>

												<tr id="acte_18" class="" style="width: 100%;">
													<th> <?php echo $this->formRow($form->get('vaccination'));?> </th>
												</tr>

												<tr id="acte_19" class="" style="width: 100%;">
													<th> <?php echo $this->formRow($form->get('soins_infirmiers'));?> </th>
												</tr>

											</table>
										</div>
										<div style="width: 18%; float: left;">
											<p style='color: white; opacity: 0.5;'>
												<img id=""
													src='<?php echo $this->basePath().'/images_icons/analys.jpg'?>'
													alt="consult-motif"
													style='padding-top: 50px; width: 100%; height: 240px;'>
											</p>
										</div>

									</div>
								</div>



								<!--**************** ANALYSE BIOLOGIQUE ************************-->
								<!--**************** ANALYSE BIOLOGIQUE ************************-->
								<div
									style='font-family: police2; font-size: 15px; font-weight: bold; color: green;'>
									Examens Biologiques</div>
								<div style='max-height: 320px;'>
									<div
										style="margin-bottom: 20px; border-bottom: 1px solid #cccccc; margin-top: -15px;"></div>
									<div style="width: 100%;">

										<div style="width: 82%; float: left; height: 1px;">
											<table id="respondee" style="width: 100%;">
												<tr id="groupe_sanguin" class="form-groupe"
													style="width: 100%;">
													<th id="groupe"> <?php echo $this->formRow($form->get('groupe_sanguin'));?> </th>
												</tr>

												<tr id="hemogramme_sanguin" class="form-analyse-biologique"
													style="width: 100%;">
													<th> <?php echo $this->formRow($form->get('hemogramme_sanguin'));?> </th>
												</tr>

												<tr id="bilan_hemolyse" class="form-analyse-biologique"
													style="width: 100%;">
													<th> <?php echo $this->formRow($form->get('bilan_hemolyse'));?> </th>
												</tr>

												<tr id="bilan_hepatique" class="form-analyse-biologique"
													style="width: 100%;">
													<th> <?php echo $this->formRow($form->get('bilan_hepatique'));?> </th>
												</tr>

												<tr id="bilan_renal" class="form-analyse-biologique"
													style="width: 100%;">
													<th> <?php echo $this->formRow($form->get('bilan_renal'));?> </th>
												</tr>

												<tr id="bilan_inflammatoire" class="form-analyse-biologique"
													style="width: 100%;">
													<th> <?php echo $this->formRow($form->get('bilan_inflammatoire'));?> </th>
												</tr>
											</table>
										</div>
										<div style="width: 18%; float: left;">
											<p style='color: white; opacity: 0.5;'>
												<img id=""
													src='<?php echo $this->basePath().'/images_icons/analys.jpg'?>'
													alt="consult-motif"
													style='padding-top: 50px; width: 100%; height: 240px;'>
											</p>
										</div>

									</div>
								</div>

								<!--**************** EXAMEN MORPHOLOGIQUES ************************-->
								<!--**************** EXAMEN MORPHOLOGIQUES ************************-->
								<!--*** Utilisation du plugin fancybox ***-->
								<div
									style='font-family: police2; font-size: 15px; font-weight: bold; color: green;'>Examens
									Morphologiques</div>
								<div style='max-height: 320px;'>
									<div
										style="margin-bottom: 8px; border-bottom: 1px solid #cccccc; margin-top: -15px;"></div>
                           
                          <?php echo  $this->headScript()->appendFile($this->basePath().'/js/orl/majComplementCons.js');?>
                            
                            <!-- AFFICHAGE DES EXAMENS N'AYANT PAS ENCORE D'IMAGES -->
									<!-- AFFICHAGE DES EXAMENS N'AYANT PAS ENCORE D'IMAGES -->
									<script>
                              getimagesExamensMorphologiques();
                              getimagesEchographieExamensMorphologiques();
                              getimagesIRMExamensMorphologiques();
                              getimagesScannerExamensMorphologiques();
                              getimagesFibroscopieExamensMorphologiques();
                            
                              <?php for($i = 0; $i<count($tableauDesExamens); $i++) {?>
                                  affichageExamenMorphoSansImages("<?php echo $tableauDesExamens[$i];?>");   
                              <?php } if(count($tableauDesExamens) == 0){ ?> affichageExamenMorphoSansImages(0); <?php }?>
                            </script>

									<!-- POP UP pour Confirmation Suppression -->
									<div id="confirmation" title="Confirmation de la suppression"
										style="display: none;">
										<p style="font-size: 15px;">
											<span style="float: left; margin: 0 0px 20px 0;"> <img
												src="<?php echo $this->basePath().'/images_icons/warning_16.png';?>" />
												Etes-vous s&ucirc;r de vouloir supprimer l'image ?
											</span>
										</p>
									</div>
									<!-- NOUVEAU CODE POUR LA GESTION DES IMAGES  -->
									<!-- NOUVEAU CODE POUR LA GESTION DES IMAGES  -->
									<!-- NOUVEAU CODE POUR LA GESTION DES IMAGES  -->

									<!-- RADIO RADIO RADIO  -->
									<!-- RADIO RADIO RADIO  -->
									<!-- RADIO RADIO RADIO  -->
									<!-- RADIO RADIO RADIO  -->
									<input type='hidden' id="typeExamen_tmp" />
									<table id="respondeee" class="imageRadio" style="width: 100%;">
										<tr class="form-examen-morphologique" style="width: 100%;">
											<th style="width: 40%; vertical-align: top;"> <?php echo $this->formRow($form->get('radio'));?></th>
											<th
												style="width: 25%; vertical-align: top; padding-top: 50px;">
												<img
												src="<?php echo $this->basePath().'/images_icons/right_64.png';?>" />
											</th>
											<th
												style="width: 34%; padding-bottom: 15px; margin-right: 40px;">
												<!-- PIKACHOOSE --> <!-- PIKACHOOSE -->
												<div id="pika">
													<div id="pika2">
														<!-- EMPLACEMENT DES IMAGES -->
														<!-- EMPLACEMENT DES IMAGES -->
														<!-- EMPLACEMENT DES IMAGES -->
													</div>
												</div>
												<div id="AjoutImage"
													style="float: right; position: relative; bottom: 42px; right: 5px;">
													<input type='file' name="fichier" />
													<!-- RECUPERER L'IMAGE -->
													<input type='hidden' id="fichier_tmp" name="fichier_tmp" />
													<!-- FICHIER TAMPON POUR RECUPERER L'IMAGE DANS LE CONTROLLER -->
												</div>
											</th>
										</tr>

										<tr style="width: 100%;">
											<th colspan="3"><div
													style="width: 100%; margin-top: -20px; margin-bottom: -10px; border-bottom: 2px solid green;"></div></th>
										</tr>
									</table>

									<!-- ECHOGRAPHIE ECHOGRAPHIE ECHOGRAPHIE  -->
									<!-- ECHOGRAPHIE ECHOGRAPHIE ECHOGRAPHIE  -->
									<!-- ECHOGRAPHIE ECHOGRAPHIE ECHOGRAPHIE  -->
									<!-- ECHOGRAPHIE ECHOGRAPHIE ECHOGRAPHIE  -->
									<table id="respondeee" class="imageEchographie"
										style="width: 100%;">
										<tr class="form-examen-morphologique" style="width: 100%;">
											<th style="width: 40%; vertical-align: top;"> <?php echo $this->formRow($form->get('ecographie'));?></th>
											<th
												style="width: 25%; vertical-align: top; padding-top: 50px;">
												<img
												src="<?php echo $this->basePath().'/images_icons/right_64.png';?>" />
											</th>
											<th
												style="width: 34%; padding-bottom: 15px; margin-right: 40px;">
												<!-- PIKACHOOSE --> <!-- PIKACHOOSE -->
												<div id="pika3">
													<div id="pika4">
														<!-- EMPLACEMENT DES IMAGES -->
														<!-- EMPLACEMENT DES IMAGES -->
														<!-- EMPLACEMENT DES IMAGES -->
													</div>
												</div>
												<div id="AjoutImageEchographie"
													style="float: right; position: relative; bottom: 42px; right: 5px;">
													<input type='file' name="fichierEchographie" />
													<!-- RECUPERER L'IMAGE -->
													<input type='hidden' id="fichierEchographie_tmp"
														name="fichierEchographie_tmp" />
													<!-- FICHIER TAMPON POUR RECUPERER L'IMAGE DANS LE CONTROLLER -->
												</div>
											</th>
										</tr>

										<tr style="width: 100%;">
											<th colspan="3"><div
													style="width: 100%; margin-top: -20px; margin-bottom: -10px; border-bottom: 2px solid green; margin-left: 0px; margin-right: 0px;"></div></th>
										</tr>
									</table>

									<!-- IRM IRM IRM  -->
									<!-- IRM IRM IRM  -->
									<!-- IRM IRM IRM  -->
									<!-- IRM IRM IRM  -->
									<table id="respondeee" class="imageIRM" style="width: 100%;">
										<tr class="form-examen-morphologique" style="width: 100%;">
											<th style="width: 40%; vertical-align: top;"> <?php echo $this->formRow($form->get('irm'));?></th>
											<th
												style="width: 25%; vertical-align: top; padding-top: 50px;">
												<img
												src="<?php echo $this->basePath().'/images_icons/right_64.png';?>" />
											</th>
											<th
												style="width: 34%; padding-bottom: 15px; margin-right: 40px;">
												<!-- PIKACHOOSE --> <!-- PIKACHOOSE -->
												<div id="pika5">
													<div id="pika6">
														<!-- EMPLACEMENT DES IMAGES -->
														<!-- EMPLACEMENT DES IMAGES -->
														<!-- EMPLACEMENT DES IMAGES -->
													</div>
												</div>
												<div id="AjoutImageIRM"
													style="float: right; position: relative; bottom: 42px; right: 5px;">
													<input type='file' name="fichierIRM" />
													<!-- RECUPERER L'IMAGE -->
													<input type='hidden' id="fichierIRM_tmp"
														name="fichierIRM_tmp" />
													<!-- FICHIER TAMPON POUR RECUPERER L'IMAGE DANS LE CONTROLLER -->
												</div>
											</th>
										</tr>

										<tr style="width: 100%;">
											<th colspan="3"><div
													style="width: 100%; margin-top: -20px; margin-bottom: -10px; border-bottom: 2px solid green;"></div></th>
										</tr>
									</table>

									<!-- SCANNER SCANNER SCANNER  -->
									<!-- SCANNER SCANNER SCANNER  -->
									<!-- SCANNER SCANNER SCANNER  -->
									<!-- SCANNER SCANNER SCANNER  -->
                                 
                 <?php
                   echo $this->headLink()->appendStylesheet($this->basePath().'/js/plugins/jPlayer-2.9.2/dist/skin/blue.monday/css/jplayer.blue.monday.min.css');
                   echo $this->headScript()->appendFile($this->basePath().'/js/plugins/jPlayer-2.9.2/dist/jplayer/jquery.jplayer.min.js');
                   echo $this->headScript()->appendFile($this->basePath().'/js/plugins/jPlayer-2.9.2/dist/add-on/jplayer.playlist.min.js');
                   echo $this->headScript()->appendFile($this->basePath().'/js/archivage/jsAjouterSuppimerVideos.js');
                 ?>
                            <table id="respondeee" class="imageScanner"
										style="width: 100%;">
										<tr class="form-examen-morphologique" style="width: 100%;">

											<th style="width: 40%; vertical-align: top;"> <?php echo $this->formRow($form->get('scanner'));?></th>
											<th
												style="width: 25%; vertical-align: top; padding-top: 50px;">
												<img
												src="<?php echo $this->basePath().'/images_icons/right_64.png';?>" />
											</th>
											<th
												style="width: 34%; padding-bottom: 15px; margin-right: 40px;">
												<!-- POUR LE MENU VIDEO ET IMAGE --> <!-- POUR LE MENU VIDEO ET IMAGE -->
												<!-- POUR LE MENU VIDEO ET IMAGE -->
												<div id="divPourMenuImagesVideos" style="height: 150px;">
													<table
														style='width: 100%; margin-bottom: 25px; margin-top: 25px;'>
														<tr style='width: 100%;'>
															<td style='width: 50%;'><img id="IconeImagesMenu"
																style="cursor: pointer; top: 20px; float: right;"
																src="<?php echo $this->basePath().'/images_icons/icone_image_96X96.png';?>" />
															</td>
															<td style='width: 50%;'><img id="IconeVideosMenu"
																style="cursor: pointer; top: 20px; float: right;"
																src="<?php echo $this->basePath().'/images_icons/icone_video_96X96.png';?>" />
															</td>
														</tr>
														<tr style='width: 100%;'>
															<td style='width: 50%;'><span
																style="top: 5px; float: right; margin-right: 25px; font-family: Times new roman; color: green;">
																	Images</span></td>
															<td style='width: 50%;'><span
																style="top: 5px; float: right; margin-right: 25px; font-family: Times new roman; color: green;">
																	Vid&eacute;os</span></td>
														</tr>
													</table>
												</div> <!-- POUR LES VIDEOS --> <!-- POUR LES VIDEOS --> <!-- POUR LES VIDEOS -->
												<div id="divVideoScannerPourMenu">
													<table style='width: 100%;'>
														<tr style='width: 100%;'>
															<td>
																<table style='width: 100%;'>
																	<tr style='width: 100%;'>
																		<td style='width: 10%; vertical-align: top;'>
																			<div style='width: 17px;'>
																				<img id="RetourDeVideosVersMenu"
																					style="cursor: pointer; width: 16px; height: 16px;"
																					src="<?php echo $this->basePath().'/images_icons/left_16.png';?>" />
																			</div>
																		</td>
																		<td style='width: 90%;'>
																			<div id='AfficherLecteurVideoScanner'
																				style='margin-left: 1px; margin-right: 0px; margin-bottom: 15px;'>
																				Emplacement de la video pour le scanner</div>
																		</td>
																	</tr>
																</table>
															</td>
														</tr>
													</table>
												</div> <!-- POUR LES IMAGES --> <!-- POUR LES IMAGES --> <!-- POUR LES IMAGES -->
												<div id="divImageScannerPourMenu">

													<table style='width: 100%;'>
														<tr style='width: 100%;'>
															<td style='width: 1%; vertical-align: top;'>
																<div style='width: 16px; position: absolute;'>
																	<img id="RetourDeImagesVersMenu"
																		style="cursor: pointer; width: 16px; height: 16px;"
																		src="<?php echo $this->basePath().'/images_icons/left_16.png';?>" />
																</div>
															</td>


															<td style='width: 99%;'>
																<!-- PIKACHOOSE --> <!-- PIKACHOOSE -->
																<div id="pika7">
																	<div id="pika8">
																		<!-- EMPLACEMENT DES IMAGES -->
																		<!-- EMPLACEMENT DES IMAGES -->
																		<!-- EMPLACEMENT DES IMAGES -->
																	</div>
																</div>
																<div id="AjoutImageScanner"
																	style="float: right; position: relative; bottom: 42px; right: 5px;">
																	<input type='file' name="fichierScanner" />
																	<!-- RECUPERER L'IMAGE -->
																	<input type='hidden' id="fichierScanner_tmp"
																		name="fichierScanner_tmp" />
																	<!-- FICHIER TAMPON POUR RECUPERER L'IMAGE DANS LE CONTROLLER -->
																</div>
															</td>
														</tr>
													</table>

												</div>

											</th>


										</tr>

										<tr style="width: 100%;">
											<th colspan="3"><div
													style="width: 100%; margin-top: -20px; margin-bottom: -10px; border-bottom: 2px solid green;"></div></th>
										</tr>
									</table>

									<!-- FIBROSCOPIE FIBROSCOPIE FIBROSCOPIE  -->
									<!-- FIBROSCOPIE FIBROSCOPIE FIBROSCOPIE  -->
									<!-- FIBROSCOPIE FIBROSCOPIE FIBROSCOPIE  -->
									<!-- FIBROSCOPIE FIBROSCOPIE FIBROSCOPIE  -->
                            <?php ?>
                            <table id="respondeee"
										class="imageFibroscopie" style="width: 100%;">
										<tr class="form-examen-morphologique" style="width: 100%;">
											<th style="width: 40%; vertical-align: top;"> <?php echo $this->formRow($form->get('fibrocospie'));?></th>
											<th
												style="width: 25%; vertical-align: top; padding-top: 50px;">
												<img
												src="<?php echo $this->basePath().'/images_icons/right_64.png';?>" />
											</th>
											<th
												style="width: 34%; padding-bottom: 15px; margin-right: 40px;">
												<!-- PIKACHOOSE --> <!-- PIKACHOOSE -->
												<div id="pika9">
													<div id="pika10">
														<!-- EMPLACEMENT DES IMAGES -->
														<!-- EMPLACEMENT DES IMAGES -->
														<!-- EMPLACEMENT DES IMAGES -->
													</div>
												</div>
												<div id="AjoutImageFibroscopie"
													style="float: right; position: relative; bottom: 42px; right: 5px;">
													<input type='file' name="fichierFibroscopie" />
													<!-- RECUPERER L'IMAGE -->
													<input type='hidden' id="fichierFibroscopie_tmp"
														name="fichierFibroscopie_tmp" />
													<!-- FICHIER TAMPON POUR RECUPERER L'IMAGE DANS LE CONTROLLER -->
												</div>
											</th>
										</tr>

										<tr style="width: 100%;">
											<th colspan="3"><div
													style="width: 100%; margin-top: -20px; margin-bottom: -10px; border-bottom: 2px solid green;"></div></th>
										</tr>
									</table>
                            <?php ?>
                            
                            <!--********************* BOUTON VALIDER OU MODIFIER ************************-->
									<!--********************* BOUTON VALIDER OU MODIFIER ************************-->
									<!--********************* BOUTON VALIDER OU MODIFIER ************************-->
									<table class="bouton_valider_examen_morpho" style="width: 90%;">
										<tr style="width: 90%;">
											<th style="width: 31%;"></th>
											<th
												style="height: 15px; width: 69%; top: -15px; bottom: 15px;">
												<!-- On crï¿½e le bouton Valider (permettant la validation des donnï¿½es -->
												<div id="bouton_valider_morpho" style="float: left;">
													<button id='bouton_morpho_valider'>Valider</button>
												</div> <!-- On crï¿½e le bouton MODIFIER (permettant la modification des donnï¿½es -->
												<div id="bouton_modifier_morpho" style="float: left;">
													<button id='bouton_morpho_modifier'>Modifier</button>
												</div>
											</th>

										</tr>
									</table>

								</div>

							</div>

						</div>

					</div>

				</div>
				
		<!-- ********************************-Examen paraclinique *******************************************-->
        
    		<div style='font-family: police2; font-size: 17px; font-weight: bold;'>Examen paraclinique</div>
				<div style='max-height: 300px;'>

					<div id="accordionsss_paraclinik" style=''>
						<!--******************* DEMANDE ************************-->
						<!--*******************DEMANDE ************************-->
						<div
							style='font-family: police2; font-size: 17px; font-weight: bold;'> Examen paraclinique
						</div> 
						<div>
						
						
					 <table  id="ajustementChampsTextarea" style="width: 60%;">
                                    <tr class="comment-form-author textareaHT">
										<th style="width: 55%;"><?php echo $this->formRow($form->get('examen_para_clinique'));?></th>
									</tr>
				     </table>
						
						</div>
						
							
					 </div> 
				</div>  

				<!-- *******************************Diagnostic***********************************-->
				<!-- *******************************Diagnostic***********************************-->
				<!-- *******************************Diagnostic***********************************-->

				<!--*5*-->
				<div
					style='font-family: police2; font-size: 17px; font-weight: bold;'>Diagnostic
					(pr&eacute;liminaire et/ou final)</div>
				<div style='max-height: 280px;'>
					<p style='color: white; opacity: 0.5;'>
						<img id=""
							src='<?php echo $this->basePath().'/images_icons/diag.png'?>'
							alt="consult-motif"
							style='float: right; margin-right: 10px; width: 28%; height: 220px;' />
					</p>
        <?php echo  $this->headScript()->appendFile($this->basePath().'/js/orl/ajouterDiagnostic.js');?>

        <table id="responded" style="width: 65%;">
						<tr id="diag1" class="form-diag" style="width: 65%; height: 40px;">
							<th> <?php echo $this->formRow($form->get('diagnostic1')); ?> <span
								id="label"> <img class='supprimerDiag1' style='cursor: pointer;'
									src='../images/images/sup.png' title='supprimer' />
							</span>
							</th>
						</tr>

						<tr id="diag2" class="form-diag" style="width: 65%;">
							<th> <?php echo $this->formRow($form->get('diagnostic2')); ?> <span
								id="label"> <img class='supprimerDiag2' style='cursor: pointer;'
									src='../images/images/sup.png' title='supprimer' />
							</span></th>
						</tr>

						<tr id="diag3" class="form-diag" style="width: 65%;">
							<th> <?php echo $this->formRow($form->get('diagnostic3')); ?> <span
								id="label"> <img class='supprimerDiag3' style='cursor: pointer;'
									src='../images/images/sup.png' title='supprimer' />
							</span></th>
						</tr>

						<tr id="diag4" class="form-diag" style="width: 65%;">
							<th> <?php echo $this->formRow($form->get('diagnostic4')); ?> <span
								id="label"> <img class='supprimerDiag4' style='cursor: pointer;'
									src='../images/images/sup.png' title='supprimer' />
							</span></th>
						</tr>
					</table>

					<!--********************* BOUTON AJOUTER-SUPPRIMER ************************-->
					<!--********************* BOUTON AJOUTER-SUPPRIMER ************************-->
					<div id="controls_diagnostics"
						style="margin-top: 10px; width: 100%;">
						<div style="width: 100%; background: green;">
							<div style="width: 3%; height: 1px; float: left;"
								id="supprimer_diagnostic">
								<img id="supprimer_diagnostic_img"
									style='margin-left: 5px; cursor: pointer;'
									src='../images_icons/moin-green.png' title='supprimer' />
							</div>
							<div style="width: 3%; height: 1px; float: left;"
								id="ajouter_diagnostic">
								<img id="ajouter_diagnostic_img"
									style='margin-left: 5px; cursor: pointer;'
									src='../images_icons/plus-green.png' title='ajouter' />
							</div>
						</div>
					</div>

					<!--********************* BOUTON VALIDER-MODIFIER ************************-->
					<!--********************* BOUTON VALIDER-MODIFIER ************************-->
					<table style="width: 59%; position: relative; top: 0px;">
						<tr style="width: 90%;">
							<th style="width: 65%;">
								<div style="float: right;">
									<button id='bouton_diagnostic_valider'>Valider</button>
								</div>
								<div style="float: right;">
									<button id='bouton_diagnostic_modifier'>Modifier</button>
								</div>
							</th>
						</tr>
					</table>

			<script>
              var nbdiagnostic = 1;
              cacherTout();
              afficher(nbdiagnostic);
              supprimerUnDiagnostic();
         </script>

				</div>


				<!-- **************************Traitements(ordonnance)**************************-->
				<!-- **************************Traitements(ordonnance)**************************-->
				<!-- **************************Traitements(ordonnance)**************************-->

				<!--*6*-->
				<div
					style='font-family: police2; font-size: 17px; font-weight: bold;'>Ordonnance</div>
				<div style="max-height: 550px;">
					<!--**************** NOUVELLE ACCORDEON *********************  -->
					<!--**************** NOUVELLE ACCORDEON *********************  -->
					<div id="accordionssss">

						<!-- ************** Traitement Mï¿½dical **************** -->
						<!-- **1** -->
						<div
							style='font-family: police2; font-size: 17px; font-weight: bold;'>
							M&eacute;dicamenteux</div>
						<div>

							<!--******* ======= MENU MENU MENU =======  ******-->
							<!--******* ======= MENU MENU MENU =======  ******-->
							<div
								style="padding-bottom: 0px; margin-bottom: 5px; border-bottom: 2px solid green; margin-left: 0px;"></div>
							<!-- LE PDF POUR IMPRESSION-->
							<div class="ordonnance">
								<input type="submit" name="ordonnance" id="ordonnance" />

							</div>

							<!-- LE CHAMP POUR LA DUREE DU TRAITEMENT DE L'ORDONNANCE-->
							<div id="duree_traitement">
								<div class="form-duree_">
									<label> Dur&eacute;e traitement m&eacute;dical </label><input
										style="margin-top: 2px; margin-bottom: 5px;" type="text"
										class="duree_traitement_ord" id="duree_traitement_ord"
										name="duree_traitement_ord" />
								</div>
								<p
									style="display: inline; float: left; border: transparent; margin-top: 8px; margin-left: 5px; font-family: police3; font-size: 19px;">jours</p>
							</div>

							<div
								style="padding-bottom: 40px; margin-bottom: 10px; border-bottom: 1px dashed green; margin-left: 0px; margin-right: 0px;"></div>

							<!--******* ======= MEDICAMENTS MEDICAMENTS =======  ******-->
							<!--******* ======= MEDICAMENTS MEDICAMENTS =======  ******-->
                    
                  
                  <?php 
                      /**
                       *=============================================================================================
                       *=============================================================================================
                       *=============================================================================================
                       **/
                   echo  $this->headScript()->appendFile($this->basePath().'/js/orl/ajouterMedicaments.js');
                  ?>    
                                   
                 <div id="listeMedicaments"
								style="float: left; width: 100%;">

								<table class="table table-bordered"
									style="width: 100%; margin-bottom: 0px; margin-left: 0px;">
									<thead style="width: 100%;">
										<tr style="width: 100%; height: 40px; font-family: police2;">
											<th style="width: 4%; font-weight: bold; font-size: 15px;">N&ordm;</th>
											<th
												style="width: 29%; font-weight: bold; font-size: 15px; text-align: left;">M&eacute;dicaments</th>
											<th
												style="width: 29%; font-weight: bold; font-size: 15px; text-align: left;">Forme</th>
											<th
												style="width: 29%; font-weight: bold; font-size: 15px; text-align: left;">Quantit&eacute;</th>
											<th style="width: 9%; font-weight: bold; font-size: 15px;">Options</th>
										</tr>
									</thead>
								</table>

								<div id="Medicament_0" style="width: 100%;">
									<!-- A ne pas enlever -->
								</div>


								<!--********************* BOUTON AJOUTER-SUPPRIMER ************************-->
								<!--********************* BOUTON AJOUTER-SUPPRIMER ************************-->
								<div id="controls_medicament"
									style="margin-top: 20px; width: 100%;">
									<div style="width: 100%;">
										<div style="width: 3%; float: left; cursor: pointer;"
											id="supprimer_medicament">
											<img style='margin-left: 5px;'
												src='../images_icons/moin-green.png' title='supprimer' />
										</div>
										<div style="width: 3%; float: left; cursor: pointer;"
											id="ajouter_medicament">
											<img style='margin-left: 5px;'
												src='../images_icons/plus-green.png' title='ajouter' />
										</div>
									</div>
								</div>

								<!--********************* BOUTON VALIDER OU MODIFIER ************************-->
								<!--********************* BOUTON VALIDER OU MODIFIER ************************-->
								<table
									style="width: 90%; float: right; position: relative; right: 0;">
									<tr style="width: 100%;">
										<th style="height: 15px;">
											<div id='bouton_Medicament_modifier_demande'
												style="float: right;">
												<button>Modifier</button>
											</div>
											<div id='bouton_Medicament_valider_demande'
												style="float: right;">
												<button>Valider</button>
											</div>
										</th>
									</tr>
								</table>

							</div>


							<!--********************* CHARGEMENT DES DONNEES  ************************-->
							<!--********************* CHARGEMENT DES DONNEES  ************************-->
							<!--********************* CHARGEMENT DES DONNEES  ************************-->
							<script> 
                   ValiderOrdonnance();

                   //var myArrayMedicament = [''];
                   <?php /* foreach($this->liste_med as $Liste) {?>
                            myArrayMedicament["<?php echo $Liste['ID_MATERIEL']; ?>"] = "<?php echo $Liste['INTITULE']; ?>"; 
                   <?php } */ ?>
                               
                   //partDefautMedicament(myArrayMedicament, 1);


                   var myArrayMedicament = [''];
                   var myArrayForme = [''];
                   var myArrayTypeQuantiteMedicament = [''];

                   /*Nouveau Code Ajouter*/
                   /*Nouveau Code Ajouter*/
                   /*Nouveau Code Ajouter*/ 
                    var j = 0;
                    <?php foreach($this->liste_med as $Liste) {?>
                           myArrayMedicament[j++] = "<?php echo $Liste['INTITULE']; ?>"; 
                    <?php } ?>
                    
                    var j = 0;
                    <?php foreach($this->listeForme as $ListeForme) {?>
                           myArrayForme[j++] = "<?php echo $ListeForme['libelleForme']; ?>"; 
                    <?php } ?>

                    var j = 0;
                    <?php foreach($this->listetypeQuantiteMedicament as $listetypeQuantiteMedicament) {?>
                           myArrayTypeQuantiteMedicament[j++] = "<?php echo $listetypeQuantiteMedicament['libelleQuantite']; ?>"; 
                    <?php } ?>

                    partDefautMedicament(myArrayMedicament, myArrayForme, myArrayTypeQuantiteMedicament, 1);
                    
                    /* =================== */
                 </script>

						</div>


						<!-- ************** Traitement Chirurgical **************** -->
						<!-- **2** -->
						<div
							style='font-family: police2; font-size: 17px; font-weight: bold;'>
							Chirurgical</div>
						<div style="max-height: 370px;">

							<div id="tabs-traitement-chirurgical">
								<ul>
									<li><a href="#tabs-1">Demande de visite
											pr&eacute;-anesth&eacute;sique</a></li>
									<li id='CompteRenduTabs'><a href="#tabs-2">Compte rendu
											op&eacute;ratoire</a></li>
								</ul>

								<div id="tabs-1">
									<div
										style="padding-bottom: 0px; margin-bottom: 5px; border-bottom: 2px solid green; margin-left: 0px;"></div>
									<!-- LE PDF POUR IMPRESSION-->
									<div class="rendezvous">
										<hass>
										<input type="submit" alt="Constantes" title="Imprimer"
											name="traitement_chirurgical" id="chirurgical1"></hass>
									</div>

									<div class="annulertransfert">
										<hass>
										<input type="submit" alt="Constantes" title="Annuler"
											name="annuler_traitement_chirurgical"
											id="annuler_traitement_chirurgical"></hass>
									</div>
									<div
										style="padding-bottom: 40px; margin-bottom: 10px; border-bottom: 1px dashed green; margin-left: 0px; margin-right: 0px;"></div>

									<table id="chirurgical" style="width: 100%;">
										<tr class="form-chirurgical" style="width: 100%;">
											<th style="width: 33%;"> <?php //echo $this->formRow($form->get('diagnostic_traitement_chirurgical'));?> </th>
											<th style="width: 33%;"> <?php //echo $this->formRow($form->get('observation'));?> </th>
											<th style="width: 33%;"> <?php //echo $this->formRow($form->get('intervention_prevue'));?> </th>
										</tr>
										<tr class="form-chirurgical" style="width: 100%;">
											<th style="width: 33%;"></th>
											<th style="width: 33%;"></th>
											<th style="width: 33%; padding-right: 30px;">
												<div id="bouton_valider_chirurgical"
													style='margin-top: 30px; float: right;'>
													<button id='bouton_chirurgical_valider'>Valider</button>
												</div>
												<div id="bouton_modifier_chirurgical"
													style='margin-top: 30px; float: right;'> 
													<button id='bouton_chirurgical_modifier'>Modifier</button>
												</div>
											</th>

										</tr>
									</table>

								</div>

								<div id="tabs-2" style="min-height: 100px;">
									<table id="transfertsq" style="width: 100%;">
										<tr style="width: 100%;">
											<td style="width: 55%; vertical-align: top;">
												<div id="AfficherLecteurqs"
													style='margin-right: 40px; vertical-align: top;'>
													<!-- ****** EMPLACEMENT DU LECTEUR AUDIO (MP3)********* -->
												</div>
											</td>
											<td class="form-transfert"
												style="width: 45%; vertical-align: top;">
												<div class="rendezvous"
													style='cursor: pointer; float: right; margin-top: 5px; margin-right: 40px;'>
													<hass> <input type="submit" title="Imprimer"
														name="protocole_operatoire" id="protocole_operatoire"> </hass>
												</div>
                             <?php echo $this->formRow($form->get('note_compte_rendu_operatoire'));?> 
                             <table style="width: 97%;">
													<tr style="width: 100%;">
														<td style="width: 100%; padding-right: 30px;">
															<div style='margin-top: 10px; float: right;'>
																<button id='bouton_compte_rendu_chirurgical_valider'>Valider</button>
															</div>
															<div style='margin-top: 10px; float: right;'>
																<button id='bouton_compte_rendu_chirurgical_modifier'>Modifier</button>
															</div>
														</td>
													</tr>
												</table>
											</td>

										</tr>
									</table>
								</div>

							</div>

							<script type="text/javascript">
                     <?php echo $this->headScript()->appendFile($this->basePath().'/js/orl/jsAjouterSuppimerMp3.js');?>
                    </script>
						</div>

						<!-- ************** Traitement Instrumental **************** -->
						<!-- **3** -->
						<div
							style='font-family: police2; font-size: 17px; font-weight: bold;'>
							Instrumental</div>

						<div style="max-height: 370px;">

							<div id="tabsInstrumental">

								<ul>
									<li><a href="#tabsInstrumental-1">Traitement</a></li>
									<li id='CompteRenduInstrumentalTabs'><a
										href="#tabsInstrumental-2">Compte rendu op&eacute;ratoire</a></li>
								</ul>

								<div id="tabsInstrumental-1">
									<!-- ******* -->
									<!-- ******* -->
									<div
										style="padding-bottom: 0px; margin-bottom: 5px; border-bottom: 2px solid green; margin-left: 0px;"></div>
									<!-- LE PDF POUR IMPRESSION-->
									<div class="rendezvous">
										<hass>
										<input type="submit" alt="Constantes" title="Imprimer"
											name="traitement_instrumental" id="instrumental1"></hass>
									</div>

									<div class="annulertransfert">
										<hass>
										<input type="submit" alt="Constantes" title="Annuler"
											name="annuler_traitement_instrumental"
											id="annuler_traitement_instrumental"></hass>
									</div>
									<div
										style="padding-bottom: 40px; margin-bottom: 10px; border-bottom: 1px dashed green; margin-left: 0px; margin-right: 0px;"></div>

									<table id="Traitementinstrumental" style="width: 100%;">
										<tr class="form-instrumental" style="width: 90%;">
											<th style="width: 95%;"> <?php echo $this->formRow($form->get('endoscopieInterventionnelle'));?> </th>
										</tr>
										<tr class="form-instrumental" style="width: 90%;">
											<th style="width: 95%;"> <?php echo $this->formRow($form->get('radiologieInterventionnelle'));?> </th>
										</tr>
										<tr class="form-instrumental" style="width: 90%;">
											<th style="width: 95%;"> <?php echo $this->formRow($form->get('cardiologieInterventionnelle'));?> </th>
										</tr>
										<tr class="form-instrumental" style="width: 90%;">
											<th style="width: 95%;"> <?php echo $this->formRow($form->get('autresIntervention'));?> </th>
										</tr>
										<!-- tr style="width: 90%;">
                                            <th style="width: 100%; padding-right:30px;">
                                                <div style='margin-top:10px; float:right; '> 
                                                     <button id='bouton_instrumental_valider'>Valider</button>  
                                                </div >
                                                <div style='margin-top:10px; float:right; '> 
                                                     <button id='bouton_instrumental_modifier'>Modifier</button>  
                                                </div>
                                            </th>
                                          </tr-->
									</table>
									<!-- ******* -->
									<!-- ******* -->
								</div>

								<div id="tabsInstrumental-2">
									<!-- ******* -->
									<!-- ******* -->
									<input type='hidden' id='temoinAudio'>
									<table id="transfert" style="width: 100%;">
										<tr style="width: 100%;">
											<td style="width: 55%; vertical-align: top;">
												<div id="AfficherLecteurInstrumental"
													style='margin-right: 40px;'>
													<!-- ****** EMPLACEMENT DU LECTEUR AUDIO (MP3)********* -->
												</div>
											</td>
											<td class="form-transfert"
												style="width: 45%; vertical-align: top;"> 
                                              <?php echo $this->formRow($form->get('note_compte_rendu_operatoire_instrumental'));?> 
                                              <table style="width: 97%;">
													<tr style="width: 100%;">
														<td style="width: 100%; padding-right: 30px;">
															<div style='margin-top: 10px; float: right;'>
																<button id='bouton_compte_rendu_instrumental_valider'>Valider</button>
															</div>
															<div style='margin-top: 10px; float: right;'>
																<button id='bouton_compte_rendu_instrumental_modifier'>Modifier</button>
															</div>
														</td>
													</tr>
												</table>
											</td>
										</tr>
									</table>
									<!-- ******* -->
									<!-- ******* -->
								</div>



							</div>
							
						</div>


					</div>

				</div>
				
		<!-- ********************************Operation *******************************************-->
        
<div style='font-family: police2; font-size: 17px; font-weight: bold;'> Operation </div>
				<div style='max-height: 550px;'>

					<div id="accordionsss_operation">
						<!--******************* DEMANDE ************************-->
						<!--*******************DEMANDE ************************-->
						<div style='font-family: police2; font-size: 17px; font-weight: bold;'> Demande de visite
											pr&eacute;-anesth&eacute;sique </div> 
							
					 <div>
					 
					<div style="padding-bottom: 0px; margin-bottom: 5px; border-bottom: 2px solid green; margin-left: 0px;"></div>
					 
					 
					 <div style="padding-bottom: 40px; margin-bottom: 10px; border-bottom: 1px dashed green; margin-left: 0px; margin-right: 0px;"></div>
					 
					 
					 
									<table id="chirurgical" style="width: 100%;">
										<tr class="form-chirurgical" style="width: 100%;">
											<th style="width: 33%;"> <?php echo $this->formRow($form->get('diagnostic_traitement_chirurgical'));?> </th>
											<th style="width: 33%;"> <?php echo $this->formRow($form->get('observation'));?> </th>
											<th style="width: 33%;"> <?php echo $this->formRow($form->get('intervention_prevue'));?> </th>
										</tr>
										<tr class="form-chirurgical" style="width: 100%;">
											<th style="width: 33%;"></th>
											<th style="width: 33%;"></th>
											<th style="width: 33%; padding-right: 30px;">
												<div id="bouton_valider_chirurgical"
													style='margin-top: 30px; float: right;'>
													<button id='bouton_chirurgical_valider'>Valider</button>
												</div>
												<div id="bouton_modifier_chirurgical"
													style='margin-top: 30px; float: right;'>
													<button id='bouton_chirurgical_modifier'>Modifier</button>
												</div>
											</th>

										</tr>
									</table>
					 
					 
					 
				     </div>
				     
				    <div style='font-family: police2; font-size: 17px; font-weight: bold;'> Compte rendu
											op&eacute;ratoire </div> 
					 
					 <div>
					 
					 									<table id="transfert" style="width: 100%;">
										<tr style="width: 100%;">
											<td style="width: 55%; vertical-align: top;">
												<div id="AfficherLecteur"
													style='margin-right: 40px; vertical-align: top;'>
													<!-- ****** EMPLACEMENT DU LECTEUR AUDIO (MP3)********* -->
												</div>
											</td>
											<td class="form-transfert"
												style="width: 45%; vertical-align: top;">
												<div class="rendezvous"
													style='cursor: pointer; float: right; margin-top: 5px; margin-right: 40px;'>
													<hass> <input type="submit" title="Imprimer"
														name="protocole_operatoire" id="protocole_operatoire"> </hass>
												</div>
                             <?php echo $this->formRow($form->get('note_compte_rendu_operatoire'));?> 
                             <table style="width: 97%;">
													<tr style="width: 100%;">
														<td style="width: 100%; padding-right: 30px;">
															<div style='margin-top: 10px; float: right;'>
																<button id='bouton_compte_rendu_chirurgical_valider'>Valider</button>
															</div>
															<div style='margin-top: 10px; float: right;'>
																<button id='bouton_compte_rendu_chirurgical_modifier'>Modifier</button>
															</div>
														</td>
													</tr>
												</table>
											</td>

										</tr>
									</table>
					 
					 </div>
				      
				     <div style='font-family: police2; font-size: 17px; font-weight: bold;'> Surveillance </div>
				     
				      <div>
				      
				      <div id="tabsSurveillance">
						     <ul>
                                <li><a href="#tabs-periodePostop">P&eacute;riode Postop&eacute;ratoire precoce</a></li>
                                <li><a href="#tabs-histologie">Histologie</a></li>
                                <li><a href="#tabs-surveillanceTardive">P&eacute;riode Postop&eacute;ratoire tardive</a></li> 
                              </ul>
						   <div id="tabs-periodePostop">
						   </div>
					 </div>
				     </div>
				     
				     </div> 
				  	</div>  
				 


				<!-- *************Autres(Transfert/Hospitalisation/ Rendez-Vous )***************-->
				<!-- *************Autres(Transfert/Hospitalisation/ Rendez-Vous )***************-->
				<!-- *************Autres(Transfert/Hospitalisation/ Rendez-Vous )***************-->

				<!--*7*-->
				<div
					style='font-family: police2; font-size: 17px; font-weight: bold;'>Autres
					(Transfert / Hospitalisation / Rendez-Vous)</div>
				<div style="max-height: 480px;">


					<!--  **************** NOUVELLE ACCORDEON *********************  -->
					<!--  **************** NOUVELLE ACCORDEON *********************  -->
					<div id="accordionsssss">

						<!-- ************** Tranfert **************** -->
						<!-- **1** -->
						<div
							style='font-family: police2; font-size: 17px; font-weight: bold;'>
							Transfert</div>
						<div>

							<div
								style="padding-bottom: 0px; margin-bottom: 5px; border-bottom: 2px solid green; margin-left: 0px;"></div>
							<!-- LE PDF POUR IMPRESSION-->
							<div class="transf">
								<hass>
								<input type="submit" alt="Constantes" title="Imprimer"
									name="transfert" id="transfert"></hass>
							</div>
							<div class="annulertransfert">
								<hass>
								<input type="submit" alt="Constantes" title="Annuler"
									name="annulertransfert" id="annulertransfert"></hass>
							</div>
							<div
								style="padding-bottom: 40px; margin-bottom: 10px; border-bottom: 1px dashed green; margin-left: 0px; margin-right: 0px;"></div>
							<table id="transfert" style="width: 100%;">
								<tr class="form-transfert" style="width: 100%;">
									<th style="width: 45%;"><?php echo $this->formRow($form->get('motif_transfert'));?></th>

									<th class="form-transfert2" style="width: 27%;"><?php echo $this->formRow($form->get('hopital_accueil'));?></th>
									<th class="form-transfert2" style="width: 28%;"><?php echo $this->formRow($form->get('service_accueil'));?></th>
									<th><input type="hidden" id="hopital_accueil_tampon"
										name="hopital_accueil_tampon"> <input type="hidden"
										id="service_accueil_tampon" name="service_accueil_tampon"></th>
								</tr>

								<tr style="width: 100%;">
									<th></th>
									<th></th>
									<th
										style="float: right; height: 40px; margin-top: 20px; width: 80px;">
										<!-- On crï¿½e le bouton Valider (permettant la validation des donnï¿½es -->
										<div id="bouton_valider_transfert">
											<button id='bouton_transfert_valider'>Valider</button>
										</div> <!-- On crï¿½e le bouton MODIFIER (permettant la modification des donnï¿½es -->
										<div id="bouton_modifier_transfert">
											<button id='bouton_transfert_modifier'>Modifier</button>
										</div>
									</th>
								</tr>
							</table>

						</div>

						<!-- ************** Hospitalisation **************** -->
						<!-- **2** -->
						<div
							style='font-family: police2; font-size: 17px; font-weight: bold;'>
							Hospitalisation</div>
						<div style="max-height: 300px;">
							<div
								style="padding-bottom: 0px; margin-bottom: 5px; border-bottom: 2px solid green; margin-left: 0px;"></div>
							<!-- LE PDF POUR IMPRESSION-->
							<div class="rendezvous">
								<hass>
								<input type="submit" alt="Constantes" title="Imprimer"
									name="hospitalisation" id="hospitalisation"></hass>
							</div>
							<div class="annulerhospitalisation">
								<hass>
								<input type="submit" name="annulerhospitalisation"
									id="annulerhospitalisation"></hass>
							</div>
							<div
								style="padding-bottom: 40px; margin-bottom: 10px; border-bottom: 1px dashed green; margin-left: 0px; margin-right: 0px;"></div>

							<p style='color: white; opacity: 0.5;'>
								<img id=""
									src='<?php echo $this->basePath().'/images_icons/hospitalisation.jpg'?>'
									alt="consult-motif"
									style='float: right; margin-right: 10px; padding-top: 10px; width: 25%; height: 180px;' />
							</p>

							<table id="hospitalisation" style="width: 73%;">
								<tr>
									<th class="form-hospitalisation" style="width: 60%;"> <?php echo $this->formRow($form->get('motif_hospitalisation'));?> </th>
									<th class="form-hospitalisation_date_fin_prevue_hospi"
										style="width: 40%"> <?php echo $this->formRow($form->get('date_fin_hospitalisation_prevue'));?> </th>
								</tr>
							</table>

							<table style="width: 100%; margin-top: 20px;">
								<tr>
									<th style="width: 55%;"></th>
									<th style="width: 10%;">
										<!-- On crï¿½e le bouton Valider (permettant la validation des donnï¿½es -->
										<div id="bouton_valider_hospi">
											<button id='bouton_hospi_valider'>Valider</button>
										</div> <!-- On crï¿½e le bouton MODIFIER (permettant la modification des donnï¿½es -->
										<div id="bouton_modifier_hospi">
											<button id='bouton_hospi_modifier'>Modifier</button>
										</div>
									</th>
									<th style="width: 35%;"></th>
								</tr>
							</table>
						</div>


						<!-- ************** Rendez-vous **************** -->
						<!-- **3** -->
						<div
							style='font-family: police2; font-size: 17px; font-weight: bold;'>
							Rendez-vous</div>
						<div>

							<div
								style="padding-bottom: 0px; margin-bottom: 5px; border-bottom: 2px solid green; margin-left: 0px;"></div>
							<!-- LE PDF POUR IMPRESSION-->
							<div class="rendezvous">
								<hass>
								<input type="submit" alt="Constantes" title="Imprimer"
									name="rendezvous" id="disable"></hass>
							</div>

							<div class="annulerrendezvous">
								<hass>
								<input type="submit" alt="Constantes" title="Annuler"
									name="annulerrendezvous" id="annulerrendezvous"></hass>
							</div>
							<div
								style="padding-bottom: 40px; margin-bottom: 10px; border-bottom: 1px dashed green; margin-left: 0px; margin-right: 0px;"></div>

							<table id="rendezvous" style="width: 100%;">
								<tr class="form-rendezvous" style="width: 100%;">
									<th style="width: 46%;"> <?php echo $this->formRow($form->get('motif_rv'));?> </th>

									<th class="form-rendezvous2" style="width: 27%;"> <?php echo $this->formRow($form->get('date_rv')); ?> </th>
									<th class="form-rendezvous2" style="width: 17%;"> <?php echo $this->formRow($form->get('heure_rv'));?> </th>
									<th class="form-rendezvous2" style="width: 17%;"> <?php echo $this->formRow($form->get('delai_rv'));?> </th>
									<th style="width: 10%;">
									
									<th>
									
									<th><input type="hidden" id="date_rv_tampon"
										name="date_rv_tampon"> <input type="hidden"
										id="heure_rv_tampon" name="heure_rv_tampon"> <input
										type="hidden" id="delai_rv_tampon" name="delai_rv_tampon"></th>
								</tr>
								<tr style="width: 100%;">
									<th colspan='4'>
										<!-- On crï¿½e le bouton Valider (permettant la validation des donnï¿½es -->
										<div id="bouton_valider"
											style="float: right; height: 15px; margin-top: 20px;">
											<button id='enable_bouton'>Valider</button>
										</div> <!-- On crï¿½e le bouton MODIFIER (permettant la modification des donnï¿½es -->
										<div id="bouton"
											style="float: right; height: 15px; margin-top: 20px;">
											<button id='disable_bouton'>Modifier</button>
										</div>
									</th>
								</tr>
							</table>

						</div>
					</div>

				</div>
			</div>


			<table style="width: 100%; margin-top: 20px;">
				<tr>
					<td style="background-color: #eeeeee; height: 40px; width: 100%;">
						<p style="text-align: center;">
							<button id="annuler2"
								style="font-family: police2; font-size: 18px; font-weight: bold;">
								Annuler</button>
							<button name="terminer2" id="terminer2"
								style="font-family: police2; font-size: 18px; font-weight: bold;">
								Terminer</button>
						</p>
					</td>
				</tr>
			</table>

			<!-- POP UP pour Confirmation Annulation -->
			<div id="confirmation2" title="Confirmation de l'annulation"
				style="display: none;">
				<p style="font-size: 16px;">
					<span style="float: left; margin: 0 0px 20px 0;"> <img
						src="<?php echo $this->basePath().'/images_icons/warning_16.png';?>" />

						Etes-vous s&ucirc;r de vouloir annuler les modifications ?
					</span>
				</p>
			</div>

			<!-- POP UP pour Choix des sous-dossiers -->
			<div id="choix_sous_dossier" title="choisir des sous-dossiers"
				style="display: none;">
				<!-- INTERFACE DE GESTION DES CHOIX DES SOUS-DOSSIER -->

				<table style="width: 100%;" id="liste_choix_sous_dossier">
					<tr style="width: 100%; height: 30px;">
						<td style="width: 15%;"><input type="checkbox" name="fiche-observation"></td>
						<td style="width: 85%;" id='choix1'>Fiche d'Observation Clinique <span> </span>
						</td>
					</tr>

					<tr style="width: 100%; height: 30px;">
						<td style="width: 15%;"><input type="checkbox" name="tyroide">
						</td>
						<td style="width: 85%;" id='choix2'>Tyroide <span> </span>
						</td>
					</tr>

					<tr style="width: 100%; height: 30px;">
						<td style="width: 15%;"><input type="checkbox" name="otologie"></td>
						<td style="width: 85%;" id='choix3'>Tumeur Parotidienne <span> </span>
						</td>
					</tr>

					<tr style="width: 100%; height: 30px;">
						<td style="width: 15%;"><input type="checkbox" name="pharynx"></td>
						<td style="width: 85%;" id='choix4'>Corps Etrangers <span> </span>
						</td>
					</tr>

					<tr style="width: 100%; height: 30px;">
						<td style="width: 15%;"><input type="checkbox" name="larynx"></td>
						<td style="width: 85%;" id='choix5'>Lesions Sphere Orl <span> </span>
						</td>
					</tr>


				</table>


			</div>



    <?php echo $this->form()->closeTag();?>
</div>


		<form id="FormulaireUpdateComplementConsultation"
			style="display: none;">
			<button id="UpdateComplementConsultation"></button>
		</form>


		<script>
jsPagination();
sousDossier();
</script>
		<!-- SCRIPT LOURD -->
<?php echo $this->headScript()->appendFile($this->basePath().'/js/jquery.maskedinput.cons.js');?>
 