<script>
//POUR LE MENU GAUCHE dans -elementgauche.phtml
$('#plus_deces').toggle(true);
$("#deces").replaceWith("<li id='deces' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='<?php echo $this->basePath().'/images_icons/moin-green2.png'?>' alt='Liste' /> Consultations </span></a></li>");
dep_deces1();
$('#liste_recherche_style').css({'font-weight':'bold','color':'white','font-size':'22px'});

$(window).load(function () {

	$('#wait').toggle(false);
	$('#contenu, #titre').fadeIn().css({'visibility':'visible'});
	 
});
</script>

<!-- Mes CSS -->
<?php echo $this->headLink()->appendStylesheet($this->basePath().'/css/orl/styleListePatientRecherche.css');?>
<!-- MES JS -->
<?php 
echo $this->headScript()->appendFile($this->basePath().'/js/orl/jsListePatientRecherche.js');
$aujourdhui = (new \DateTime ( 'now' ))->format ( 'Y-m-d' );
?>

<style>
#contenu, #titre{ visibility: hidden; }
</style>

<script>
$(window).load(function () {
	$('#wait').toggle(false);
	$('#contenu, #titre').fadeIn().css({'visibility':'visible'});
});
affichervue('<?php echo $this->id_patient ?>');
</script>

<div id="titre" style='font-family: police2; color: green; font-size: 20px; font-weight: bold; padding-left:20px;'><i style='font-size: 25px;'>&curren; </i>INFO PATIENT RECHERCHE </div>
<div id="wait" style="color: gray; font-size: 20px; text-align: center; margin-top: 80px;" > <span> Chargement ... </span> </div>
<div id="contenu" >

  <div id="vue_patient"> </div>
  <div id="titre_info_admis"> Liste des consultations pr&eacute;c&eacute;dentes </div>
  <div id="barre_separateur"></div>
		  

  <div id="contenu_tab" style="margin-left: 18%; margin-top:8px;">
  
     <table class="table table-bordered  tab_list_mini" id="patient">
        <thead>
	        <tr style="height:25px; width: 100%;">
				    
		 			<th id="nom" align="center">Dossier</th>
					<th id="prenom" align="center">Date ouverture</th>
					<th id="date" align="center" name="date">Nb notes m&eacute;dicales</th>
					<th id="sexe" align="center" name="sexe">Option</th>
					
		    </tr>
        </thead>
	    <tbody>
			
	    </tbody>
	 
     </table>
	
	 <input type="hidden" id="id_patient">
		 
  </div>		  
		
</div>


<script>
$('#id_patient').val('<?php echo $this->id_patient ?>');
initialisation();
</script>