<!-- MES STYLES -->
<?php echo $this->headLink()->appendStylesheet($this->basePath().'/css/pharmacie/styleAjouterMedicament.css');?>

<!-- MES JS -->
<?php echo $this->headScript()->appendFile($this->basePath().'/js/pharmacie/jsAjouterMedicament.js');?>


<!-- TITRE EN TETE DE LA PAGE -->
<div id="titre" style='font-family: police2; text-decoration:none; color: #48883e; font-size: 20px; font-weight: bold;'><iS style='font-size: 25px;'>&curren;</iS> AJOUTER LE MEDICAMENT
  <!-- div id="pharmacie_logo"></div-->
</div>

<!-- CONTENU AJOUT D'UN MEDICAMENT -->
<div id="contenu" >

   <div  style="width:200px;float:left; margin-right:10px">
        <div id="image" class="image">
           <input type='file' name="fichier" /> <!-- RECUPERER L'IMAGE -->
           <input type='hidden' id="fichier_tmp" name="fichier_tmp" /> <!-- FICHIER TAMPON POUR RECUPERER L'IMAGE DANS LE CONTROLLER -->
        </div>

        <div class="supprimer_photo" id="div_supprimer_photo">
        </div>
   </div>

   <div style="float:right;">
   <?php $form = $this->form;
     $this->form->prepare();
    echo $this->form()->openTag($form); ?>
   <table>
     <tr id="form_medicament">
        <td class="comment-form-medicament"><?php echo $this->formRow($form->get('intitule')); ?></td>
        <td class="comment-form-medicament"><?php echo $this->formRow($form->get('indication_therapeutique')); ?></td>
        <td class="comment-form-medicament"><?php echo $this->formRow($form->get('mise_en_garde')); ?></td>
     </tr>

     <tr id="form_medicament">
        <td class="comment-form-medicament"><?php echo $this->formRow($form-> get('composition')); ?></td>
        <td class="comment-form-medicament"><?php echo $this->formRow($form->get('excipient_notoire')); ?></td>
        <td class="comment-form-medicament"><?php echo $this->formRow($form->get('voie_administration')); ?></td>
     </tr>

     <tr id="form_medicament">
        <td class="comment-form-medicament" ><?php echo $this->formRow($form->get('adresse_fabricant')); ?></td>
        <td class="comment-form-medicament" ><?php echo $this->formRow($form->get('description')); ?></td>
        <td rowspan="2"> <div id="pharmacie_logo_2"> </div></td>
     </tr>

     <tr>
        <td> </td>
        <td>
           <div class='block' id='thoughtbot' style='display: inline-block;  vertical-align: bottom; padding-left:0px; padding-top: 25px;'><button type='submit' id='annulerMedicament'>Annuler</button></div>
           <div class='block2' id='thoughtbot' style='display: inline-block;  vertical-align: bottom; padding-left:0px; padding-top: 25px;'><button type='submit' id='terminerMedicament'>Terminer</button></div>
        </td>
     </tr>
   </table>
   <?php echo $this->form()->closeTag()?>
  </div>

<!--***********************************************************************************************-->

<!--==========================POP UP pour Confirmation Suppression=================================-->

<!--***********************************************************************************************-->
        <div id="confirmation" title="Confirmation de la suppression" style="display:none;">
             <p style="font-size: 16px;">
                 <span style="float:left; margin:0 0px 20px 0; font-size:17px; ">
                 <img src="<?php echo $this->basePath().'/images_icons/warning_16.png';?>" />

                 Etes-vous s&ucirc;r de vouloir supprimer l'image ?</span>
             </p>
         </div>



<script>
AjouterMedicament();
$(".supprimer_photo").toggle(false);
</script>
</div>










<script>
//POUR LE MENU GAUCHE dans -elementgauche.phtml
$('#plus_dossier_patient').toggle(true);
$("#dossier_patient").replaceWith("<li id='dossier_patient' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:18px; font-family:Times New Roman;'> <img style='display: inline;' src='/simens/public/images_icons/moins-vert.PNG' alt='Liste' /> M&eacute;dicaments </span></a></li>");
dep_dossier_patient1();
$('#nouveau_style').css({'font-weight':'bold','color':'white','font-size':'22px'});
</script>