
<!-- MES STYLES --> 
<?php 
echo $this->headLink()->appendStylesheet($this->basepath().'/css/consultation/styleModifierPassword.css');
echo $this->headScript ()->appendFile ( $this->basePath () . '/js/consultation/jsModifierPassword.js' );

echo $this->headLink()->appendStylesheet($this->basepath().'/js/plugins/passwordStrength/css/style.css');
echo $this->headScript ()->appendFile ( $this->basePath ().'/js/plugins/passwordStrength/js/mocha.js' );
?>

<script type="text/javascript">
$(window).load(function () {
	$('#wait').toggle(false);
	$('#contenuInterface').fadeIn().css({'visibility':'visible'});
});
</script>

<style>
#contenuInterface{ visibility: hidden };
</style>


<div id="titre" style='font-family: police2; text-decoration: none; color: green; font-size: 20px; font-weight: bold; padding-left:20px;'>
	<iS style='font-size: 25px;'>&curren;</iS>
	MODIFICATION DES INFORMATIONS
</div>


<div id="wait" style="color: gray; font-size: 20px; text-align: center; margin-top: 80px;" > <span> Chargement ... </span> </div>

<div id="contenuInterface"> 

<div id="contenu">

	<div style='width: 100%;'>
    
    <!-- Ajouter une photo -->
    <!-- Ajouter une photo -->
	<div style='width: 15%; height: 150px; float:left; margin-left: 30px;'>
	<div class="photo_patient" id='photo'>
		<input type='file' name="fichier" />
		<!-- RECUPERER L'IMAGE -->
		<input type='hidden' id="fichier_tmp" name="fichier_tmp" />
		<!-- FICHIER TAMPON POUR RECUPERER L'IMAGE DANS LE CONTROLLER -->
	</div>
    </div>

    
    <!-- Formulaire de saisie des donnees a modifier -->
    <!-- Formulaire de saisie des donnees a modifier -->
    <div style='width: 80%; height: 150px; float:left;'>
	<div id="FormUtilisateur">

    <?php
    $controller = $this->controller;
    $form = $this->formUtilisateur;
    $form->setAttribute ( 'action', $this->url ( 'admin', array ('action' => 'modifier-password', 'id' => $controller) ));
    $form->prepare ();
    echo $this->form ()->openTag ( $form );
    ?>
    <?php echo $this->formhidden($form->get('id')); ?>

    <table id="form_patient" style="margin-left: 50px; width: 95%;">  
      
      <tr  style="width: 90%;">
         <td class="comment-form-patient"  style="width: 33%;"> <?php echo $this->formRow($form->get('nomUtilisateur'));?></td> 
         <td class="comment-form-patient"  style="width: 33%;"> <?php echo $this->formRow($form->get('prenomUtilisateur'));?></td> 
         <td style="width: 33%; padding-left: 20px; vertical-align: top;" rowspan="3"> 
             <div style="width: 75%;">
               <a id="raffraichirChamp" href="javascript:raffraichirChamp()" style="display: inline; padding-right: 5px;" >
				   <img  style="width: 27px; height: 27px;" src='<?php echo $this->basePath().'/images_icons/72.png'?>' title="Retour" />
			   </a>
               <a class="viderChamp" href="javascript:viderChamp()" style="display: inline; padding-right: 5px;" >
				   <img  id="viderChamp" src='<?php echo $this->basePath().'/images_icons/9.png'?>' title="Vider les champs" />
			   </a>
               <a class="modifierChamp" href="javascript:modifierChamp()" style="display: inline;" >
				   <img id="modifierChamp" src='<?php echo $this->basePath().'/images_icons/2.png'?>' title="modifier" />
			   </a>
			   <div style="width:100%; background: #cccccc; height:2px; margin-top: 5px; margin-bottom: 15px;"></div>
			 </div>
             <div class="comment-form-patien" ><label> </label></div> 
             <div style="border-top-right-radius: 15px; width: 75%; height: 100%; background: #f5f5f5; padding-left: 10px;"> 
             </div>
         </td> 
      </tr>
      
      <tr class="comment-form-patient"  style="width: 80%;">
         <td style="width: 33%; vertical-align: top;"> <?php echo $this->formRow($form->get('username'));?></td> 
         <td style="width: 33%; vertical-align: top;"> <?php echo $this->formRow($form->get('password'));?><span id="message_password" style="font-family: time new roman; position: relative; top: -15px; color:red; "><i> mot de passe incorrect ..</i> </span></td>
      </tr>
      
      <tr class="comment-form-patient"  style="width: 80%;">
         <td class="block" style="width: 33%; vertical-align: top;"> <?php echo $this->formRow($form->get('nouveaupassword'));?> <div id="complexity" class="default"></div> </td> 
         <td style="width: 33%; vertical-align: top;"> <?php echo $this->formRow($form->get('confirmerpassword'));?> <span id="message_confirmer_password" style="font-family: time new roman; position: relative; top: -15px; color:red; "><i> mot de passe incorrect ..</i> </span> </td>
      </tr>
      
       <tr class="comment-form-patient" style="width: 80%;">
         <td style="width: 33%; vertical-align: top;"> <?php echo $this->formRow($form->get('service'));?></td> 
         <td style="width: 33%; vertical-align: top;"> <?php echo $this->formRow($form->get('fonction'));?></td> 
      </tr>
      
    </table>
    
    <table id="form_patient" style="margin-left: 50px; width: 95%;">
      <tr class="comment-form-patient" style=" width: 80%; height: 75px; vertical-align: bottom;">
         <td style="width: 33%; padding-left: 21%; "> 
            <?php echo $this->formSubmit($form->get('annuler')); ?>
            <?php echo $this->formSubmit($form->get('enregistrer')); ?>
         </td> 
      </tr>
    </table>

    <?php echo $this->form()->closeTag();?>
    
    <div id="scriptFormUtilisation">
    </div>
  
   </div>
		
		<!-- div class="supprimer_photo" id="div_supprimer_photo">
			<hass> <input name="supprimer_photo"> </hass>
		</div-->
		
   </div>
      
   </div>
</div>

</div>

<!-- POP UP pour Confirmation Suppression -->
<div id="confirmation" title="Confirmation de la suppression"
	style="display: none;">
	<p style="font-size: 16px;">
		<span style="float: left; margin: 0 0px 20px 0;"> <img
			src="<?php echo $this->basePath().'/images_icons/warning_16.png';?>" />

			Etes-vous s&ucirc;r de vouloir supprimer la photo ?
		</span>
	</p>
</div>

<script>
var ancienUsername = $('#username').val();
var nomUser = $('#nomUtilisateur').val();
var prenomUser = $('#prenomUtilisateur').val();


//raffraichir les champs
//raffraichir les champs
//raffraichir les champs
$('#raffraichirChamp').toggle(false);
function raffraichirChamp(){
	$('#nomUtilisateur').val(nomUser);
	$('#prenomUtilisateur').val(prenomUser);
	$('#username').val(ancienUsername);
	$('#raffraichirChamp').fadeOut();
}


//ON CACHE LE MENU GAUCHE
//ON CACHE LE MENU GAUCHE
//ON CACHE LE MENU GAUCHE
$("#sidebar").toggle(false);

//EMPECHER LA TOUCHE ENTREE DE SOUMETTRE LE FORMULAIRE 
//EMPECHER LA TOUCHE ENTREE DE SOUMETTRE LE FORMULAIRE 
//EMPECHER LA TOUCHE ENTREE DE SOUMETTRE LE FORMULAIRE 
$("table tr td input").keypress(function(event) {
	  if (event.keyCode == 13) {
		  return false;
	  }
});    

$('#service').attr('disabled', true);
$('#fonction').attr('disabled', true);

var indice = 0;
$('#nomUtilisateur').attr('readonly', true);
$('#prenomUtilisateur').attr('readonly', true);
$('#username').attr('readonly', true);

$(".modifierChamp").click(function(){
	if(indice == 0){
		$('#nomUtilisateur').attr('readonly', false);
		$('#prenomUtilisateur').attr('readonly', false);
		$('#username').attr('readonly', false);
		indice = 1;
		$('.viderChamp').html("<img  id='viderChamp' src='<?php echo $this->basePath().'/images_icons/9.png'?>' title='Vider les champs' />");
		$('.modifierChamp').html("<img style='opacity: 0.3; color: white;'  id='viderChamp' src='<?php echo $this->basePath().'/images_icons/2.png'?>' />");
		
	} else {
		$('#nomUtilisateur').attr('readonly', true);
		$('#prenomUtilisateur').attr('readonly', true);
		$('#username').attr('readonly', true);
		indice = 0;
	}
});

$('.viderChamp').html("<img style='opacity: 0.3; color: white;'  id='viderChamp' src='<?php echo $this->basePath().'/images_icons/9.png'?>' />");
$(".viderChamp").click(function(){
	if(indice == 1){
		$('#raffraichirChamp').toggle(true);
		$('#nomUtilisateur').val('');
		$('#prenomUtilisateur').val('');
		$('#username').val('');

		$('.viderChamp').html("<img style='opacity: 0.3; color: white;'  id='viderChamp' src='<?php echo $this->basePath().'/images_icons/9.png'?>' />");
		$('.modifierChamp').html("<img  id='viderChamp' src='<?php echo $this->basePath().'/images_icons/2.png'?>' title='modifier' />");
	}
});
    
var base_url = window.location.toString();
var tabUrl = base_url.split("public");

$("#annuler").click(function(){
	if(<?php echo $this->controller;?> == 1){
		vart=tabUrl[0]+'public/consultation/protocole-operatoire';
        $(location).attr("href",vart);
        return false;
	}else
		if(<?php echo $this->controller;?> == 2){
			vart=tabUrl[0]+'public/consultation/recherche';
	        $(location).attr("href",vart);
	        return false;
		}else
			if(<?php echo $this->controller;?> == 3){
				vart=tabUrl[0]+'public/facturation/liste-patient';
		        $(location).attr("href",vart);
		        return false;
			}else
				if(<?php echo $this->controller;?> == 4){
					vart=tabUrl[0]+'public/hospitalisation/suivi-patient';
			        $(location).attr("href",vart);
			        return false;
				}else
					if(<?php echo $this->controller;?> == 5){
						vart=tabUrl[0]+'public/hospitalisation/liste-demandes-examens';
				        $(location).attr("href",vart);
				        return false;
					}else 
						if(<?php echo $this->controller;?> == 6){
							vart=tabUrl[0]+'public/hospitalisation/liste-demandes-examens-morpho';
							$(location).attr("href",vart);
							return false;
						}else 
							if(<?php echo $this->controller;?> == 7){
								vart=tabUrl[0]+'public/hospitalisation/liste-demandes-vpa';
								$(location).attr("href",vart);
								return false;
							}else
								if(<?php echo $this->controller;?> == 8){
									vart=tabUrl[0]+'public/hospitalisation/demande-hospitalisation';
									$(location).attr("href",vart);
									return false;
								}else
									if(<?php echo $this->controller;?> == 9){
										vart=tabUrl[0]+'public/facturation/liste-naissance';
										$(location).attr("href",vart);
										return false;
									}else
										if(<?php echo $this->controller;?> == 10){
											vart=tabUrl[0]+'public/personnel/liste-personnel';
											$(location).attr("href",vart);
											return false;
										}else
											if(<?php echo $this->controller;?> == 11){
												vart=tabUrl[0]+'public/facturation/admission-bloc';
												$(location).attr("href",vart);
												return false;
											}else 
												if(<?php echo $this->controller;?> == 12){
													vart=tabUrl[0]+'public/archivage/liste-dossiers-patients';
													$(location).attr("href",vart);
													return false;
												}else 
													if(<?php echo $this->controller;?> == 13){
														vart=tabUrl[0]+'public/secretariat/liste-patient';
														$(location).attr("href",vart);
														return false;
													}
	
	stopPropagation();
});


$("#enregistrer").click(function(){
	if($('#username').val() == '' || $('#password').val() == '' || $('#nouveaupassword').val() == '' || $('#confirmerpassword').val() == ''){
		return true;
	} else if(ancienUsername == $('#username').val()){
		return true;
	} else {
		var chemin = tabUrl[0]+'public/admin/mise-a-jour-user-password';
		$.ajax({
			 type: 'POST',
	         url: chemin ,
	         data:{'nouveauUsername':$('#username').val(), 'ancienUsername':ancienUsername, 'nouveaupassword':$('#nouveaupassword').val()},
	         success: function(data) {    
		         	vart=tabUrl[0]+'public/admin/logout';
					$(location).attr("href",vart);
	         	    return false;    
	         },
	         error:function(e){console.log(e);alert("Une erreur interne est survenue!");},
	         dataType: "html"
		});
	}
	return false;
});

//MOT DE PASSE ACTUEL
//MOT DE PASSE ACTUEL
//MOT DE PASSE ACTUEL
$("#message_password").toggle(false);
$('#password').blur(function(){
	
	var cle = $("#id").val();
	var password = $("#password").val();
	var chemin = tabUrl[0]+'public/admin/verifier-password';
	$.ajax({
		 type: 'POST',
         url: chemin ,
         data: $(this).serialize(),  
         data:{'id':cle, 'password': password},
         success: function(data) {    
         	    var result = jQuery.parseJSON(data);  
         	    if(result == 0){
         	    	$("#password").val('');
         	    	$("#password").css("border-color","#FF0000");
         	    	$("#message_password").toggle(true);
             	} else 
             		if(result == 1){
             	    	$("#password").css("border-color","#CCCCCC");
             	    	$("#message_password").toggle(false);
                 	}
         	   return false;    
         },
         error:function(e){console.log(e);alert("Une erreur interne est survenue!");},
         dataType: "html"
	});
});

$("#message_confirmer_password").toggle(false);
$('#confirmerpassword').blur(function(){
	var nouveaupassword = $("#nouveaupassword").val(); 
	var confirmerpassword = $("#confirmerpassword").val();
	if ( nouveaupassword != confirmerpassword ) {
		$("#confirmerpassword").val('');
		$("#confirmerpassword").css("border-color","#FF0000");
    	$("#message_confirmer_password").toggle(true);
	} else {
		$("#confirmerpassword").css("border-color","#CCCCCC");
    	$("#message_confirmer_password").toggle(false);
	}
});

//SI l'actuel password n'est pas saisi vider le champ nouveaupassword
$('#nouveaupassword').blur(function(){
	var password = $("#password").val();
	if ( password == "" ) {
		$("#nouveaupassword").val('');
		$("#password").val('');
    	$("#password").css("border-color","#FF0000");
    	$("#message_password").toggle(true);
    	$("#complexity").toggle(false);
	}
});

$('#password').keyup(function(){
	$("#nouveaupassword").val('');
	$("#confirmerpassword").val('');
	$("#complexity").toggle(false);
});

//GESTION DU MESSAGE password strength
//GESTION DU MESSAGE password strength
//GESTION DU MESSAGE password strength
$("#complexity").toggle(false);
$('#nouveaupassword').keyup(function(){
	$("#complexity").toggle(true);
	$("#confirmerpassword").val('');
});
</script>