<!-- MES STYLES --> 
<?php echo $this->headLink()->appendStylesheet($this->basepath().'/css/admin/styleParametrages.css'); ?>
<!-- MES JS -->
<?php echo $this->headScript()->appendFile($this->basepath().'/js/admin/jsParametrages.js'); ?>


<style>
  #toutLeContenu{ visibility: hidden; }
</style>


<div id="titre" style='font-family: police2; text-decoration: none; color: green; font-size: 20px; font-weight: bold; padding-left:20px;'>
	<iS style='font-size: 25px;'>&curren;</iS>
	PARAM&Eacute;TRAGES
</div>

<div id="wait" style="color: gray; font-size: 20px; text-align: center; margin-top: 80px;" > <span> Chargement ... </span> </div>

<div id="toutLeContenu"> 

<div id="contenu"> 
            
     <table style="width: 100%;">
				
	    <!-- ************************************  LA PREMIERE LIGNE  ******************************************* -->
	    <!-- ************************************  LA PREMIERE LIGNE  ******************************************* -->
	    <!-- ************************************  LA PREMIERE LIGNE  ******************************************* -->
	    <!-- ************************************  LA PREMIERE LIGNE  ******************************************* -->
		<tr style="width: 100%; background: white;">
		   
		   <td style="width: 25%; vertical-align: top;">
		   
		    <div style='width: 90%; margin: auto;'>
		      <table style="width: 100%;" class="table table-bordered tab_list_mini" >
		          <tr>
		             <th><img src='/simens/public/images_icons/Table16X16.png' /> H&ocirc;pitaux </th>
		          </tr>
		          
		          <tr> 
		             <td> 
		                <section> effectifs: 23 h&ocirc;pitaux </section>
		                <label></label> 
		                <section> nb bat|Moy: 5 batiments </section>
		                <label></label> 
		                <section><i id='ajouterHopitaux' >Ajouter <img src='/simens/public/images_icons/Add14X14.png' /></i></section>
		                
		             </td>
		          </tr>
		       </table>
		    </div>
		   
		   </td>
		   
		   
		   <td style="width: 25%; vertical-align: top;">
		     
		     <div style='width: 90%;  margin: auto;'>
		       <table style="width: 100%;" class="table table-bordered tab_list_mini" >
		          <tr>
		             <th><img src='/simens/public/images_icons/Table16X16.png' /> Batiments </th>
		          </tr>
		          
		          <tr>
		             <td> 
		                 <section> effectifs: 23 batiments </section>
		                 <label></label> 
		                 <section> nb sal|Moy: 6 salles </section>
		                 <label></label> 
		                 <section><i>Ajouter <img src='/simens/public/images_icons/Add14X14.png' /></i></section>
		                 
		             </td>
		          </tr>
		       </table>
		     </div>
		     
		   </td>
		   
		   
		   <td style="width: 25%; vertical-align: top;">
		   
		    <div style='width: 90%;  margin: auto;'>
		      <table style="width: 100%;" class="table table-bordered tab_list_mini" >
		          <tr>
		             <th><img src='/simens/public/images_icons/Table16X16.png' /> Salles </th>
		          </tr>
		          
		          <tr>
		             <td> 
		                <section> effectifs: 23 salles </section> 
		                <label></label> 
		                <section> nb lit|Moy: 8 lits </section>
		                <label></label> 
		                <section><i>Ajouter <img src='/simens/public/images_icons/Add14X14.png' /></i></section>   
		             </td>
		          </tr>
		       </table>
		     </div>
		     
		   </td>
		   
		   
		   <td style="width: 25%; vertical-align: top;">
		   
		    <div style='width: 90%; margin: auto;'>
		      <table style="width: 100%;" class="table table-bordered tab_list_mini" >
		          <tr>
		             <th><img src='/simens/public/images_icons/Table16X16.png' /> Lits </th>
		          </tr>
		          
		          <tr>
		             <td> 
		                <section> effectifs: 23 lits </section>
		                <label></label>
		                <!-- section> nb lits|dispo: 3 lit(s) </section>
		                <label></label--> 
		                <section> nb lits|occup&eacute;s: 8 lit(s) </section>
		                <label></label> 
		                <!-- section> nb lits|indispo: 6 lit(s) </section>
		                <label></label-->
		                <section><i>Ajouter <img src='/simens/public/images_icons/Add14X14.png'/></i></section>
		             </td>
		          </tr>
		       </table>
		    </div>
		   
		   </td>
		   
		</tr>
		
		<!-- ************************************  LA DEUXIEME LIGNE  ******************************************* -->
		<!-- ************************************  LA DEUXIEME LIGNE  ******************************************* -->
		<!-- ************************************  LA DEUXIEME LIGNE  ******************************************* -->
		<!-- ************************************  LA DEUXIEME LIGNE  ******************************************* -->
		<tr style="width: 100%; background: white; ">
		   <td colspan='4'> <label style='border: 1px solid #cccccc; width: 98%; margin:auto; margin-bottom: 10px; '> </label></td>
		</tr>
		
		<tr style="width: 100%; background: white;">
		
		   <td style="width: 25%; vertical-align: top;">
		   
		    <div style='width: 90%;  margin: auto;'>
		      <table style="width: 100%;" class="table table-bordered tab_list_mini" >
		          <tr>
		             <th><img src='/simens/public/images_icons/Table16X16.png' /> Services </th>
		          </tr>
		          
		          <tr>
		             <td> 
		                <section> effectifs: 23 services </section> 
		                <label></label> 
		                <section> 3 types </section>
		                <label></label> 
		                <section><i id='ajouterServices' >Ajouter <img src='/simens/public/images_icons/Add14X14.png' /></i></section>   
		             </td>
		          </tr>
		       </table>
		     </div>
		   
		   </td>
		   
		   <td style="width: 25%; vertical-align: top;">
		   
		    <div style='width: 90%;  margin: auto;'>
		      <table style="width: 100%;" class="table table-bordered tab_list_mini" >
		          <tr>
		             <th><img src='/simens/public/images_icons/Table16X16.png' /> Actes </th>
		          </tr>
		          
		          <tr>
		             <td> 
		                <section> nombres: 23 actes </section> 
		                <label></label> 
		                <section> 0 type </section>
		                <label></label> 
		                <section><i id='ajouterActes' >Actes <img src='/simens/public/images_icons/Add14X14.png' /></i></section>   
		             </td>
		          </tr>
		       </table>
		     </div>
		   
		   </td>
		   
		   <td style="width: 25%; vertical-align: top;">
		   
		    <div style='width: 90%;  margin: auto;'>
		      <table style="width: 100%;" class="table table-bordered tab_list_mini" >
		          <tr>
		             <th><img src='/simens/public/images_icons/Table16X16.png' /> Examens </th>
		          </tr>
		          
		          <tr>
		             <td> 
		                <section> nombres: 23 examens </section> 
		                <label></label> 
		                <section> 2 types </section>
		                <label></label> 
		                <section><i id='ajouterExamens' >Examens <img src='/simens/public/images_icons/Add14X14.png' /></i></section>   
		             </td>
		          </tr>
		       </table>
		     </div>
		   
		   </td>
		</tr>

	 </table>
	 
</div>

<div id="contenuTable">

</div>

</div>

<script> 
 $(window).load(function () {
	$('#wait').toggle(false);
	$('#toutLeContenu').fadeIn().css({'visibility':'visible'});
 });
 

 
 ajouterDonneesParametrages();
 $('#contenuTable').toggle(false);
</script>
