
<!-- MES STYLES --> 
<?php echo $this->headLink()->appendStylesheet($this->basepath().'/css/personnel/styleTransfertPersonnel.css');
      echo $this->headLink()->appendStylesheet($this->basepath().'/css/facturation/DatePicker.css'); //DatePicker?>

<!-- MES JS -->
<?php echo $this->headScript()->appendFile($this->basepath().'/js/personnel/jsTransfertPersonnel.js');?>

<?php 
$formTypePersonnel = $this->formTypePersonnel;
$formTransfertPersonnel = $this->formTransfertPersonnel;
?>
     <div id="titre" style='font-family: police2; text-decoration:NONE; color: green; font-size: 20px; font-weight: bold; padding-left: 35px;'><iS style='font-size: 25px;'>&curren;</iS> LE PERSONNEL</div>
     <div id="contenu" >
     
     <div id="liste_personnel" style="float:right; margin-right: 35px; height:5px; margin-top: 5px; width: 150px;"> 
          <?php echo $this->formrow($formTypePersonnel->get('type_personnel'));?> 
        </div>
     
		<table style='width:95%; margin-left: 10px; align:center' class="table table-bordered tab_list_mini" id="personnel">
			<thead>
			   <tr style='width: 100%;'>
				    <th id="idpatient_" style='width: 7%;'><input type="text" value="ID_Pat" class="search_init" /></th>
					<th id="nom_" style='width: 15%;'><input type="text" name="search_browser" value=" Nom" class="search_init" /></th>
					<th id="prenom_" style='width: 20%;'><input type="text" name="search_browser" value=" Pr&eacute;nom" class="search_init" /></th>
					<th id="date_" style='width: 13%;'><input type="text" name="search_browser" value=" Date naissance" class="search_init" /></th>
					<th id="adresse_" style='width: 40%;'><input type="text" name="search_browser" value=" Adresse" class="search_init" /></th>
					<th id="effectuer_" style='width: 5%;'><input type="hidden" name="search_browser" value="" class="" />Options</th>
				</tr>
			</thead>

			<tbody id="donnees" class="liste_patient">			
			        <!-- AFFICHAGE DES DONNEES -->
			</tbody>

		</table>
		
<script type="text/javascript">
initialisation();	
</script>		
</div>		 

<!-- POP UP pour Information -->
                            <div id="confirmation" title="Informations" style="display:none;">
                              <div id="info" style="font-size: 16px;">
                              
                              </div>
                            </div>
<!-- LES BOUTONS "TERMINER" ou "VALIDER" -->



<!-- PARTIE ENREGISTREMENT DE LA NAISSANCE -->
    <?php 
    $formTransfertPersonnel->setAttribute ( 'action', $this->url ( 'personnel', array ('action' => 'transfert') ) );
    $formTransfertPersonnel->prepare();
    echo $this->form()->openTag($formTransfertPersonnel);
    ?>
    <?php echo $this->formhidden($formTransfertPersonnel->get('id_personne'));?> 
    <?php echo $this->formhidden($formTransfertPersonnel->get('id_verif'));?> 
    
    <div id="ajouter_naissance">
          <a href="" id="precedent" style="font-family: police2; width:50px; margin-left:30px;">  
	        <img style="display: inline; " src='<?php echo $this->basepath().'/images_icons/transfert_gauche.PNG'?>' alt='Constantes' title="Rechercher" />
		    Pr&eacute;c&eacute;dent
		  </a>
		  
		  <div id="info_personnel">     
		  </div>
		  
		  <div id="barre_separateur">
		  </div>
		  
		  <div id="info_bebe">
              
		       <table id="form_patient" style="float: left; margin-left: 30px;">  
                    <tr class="comment-form-patient">
                        <td style="width: 270px;"> <?php echo $this->formrow($formTransfertPersonnel->get('type_transfert'));?></td> 
                    </tr>
               </table>
               
               <div class="vider_formulaire" id="vider_champ_interne">
                     <input title="Vider tout" name="vider" id="vider"> 
               </div>
               
               <div class="vider_formulaire" id="vider_champ_externe">
                     <input title="Vider tout" name="vider" id="vider"> 
               </div>
               <div id="barre_separateur2">
		       </div>
		       <!--  *************************************************************************
		             =========================== TRANSFERT INTERNE =========================-->
		       <table id="form_patient" class="transfert_interne" style=" float:left; margin-top:10px; margin-left: 30px;">
		             
		             <tr style="display: inline-block;  vertical-align: top;">
		                 <td class="comment-form-patient"><?php echo $this->formrow($formTransfertPersonnel->get('service_origine'));?></td>
		                 <td class="comment-form-patient"><?php echo $this->formrow($formTransfertPersonnel->get('service_accueil')); ?></td>
		                 <td class="comment-form-patient"><?php echo $this->formrow($formTransfertPersonnel->get('motif_transfert')); ?></td>
		                 <td class="comment-form-patient"><?php echo $this->formrow($formTransfertPersonnel->get('note')); ?></td>
		             </tr>
		             
	           </table>	
	           
	           <!--  *************************************************************************
		             =========================== TRANSFERT EXTERNE =========================-->
		       <table id="form_patient" class="transfert_externe" style=" float:left; margin-top:10px; margin-left: 30px;">
		             
		             <tr style="display: inline-block;  vertical-align: top;">
		                 <td class="comment-form-patient"><?php echo $this->formrow($formTransfertPersonnel->get('service_origine_externe'));?></td>
		                 <td class="comment-form-patient"><?php echo $this->formrow($formTransfertPersonnel->get('hopital_accueil'));?></td>
		                 <td class="comment-form-patient"><?php echo $this->formrow($formTransfertPersonnel->get('service_accueil_externe'));?></td>
		                 <td class="comment-form-patient"><?php echo $this->formrow($formTransfertPersonnel->get('motif_transfert_externe'));?></td>
		             </tr>
		             
	           </table>	
               
               <div id="terminer_annuler" style="padding-top: 5px;">
                    <div class="block" id="thoughtbot">
                       <button type="submit" id="terminer" style=" height:35px; ">Terminer</button>
                    </div>
                    
                    <div class="block" id="thoughtbot">
                       <button id="annuler" style=" height:35px; ">Annuler</button>
                    </div>
               </div>
		       
		  </div>
      
    </div>
    <?php echo $this->form()->closeTag(); ?>
    
<script>
animation();
/*****TRANSFERT INTERNE******/
 $(".transfert_externe").toggle(false);
 $("#vider_champ_externe").toggle(false);

 $("#service_accueil").attr({'required': true});
 $("#motif_transfert").attr({'required': true});
 $("#service_accueil_externe").attr({'required': false});
 $("#motif_transfert_externe").attr({'required': false});
 
$("#vider_champ_interne").click(function(){
	$('#service_accueil').val("");
	$('#motif_transfert').val("");
	$('#note').val("");
});

/**************************************************/
/*************** TRANSFERT INTERNE ****************/
  $('#service_origine').val("");
  $('#service_accueil').val("");

/**************************************************/
/*************** TRANSFERT EXTERNE ****************/
  $('#hopital_accueil').val("");
  $('#service_origine_externe').val("");
  $('#service_accueil_externe').val("");

//POUR LE MENU GAUCHE dans -elementgauche.phtml
$('#plus_operation').toggle(true); 
$("#operation").replaceWith("<li id='operation' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:18px; font-family:Times New Roman;'> <img style='display: inline;' src='/simens/public/images_icons/moins-vert.PNG' alt='Liste' /> Op&eacute;rations </span></a></li>");
dep1();
$('#recherche_style').css({'font-weight':'bold','color':'white','font-size':'22px'});
</script>
