<!-- MES STYLES -->
<?php echo $this->headLink()->appendStylesheet($this->basePath().'/css/facturation/styleAdmissionBloc.css');?>

<!-- MES JS -->
<?php echo $this->headScript()->appendFile($this->basePath().'/js/facturation/jsAdmissionBloc.js');?>

<?php use  Facturation\View\Helper\DateHelper;
$Control = new DateHelper();?>

<script type="text/javascript">
var base_url = window.location.toString();
var tabUrl = base_url.split("public");

$('#plus_admissionbloc').toggle(true);
$("#admissionbloc").replaceWith("<li id='admissionbloc' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='"+tabUrl[0]+"public/images_icons/moin-green2.png' alt='Liste' /> Admission au bloc </span></a></li>");
dep_admissionbloc1();
$('#admissionbloc_style').css({'font-weight':'bold','color':'white','font-size':'22px'});


$(window).load(function () {
	$('#wait').toggle(false);
	$('#contenuDesInterfaces').fadeIn().css({'visibility':'visible'});
});
</script>

<style>
#contenuDesInterfaces{ visibility: hidden; };
</style>


<div id="titre" style='font-family: police2; text-decoration:none; color: green; font-size: 18px; font-weight: bold; padding-left: 35px;'><iS style='font-size: 25px;'>&curren;</iS> DEMANDES D'ADMISSION</div>
     
<div id="wait" style="color: gray; font-size: 20px; text-align: center; margin-top: 80px;" > <span> Chargement ... </span> </div>
     
<div id="contenuDesInterfaces" >
     <div id="contenu" >
		<table style='width:95%; margin-left: 10px; align:center' class="table table-bordered tab_list_mini" id="patient">
			<thead >
			    <tr >
				    <th id="idpatient_" style='width: 10%;'><input type="text" name="search_browser" value=" ID_Patient" class="search_init" /></th>
					<th id="nom_" style='width: 15%;'><input type="text" name="search_browser" value=" Nom" class="search_init" /></th>
					<th id="prenom_" style='width: 17%;'><input type="text" name="search_browser" value=" Pr&eacute;nom" class="search_init" /></th>
					<th id="date_" style='width: 13%;'><input type="text" name="search_browser" value=" Date naissance" class="search_init" /></th>
					<th id="adresse_" style='width: 40%;'><input type="text" name="search_browser" value=" Adresse" class="search_init" /></th>
					<th id="effectuer_" style='width: 5%;'><input type="hidden" value="" class="" />Options</th>

				</tr>

			</thead>

			<tbody id="donnees" class="liste_patient">

	            <?php /* AFFICHAGE DE LA LISTE DES PATIENTS */?>

			</tbody>

		</table>

<script type="text/javascript">
initialisation();
</script>
</div>

<!-- POP UP pour Confirmation Suppression -->
                            <div id="confirmation" title="Informations" style="display:none;">
                              <div id="info" style="font-size: 16px;">

                              </div>
                            </div>


<!-- LES BOUTONS "TERMINER" ou "VALIDER" -->



<!-- PARTIE ENREGISTREMENT DU DECES -->

    <div id="declarer_deces">
          <a href="" id="precedent" style="text-decoration: none; font-family: police2; width:50px; margin-left:30px;">
	        <img style=" display: inline; " src='<?php echo $this->basePath().'/images_icons/transfert_gauche.PNG'?>' title="Rechercher" />
		    Pr&eacute;c&eacute;dent
		  </a>

		  <div id="info_patient">
		  </div>

		  <?php $today = new \DateTime('now');
		  $date = $today->format ( 'd/m/Y H:i' );?>
		  <div id="titre_info_deces">Programme op&eacute;ratoire<div style='float:right; margin-right:15px; font-size:14px;'> <input name='semainedatedebut' type='hidden' ><input name='semainedatefin' type='hidden'>  <span id='semaineDebutFin' style='cursor:pointer; padding-right: 20px; text-decoration: none;'> ---- </span> | <span style='padding-left: 20px;'> Saint-Louis le, <?php echo $date;?> </span> </div></div>
		  <div id="barre_separateur">
		  </div>

		  <?php $form = $this->form ;
		        $form->setAttribute ( 'action', $this->url ( 'facturation', array ('action' => 'enregistrer-admission-bloc') ) );
		        $form->setAttribute ( 'id' , 'formulairePrincipal');
		        $form->prepare();
		        echo $this->form()->openTag($form);
		       ?>
		  <?php echo $this->formhidden($form->get('id_patient')); ?>    
		  <div id="info_bebe" style='width: 100%; margin-top:10px; height:185px;'>
               <div style="float:left; width:18%; height:5%;">
		       </div>
		       
		       <div style='width: 77%; float:left;'>
		       	<input type="hidden" id="idDemandeOperation" name="idDemandeOperation">
		         <table id="form_patient" style="width:100%;">
		             <tr id="form_patient_radio" style='width: 100%;'>
		                 <td style='width: 33%;' class="comment-form-patient"><?php echo $this->formRow($form->get('diagnostic'));?></td>
		                 <td style='width: 33%;' class="comment-form-patient"><?php echo $this->formRow($form->get('intervention_prevue'));?></td>
		                 <td style='width: 33%;' class="comment-form-patient"><?php echo $this->formRow($form->get('vpa'));?></td>
		             </tr>
		         
		             <tr style='width: 100%;'>
		                 <td class="comment-form-patient" style='width: 33%;'><?php echo $this->formRow($form->get('salle'));?></td>
		                 <td class="comment-form-patient" style='width: 33%;'><?php echo $this->formRow($form->get('operateur'));?></td>
		                 <td class="comment-form-patient" style='width: 33%;'><?php echo $this->formRow($form->get('service'));?></td>
		             </tr>
		         </table>
		       </div>
		       <div style="float:left; width:5%;">
		       </div>
		  </div>

		  <div style='width: 90%; height: 60px;'>
		       <div style='width: 40%;'></div>
		       <div style='width: 20%;'>
                  <div id="terminer_annuler">
                    <div class="block" id="thoughtbot">
                       <button name="annuler" id="annuler" style=" height:35px; ">Annuler</button>
                    </div>
                    
                    <div class="block termineradmission" id="thoughtbot">
                       <button id="termineradmission" style=" height:35px; ">Terminer</button>
                    </div>
                  </div>
                </div>
                <div style='width: 40%;'></div>
          </div>
          <?php echo $this->form()->closeTag(); ?>
		  
    </div>
    
</div>

    <form id="FormulaireImprimerFacture" style="display: none;">
      <button id="ImprimerFacture"></button>
    </form>

<div id="context-menu">
    <ul class="dropdown-menu" >
         <li><a style="cursor: pointer;" ><img id="visualiserCTX" style='margin-right: 10px; width: 19px; height: 16px;' src='../images_icons/voir2.png'>Visualiser</a></li>
         <li class="divider2"></li>
         <li><a style="cursor: pointer;"><img  id="suivantCTX" style='margin-right: 10px; width: 19px; height: 16px;' src='../images_icons/transfert_droite.png'>Suivant</a></li>
         <li class="divider"></li>
         <li><a id="quitterCTX"  style="cursor: pointer;">Quitter</a></li>
    </ul>
</div>
		
		
<script>
animation();
$('#service').val("").attr({'disabled':'true'}).css({'background':'#f3f3f3'});
$('#operateur').val("");
function ajouterPatient(){
	vart=tabUrl[0]+'public/facturation/ajouter';
    $(location).attr("href",vart);
    return false;
}
$('#semaineDebutFin').click(function(){
	alert(1);

	stopPropagation();
});
//scriptFactMajor();
</script>


