<!-- MES STYLES -->
<?php echo $this->headLink()->appendStylesheet($this->basePath().'/css/facturation/styleFacturation.css');
?>

<!-- MES JS -->
<?php
echo $this->headScript ()->appendFile ( $this->basePath () . '/js/facturation/jsFacturation.js' );
echo $this->headScript()->appendFile($this->basePath().'/js/plugins/jqueryCharts/jquery.canvasjs.min.js');
echo $this->headLink ()->appendStylesheet ( $this->basePath () . '/css/facturation/DatePicker.css' );
?>

<script>
info_bulle();
controle_saisie();

var base_url = window.location.toString();
var tabUrl = base_url.split("public");
//POUR LE MENU GAUCHE dans -elementgauche.phtml
$('#plus_statistiques').toggle(true);
$("#statistiques").replaceWith("<li id='statistiques' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='<?php echo $this->basePath().'/images_icons/moin-green2.PNG';?>'  /> Statistiques </span></a></li>");
dep_statistiques1();
$('#statistiques_style').css({'font-weight':'bold','color':'white','font-size':'21px'});



</script>

<style>
#contenu{ visibility: hidden };
</style>




<div id="titre" style='font-family: police2; text-decoration:none; color: green; font-size: 18px; font-weight: bold; padding-left: 30px;'><iS style='font-size: 25px;'>&curren;</iS> INFORMATIONS STATISTIQUES</div>
<div id="wait" style="color: gray; font-size: 20px; text-align: center; margin-top: 80px;" > <span> Chargement ... </span> </div>
<div id="contenu" >
    
	<div style='width: 100%;'>
	
	
	<script type="text/javascript"> 
     var ordonnees = [];
     var abcisses  = [];
     var i = 1;
     var j = 1;
     </script>
     
	<table style='width:50%; margin-left: 10px; align:center; float: left; margin-top: 15px;' class="table table-bordered tab_list_mini" id="patient">
			<thead >
			    <tr> 
				    
					<th id="nom" align="center">Num&eacute;ro ordre</th>
					<th id="prenom" align="center">Sous dossier</th>
					<th id="date" align="center" name="date">Nombre</th>

				</tr>

			</thead>

			<tbody id="donnees" class="liste_patient">

	          <?php $tabDonnees = $this->infos;?>
	          <?php for($i=0 ; $i<count($tabDonnees[0]) ; $i++) { ?>
	          <tr >
					<td>
					  <?php echo $i+1; ?> 
					  
					  <script type="text/javascript"> ordonnees  [i++] = "<?php echo $tabDonnees[0][$i]; ?>"; </script>
					  <script type="text/javascript"> abcisses [j++] = <?php echo $tabDonnees[1][$tabDonnees[0][$i]]; ?>; </script>
					</td>
					<td><?php echo $tabDonnees[0][$i]; ?></td>
					<td><?php echo $tabDonnees[1][$tabDonnees[0][$i]]; ?></td>
			  </tr>
			  <?php } ?>

			</tbody>
			
		</table>
		
		<script type="text/javascript">
		var Pile = [];

    	for(var k = 1 ; k < ordonnees.length ; k++){
    		var tabValeur = { y: abcisses[k], label: ordonnees[k] };
    		Pile.push(tabValeur);
    	}

		</script>
		
	    <table id="AntecedentMedicaux" style="width: 48%; height: 220px;  float: left;">
	      <tr style="width: 100%; height: 150px;">
	         <td style="width: 100%; height: 100px; vertical-align: top; ">
	            <div id="chartContainerDiv" style="height: 400px; width: 100%;">   </div>
	         </td>
          </tr>
          
           <tr class="form-rendezvous" style="width: 100%;">
                                                
                            <th colspan='1' >
                                 <div class='block' id='thoughtbot' style=' vertical-align: bottom; float: right; padding-left:10%; padding-top: 35px; font-size: 18px; font-weight: bold;'> <button id='annuler' >Suivant</button></div>
                            </th>
            </tr>
	    </table>
	
								
	
	
    
<script>    

$(window).load(function () {
	$('#wait').toggle(false);
	$('#contenu').fadeIn().css({'visibility':'visible'});
	
	      
	$(document).ready(function($) {
		var chart = new CanvasJS.Chart("chartContainerDiv", {
			title: {
				text: "Basic Column Chart"
			},
			data: [{
				type: "column",
				dataPoints: Pile 
			}]
		});
		
		chart.render();

		
	 });
});    
    
</script>  

<script> 


    $(document).keypress(function(e){
	if(e.keyCode == 11){
		e.preventDefault();
	}
    });
    $('#annuler').click(function(){ 
		 vart=tabUrl[0]+'public/facturation/informations-complementaires';
	     $(location).attr("href",vart);
	     return false;
	});
</script>
    
    
       
    
    
    </div>

</div>


