<!-- MES STYLES -->
<?php echo $this->headLink()->appendStylesheet($this->basePath().'/css/archivage/styleAdmission.css');?>

<!-- MES JS -->
<?php echo $this->headScript()->appendFile($this->basePath().'/js/archivage/jsAdmission.js');?>

<?php use  Facturation\View\Helper\DateHelper;
$Control = new DateHelper();?>

<script type="text/javascript">
var base_url = window.location.toString();
var tabUrl = base_url.split("public");

$('#plus_facturationArchive').toggle(true);
$("#facturationArchive").replaceWith("<li id='facturationArchive' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='"+tabUrl[0]+"public/images_icons/moin-green2.png' alt='Liste' /> Facturation </span></a></li>");
dep_facturationArchive1();
$('#stylefacturationArchive').css({'font-weight':'bold','color':'white','font-size':'20px'});


$(window).load(function () {
	$('#wait').toggle(false);
	$('#contenu').fadeIn().css({'visibility':'visible'});
});
</script>

<style>
#contenu { visibility: hidden; };
</style>


     <div id="titre" style='font-family: police2; text-decoration:none; color: green; font-size: 18px; font-weight: bold; padding-left: 35px;'><iS style='font-size: 25px;'>&curren;</iS> RECHERCHER LE PATIENT</div>
     
     <div id="wait" style="color: gray; font-size: 20px; text-align: center; margin-top: 80px;" > <span> Chargement ... </span> </div>
     
     <div id="contenu" >
        <div style="margin-right: 45px; float:right; font-size: 15px; color: gray; margin-top:5px;"><a style="text-decoration: none; cursor:pointer;" href="javascript:ajouterPatient()" ><img src='../images_icons/aj.gif' title="ajouter" /><i style="font-family: Times New Roman; font-size: 15px; color: green;"> ajouter un patient</i></a></div>
		<div style="margin-right: 20px; float:right; font-size: 15px; margin-top:5px; font-family: Times New Roman; font-size: 15px; color: green;"> <i style='cursor:pointer;' id='afficherTous'> Tous </i> | <i style='cursor:pointer;' id='afficherArchive'> Archives </i> </div>
		
		<table style='width:95%; margin-left: 10px; align:center' class="table table-bordered tab_list_mini" id="patientAdmission">
			<thead >
			    <tr >
				    <th id="idpatient_" style='width: 10%;'><input type="text" name="search_browser" value=" ID_Patient" class="search_init" /></th>
					<th id="nom_" style='width: 15%;'><input type="text" name="search_browser" value=" Nom" class="search_init" /></th>
					<th id="prenom_" style='width: 17%;'><input type="text" name="search_browser" value=" Pr&eacute;nom" class="search_init" /></th>
					<th id="date_" style='width: 13%;'><input type="text" name="search_browser" value=" Date naissance" class="search_init" /></th>
					<th id="adresse_" style='width: 36%;'><input type="text" name="search_browser" value=" Adresse" class="search_init" /></th>
					<th id="effectuer_" style='width: 9%;'><input type="hidden" name="search_browser" value="" class="" />Options</th>

				</tr>

			</thead>

			<tbody id="donnees" class="liste_patient">

	            <?php /* AFFICHAGE DE LA LISTE DES PATIENTS */?>

			</tbody>

		</table>

      <script type="text/javascript">
       initialisation();
      </script>

      
      
<div id="context-menu">
    <ul class="dropdown-menu" >
         <li><a style="cursor: pointer;" ><img id="visualiserCTX" style='margin-right: 10px; width: 19px; height: 16px;' src='/simens/public/images_icons/voir2.png'>Visualiser</a></li>
         <li class="divider2"></li>
         <li><a style="cursor: pointer;"><img  id="suivantCTX" style='margin-right: 10px; width: 19px; height: 16px;' src='/simens/public/images_icons/transfert_droite.png'>Suivant</a></li>
         <li class="divider"></li>
         <li><a id="quitterCTX"  style="cursor: pointer;">Quitter</a></li>
    </ul>
</div>

</div>

<!-- POP UP pour Confirmation Suppression -->
                            <div id="confirmation" title="Informations" style="display:none;">
                              <div id="info" style="font-size: 16px;">

                              </div>
                            </div>


<!-- LES BOUTONS "TERMINER" ou "VALIDER" -->



<!-- PARTIE ENREGISTREMENT DU DECES -->

    <div id="admettrePatient">
          <a href="" id="precedent" style="text-decoration: none; font-family: police2; width:50px; margin-left:30px;">
	        <img style=" display: inline; " src='<?php echo $this->basePath().'/images_icons/transfert_gauche.PNG'?>' alt='Constantes' title="Rechercher" />
		    Pr&eacute;c&eacute;dent
		  </a>

		  <div id="info_patient">
		  </div>

		  <?php $today = new \DateTime('now');
		  $date = $today->format ( 'd/m/Y H:i' );?>
		  <div id="titre_info_deces">Facturation <div style='float:right; margin-right:15px; font-size:14px;'> Saint-Louis le, <?php echo $date;?></div></div>
		  <div id="barre_separateur">
		  </div>

		  <?php $form = $this->form ;
		        $form->setAttribute ( 'action', $this->url ( 'archivage', array ('action' => 'enregistrer-admission') ) );
		        $form->prepare();
		        echo $this->form()->openTag($form);
		       ?>
		  <?php echo $this->formhidden($form->get('id_patient'))?>     
		  <div id="info_bebe" style='width: 100%; margin-top:10px; height:80px;'>
               <div style="float:left; width:18%; height:5%;">
		       </div>
		       
		       <div style='width: 77%; float:left;'>
		         <table id="form_patient" style="width:100%;">
		             <tr style='width: 100%;'>
		                 <td class="comment-form-patient" style='width: 25%;'><?php echo $this->formRow($form->get('date'))?></td>
		                 <td class="comment-form-patient" style='width: 25%;'><?php echo $this->formRow($form->get('numero'))?></td>
		                 <td class="comment-form-patient" style='width: 35%;'><?php echo $this->formRow($form->get('service'))?></td>
		                 <td class="comment-form-patient" style='width: 15%;'><?php echo $this->formRow($form->get('montant'))?></td>
		             </tr>
		         </table>
		       </div>
		       <div style="float:left; width:5%;">
		       </div>
		  </div>

		  <div style='width: 90%; height: 60px;'>
		       <div style='width: 40%;'></div>
		       <div style='width: 20%;'>
                  <div id="terminer_annuler">
                    <div class="block" id="thoughtbot">
                       <button name="annuler" id="annuler" style=" height:35px; ">Annuler</button>
                    </div>
                    
                    <div class="block" id="thoughtbot">
                       <button type="submit" id="termineradmissio" style=" height:35px; ">Terminer</button>
                    </div>
                  </div>
                </div>
                <div style='width: 40%;'></div>
          </div>
          <?php echo $this->form()->closeTag(); ?>
		  
    </div>

<script>
animation();
$('#service').val("");
function ajouterPatient(){
	vart=tabUrl[0]+'public/archivage/ajouter';
    $(location).attr("href",vart);
    return false;
}

$('#termineradmissio').click(function(){
	if($('#date').val() == ""){
		return true;
	} else {
	   $('#service').attr('disabled',false);
	   $('#service').css({'font-weight':'bold','color':'gray','font-family': 'Times  New Roman','font-size':'14px'});
	   return true;
	}
});
</script>

