<!-- MES STYLES --> 
<?php echo $this->headLink()->appendStylesheet($this->basepath().'/css/archivage/styleAdministrerSoin.css');
      echo $this->headLink()->appendStylesheet($this->basepath().'/css/facturation/DatePicker.css'); 
?>
<!-- MES JS -->
<?php echo $this->headScript()->appendFile($this->basepath().'/js/archivage/jsAppliquerSoin.js');?>

<?php $form = $this->form; ?>

<script>
var base_url = window.location.toString();
var tabUrl = base_url.split("public");

/***POUR LE MENU GAUCHE dans -elementgauche.phtml***/
$('#plus_hospitalisationArchive').toggle(true); 
$("#hospitalisationArchive").replaceWith("<li id='hospitalisationArchive' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img  src='../images_icons/moin-green2.png' /> Hospitalisations </span></a></li>");
dep_hospitalisationArchive1();
$('#style3HospitalisationArchive').css({'font-weight':'bold','color':'white','font-size':'20px'});

</script>

<script type="text/javascript">
$(window).load(function () {
	$('#wait').toggle(false);
	$('#toutLeContenu').fadeIn().css({'visibility':'visible'});
});
</script>

<style>
#toutLeContenu{ visibility: hidden; };
</style>

<div id="titre" style='font-family: police2; text-decoration: none; color: green; font-size: 20px; font-weight: bold; padding-left:20px;'>
	<iS style='font-size: 25px;'>&curren;</iS>
	LISTE DES PATIENTS
</div>
<div id="wait" style="color: gray; font-size: 20px; text-align: center; margin-top: 80px;" > <span> Chargement ... </span> </div>

<div id="toutLeContenu"> 
<div id="contenu"> 

            <table id="patient" class="table table-bordered tab_list_mini" >
				<thead>
					<tr style="height: 50px; width:100%;">
						<th id="nom" style='cursor: pointer;'>Nom</th>
						<th id="prenom" style='cursor: pointer;'>Pr&eacute;nom</th>
						<th id="date" style='cursor: pointer;'>Date. naiss</th>
						<th id="sexe" style='cursor: pointer;'>Sexe</th>
						<th id="adresse" style='cursor: pointer;'>Date & Heure D&eacute;but</th>
						<th id="nationalite" style='cursor: pointer;'>Date fin pr&eacute;vue.</th>
						<th id="effectuer">Options</th>
					</tr>
				</thead>

				<tbody id="donnees" class="liste_patient">

					<!-- ************ On affiche les patients en une liste ordonnï¿½e************ -->

				</tbody>

				<tfoot id="foot" class="foot_style">
					<tr>
						<th id="nom_" style='width: 16%;'><input type="text" name="search_browser"
							value=" Nom" class="search_init" /></th>
						<th id="prenom_" style='width: 18%;'><input type="text" name="search_browser"
							value=" Pr&eacute;nom" class="search_init" /></th>
						<th id="date_" style='width: 12%;'><input type="text" name="search_browser"
							value=" Date naissance" class="search_init" /></th>
						<th id="sexe_" style='width: 7%;'><input type="text" name="search_browser"
							value=" Sexe" class="search_init" /></th>
						<th id="adresse_" style='width: 20%;'><input type="text" name="search_browser"
							value=" Adresse" class="search_init" /></th>
						<th id="nationalite_" style='width: 17%;'><input type="text" name="search_browser"
							value=" Nationalite" class="search_init" /></th>
						<th id="effectuer_" style='width: 10%;'><input type="hidden" name="search_browser"
							value="" class="" /></th>

					</tr>
				</tfoot>
			</table>
</div>

<div id="vue_patient">

</div>

<div id="vue_detail_hospi_patient">

</div>
</div>

<!--***********************************************************************************************-->                              

<!--==========================POP UP pour Afficher les détails =================================-->                              
                          
<!--***********************************************************************************************-->  
        <div id="informations" title="D&eacute;tails des infos du soin" style="display:none;">
             
             <div id="info" style="font-size: 16px;">
                              
             </div>
             
        </div>
        
        
<!--***********************************************************************************************-->                              

<!--============================ POP UP pour Afficher les détails =================================-->                              
                          
<!--***********************************************************************************************-->  
        <div id="application_soin" title="Ajouter une note" style="display:none;">
             
             <div id="info_soin" style="font-size: 16px;">
                <?php $form = $this->form;?>

                <span id="HeureActu" style="position:absolute; right: 30px; top: 15px; color: red; font-weight: bold; font-family: time new romans; font-size: 20px;"> --- </span>
                <table id="form_patient" style="width: 100%;">  
                   <tr class="comment-form-patient" style="width: 100%;">
                      <td style="width: 33%;"> <?php echo $this->formRow($form->get('note'));?></td> 
                   </tr>
                </table>

             </div>
        
        </div>

        
        
<div id="context-menu">
    <ul class="dropdown-menu" >
         <li><a style="cursor: pointer;" ><img id="detailsCTX" style='margin-right: 10px; width: 19px; height: 16px;' src='/simens/public/images_icons/voir.png'>D&eacute;tails</a></li>
         <li class="divider2"></li>
         <li><a style="cursor: pointer;"><img  id="appliquerCTX" style='margin-right: 10px; margin-left: -3px; ' src='/simens/public/img/dark/blu-ray.png'>Appliquer un soin</a></li>
         <li class="divider"></li>
         <li><a id="quitterCTX"  style="cursor: pointer;">Quitter</a></li>
    </ul>
</div>



<script type="text/javascript">
function FaireClignoterImage (){
     $("#clignoterHeure").fadeOut(900).fadeIn(800);
}
$(function(){
 setInterval('FaireClignoterImage()',2200);
});

$("#vue_detail_hospi_patient").toggle(false);
$("#vue_patient").toggle(false);
$("#hospitaliser").toggle(false);
</script>