<style>
#sidebarMenu{ visibility: hidden }
</style>

<script>
$(window).load(function () {

	$('#waitMenuGauche').toggle(false);
	$('#sidebarMenu').fadeIn().css({'visibility':'visible'});
	 
});
</script>

<div id="waitMenuGauche" style="color: #cccccc; font-size: 13px;  margin-top: 80px;  margin-left: 60px;" > <span> Chargement ... </span> </div>



<ul id="sidebarMenu">
	<!-- MENU ***SURVEILLANT DE SERVICE*** -->
	<!-- MENU ***SURVEILLANT DE SERVICE*** -->
	<!-- MENU ***SURVEILLANT DE SERVICE*** -->
	<li id="naissance"><a href="">
	    <span style="margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;"> <img id="image" style="display: inline;" src='<?php echo $this->basePath().'/images_icons/plus-green1.png'?>' alt='Liste' /> Consultations </span></a> </li>

	<li id="plus_naissance" style="background: #4a5765;" >
	   <div style="margin-left:30px; height:40px; padding-top:20px;"><a href="<?php echo $this->url('consultation', array('action'=> 'recherche'));?>"  >
	       <span id="ajouter_style" style="margin-left:5px; color: white; font-size:15px; font-family:Times New Roman;"><img style="display: inline;" src='<?php echo $this->basePath().'/images_icons/dossier.PNG'?>' alt='Liste' /> En cours ...</span></a>
	   </div>
	   <div id="liste_naiss"style="margin-left:30px; height:40px;"><a href="<?php echo $this->url('consultation', array('action'=> 'espace-recherche-surv'));?>">
	       <img style="margin-left:5px; display: inline;" src='<?php echo $this->basePath().'/images_icons/Search_22.PNG'?>' alt='Liste' />
	       <span id="liste_style" style="font-size:15px; color: white; font-family:Times New Roman;">Recherche</span></a>
	   </div>
	</li>
	
	<!-- MENU ***MEDECIN DE SERVICE*** -->
	<!-- MENU ***MEDECIN DE SERVICE*** -->
	<!-- MENU ***MEDECIN DE SERVICE*** -->
	
	<!-- MENU ***ADMISSION AU BLOC*** -->
	<li id="admissionbloc"><a href="">
	   <span style="margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;"> <img id="image" style="display: inline;" src='<?php echo $this->basePath().'/images_icons/plus-green1.png'?>' alt='Liste' /> Bloc op&eacute;ratoire </span></a> 
	</li>

	<li id="plus_admissionbloc" style="background: #4a5765;" >

	   <div style="margin-left:30px; height:40px; padding-top:20px;"><a href="<?php echo $this->basePath()."/consultation/protocole-operatoire";?>"  >
	      <span id="admissionbloc_style" style="margin-left:5px; color: white; font-size:15px; font-family:Times New Roman;"><img style="display: inline;" src='<?php echo $this->basePath().'/images_icons/dossier.PNG'?>' alt='Liste' /> C.R.O</span></a>
	   </div>

	   <div style="margin-left:30px; height:40px;"><a href="<?php echo $this->basePath()."/consultation/liste-protocole-operatoire";?>">
	      <img style="margin-left:5px; display: inline;" src='<?php echo $this->basePath().'/images_icons/liste.PNG'?>' alt='Liste' />
	      <span id="liste_admissionbloc_style" style="font-size:15px; color: white; font-family:Times New Roman;">Liste</span></a>
	   </div>
	   
	</li>
	
	
	<li id="deces"><a href="">
	    <span style="margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;"> <img id="image" style="display: inline;" src='<?php echo $this->basePath().'/images_icons/plus-green1.png'?>' alt='Liste' /> Consultations </span></a> </li>

	<li id="plus_deces" style="background: #4a5765;" >

	   <div style="margin-left:30px; height:40px; padding-top:20px;"><a href="<?php echo $this->url('consultation', array('action'=> 'consultation-medecin'));?>"  >
	       <span id="declarer_style" style="margin-left:5px; color: white; font-size:15px; font-family:Times New Roman;"><img style="display: inline;" src='<?php echo $this->basePath().'/images_icons/dossier.PNG'?>' alt='Liste' /> En cours ...</span></a>
	   </div>

	   <div style="margin-left:30px; height:40px;"><a href="<?php echo $this->url('consultation', array('action'=> 'espace-recherche-med'));?>"> <!-- test-mp3 ---- espace-recherche-med -->
	       <img style="margin-left:5px; display: inline;" src='<?php echo $this->basePath().'/images_icons/Search_22.PNG'?>' alt='Liste' />
	       <span id="liste_recherche_style" style="font-size:15px; color: white; font-family:Times New Roman;"> Recherche </span></a>
	   </div>
	</li>
	
	<!-- Menu ***Hospitalisation*** -->
	<li id="dossier_personnel"><a href="">
	    <span style="margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;"> <img id="image" style="display: inline;" src='<?php echo $this->basePath().'/images_icons/plus-green1.png'?>' alt='Liste' /> Hospitalisations </span></a> </li>
	
	<li id="plus_dossier_personnel" style="background: #4a5765;" >
	<div style="margin-left:30px; height:40px; padding-top:20px;"><a href="<?php echo $this->basePath().'/consultation/en-cours';?>">
	       <img style="margin-left:5px; display: inline;" src='<?php echo $this->basePath().'/images_icons/liste.png'?>' alt='Liste' />
	       <span id="en_cours_style" style="font-size:15px; color: white; font-family:Times New Roman;">En cours ...</span></a>
	   </div>
	</li>

	<li id="separateurMenuArchive"><a> <span>...............................................</span></a> </li>
	<li id='archivage'> 
	   
	   <div style="margin-left:30px; height:40px;"><a href="<?php echo $this->url('archivage', array('action'=> 'liste-dossiers-patients'));?>">
	       <img style="margin-left:5px;" src='<?php echo $this->basePath().'/images_icons/Folders2.png'?>'  />
	       <span  style="font-size:15px; color: white; font-family:Times New Roman;">Archivage</span></a>
	   </div>
	</li>
</ul>

<?php
//CHOISIR LE MENU A AFFICHER SELON QUE C'EST LE MEDECIN OU C'EST LE SURVEILLANT
$user = $this->layout()->user;
$role = $user['role'];

if($role == 'surveillant'){ ?>
<script>
$("#deces").toggle(false);
$("#dossier_personnel").toggle(false);
$("#archivage").toggle(false);
</script>
<?php
}
else if($role == 'medecin'){ ?>
<script>
$("#naissance").toggle(false);
</script>
<?php
     }
?>

<script>
//NAISSANCE
function dep1(){
	$('#naissance').click(function(){
		$("#naissance").replaceWith("<li id='naissance'><a href=''><span style='margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='/simens/public/images_icons/plus-green1.png' alt='Liste' /> Consultations </span></a></li>");
		dep2();
	    $('#plus_naissance').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

function dep2(){
	$('#naissance').click(function(){
		$("#naissance").replaceWith("<li id='naissance' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='/simens/public/images_icons/moin-green2.PNG' alt='Liste' /> Consultations </span></a></li>");
		dep1();
	    $('#plus_naissance').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

$('#plus_naissance').toggle(false);
$('#naissance').click(function(){
	$("#naissance").replaceWith("<li id='naissance' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='/simens/public/images_icons/moin-green2.png' alt='Liste' /> Consultations </span></a></li>");
	dep1();
    $('#plus_naissance').animate({
        height : 'toggle'
    },1000);
 return false;
});

//*******************************************************************************************************************************
//MEDECIN DE SERVICE
function dep_deces1(){
	$('#deces').click(function(){
		$("#deces").replaceWith("<li id='deces'><a href=''><span style='margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='/simens/public/images_icons/plus-green1.png' alt='Liste' /> Consultations </span></a></li>");
		dep_deces2();
	    $('#plus_deces').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

function dep_deces2(){
	$('#deces').click(function(){
		$("#deces").replaceWith("<li id='deces' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='/simens/public/images_icons/moin-green2.png' alt='Liste' /> Consultations </span></a></li>");
		dep_deces1();
	    $('#plus_deces').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

$('#plus_deces').toggle(false);
$('#deces').click(function(){
	$("#deces").replaceWith("<li id='deces' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='/simens/public/images_icons/moin-green2.png' alt='Liste' /> Consultations </span></a></li>");
	dep_deces1();
$('#plus_deces').animate({
    height : 'toggle'
},1000);
return false;
});

//*******************************************************************************************************************************
//HOSPITALISATION
function dep_dossier_personnel1(){
	$('#dossier_personnel').click(function(){
		$("#dossier_personnel").replaceWith("<li id='dossier_personnel'><a href=''><span style='margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='/simens/public/images_icons/plus-green1.png' alt='Liste' /> Hospitalisations </span></a></li>");
		dep_dossier_personnel2();
	    $('#plus_dossier_personnel').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

function dep_dossier_personnel2(){
	$('#dossier_personnel').click(function(){
		$("#dossier_personnel").replaceWith("<li id='dossier_personnel' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='/simens/public/images_icons/moin-green2.png' alt='Liste' /> Hospitalisations </span></a></li>");
		dep_dossier_personnel1();
	    $('#plus_dossier_personnel').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

$('#plus_dossier_personnel').toggle(false);
$('#dossier_personnel').click(function(){
	$("#dossier_personnel").replaceWith("<li id='dossier_personnel' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='/simens/public/images_icons/moin-green2.png' alt='Liste' /> Hospitalisations </span></a></li>");
	dep_dossier_personnel1();
$('#plus_dossier_personnel').animate({
height : 'toggle'
},1000);
return false;
});

//*******************************************************************************************************************************
//ADMISSION
function dep_admissionbloc1(){
	$('#admissionbloc').click(function(){
		$("#admissionbloc").replaceWith("<li id='admissionbloc'><a href=''><span style='margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='../images_icons/plus-green1.png' alt='Liste' /> Bloc op&eacute;ratoire </span></a></li>");
		dep_admissionbloc2();
	    $('#plus_admissionbloc').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

function dep_admissionbloc2(){
	$('#admissionbloc').click(function(){
		$("#admissionbloc").replaceWith("<li id='admissionbloc' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='../images_icons/moin-green2.png' alt='Liste' /> Bloc op&eacute;ratoire </span></a></li>");
		dep_admissionbloc1();
	    $('#plus_admissionbloc').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

$('#plus_admissionbloc').toggle(false);
$('#admissionbloc').click(function(){
	$("#admissionbloc").replaceWith("<li id='admissionbloc' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='../images_icons/moin-green2.png' alt='Liste' /> Bloc op&eacute;ratoire </span></a></li>");
	dep_admissionbloc1();
$('#plus_admissionbloc').animate({
height : 'toggle'
},1000);
return false;
});

</script>