<!-- MES STYLES --> 
<?php echo $this->headLink()->appendStylesheet($this->basepath().'/css/hospitalisation/styleEncours.css');
      echo $this->headLink()->appendStylesheet($this->basepath().'/css/facturation/DatePicker.css'); 
?>
<!-- MES JS -->
<?php echo $this->headScript()->appendFile($this->basepath().'/js/hospitalisation/jsEncours.js');?>

<?php $form = $this->form; ?>
<div id="titre" style='font-family: police2; text-decoration: none; color: green; font-size: 20px; font-weight: bold; padding-left:20px;'>
	<iS style='font-size: 25px;'>&curren;</iS>
	LISTE DES PATIENTS
</div>
<div id="contenu"> 

            <table id="patient" class="table table-bordered tab_list_mini" >
				<thead>
					<tr style="height: 50px; width:100%;">
						<th id="nom" style='cursor: pointer;'>Nom</th>
						<th id="prenom" style='cursor: pointer;'>Prenom</th>
						<th id="date" style='cursor: pointer;'>Date. naiss</th>
						<th id="sexe" style='cursor: pointer;'>Sexe</th>
						<th id="adresse" style='cursor: pointer;'>Date & Heure d&eacute;but</th>
						<th id="nationalite" style='cursor: pointer;'>Date Fin pr&eacute;vue</th>
						<th id="effectuer">Options</th>
					</tr>
				</thead>

				<tbody id="donnees" class="liste_patient">

					<!-- ************ On affiche les patients en une liste ordonnï¿½e************ -->

				</tbody>

				<tfoot id="foot" class="foot_style">
					<tr>
						<th id="nom_" style='width: 17%;'><input type="text" name="search_browser"
							value=" Nom" class="search_init" /></th>
						<th id="prenom_" style='width: 18%;'><input type="text" name="search_browser"
							value=" Pr&eacute;nom" class="search_init" /></th>
						<th id="date_" style='width: 12%;'><input type="text" name="search_browser"
							value=" Date naissance" class="search_init" /></th>
						<th id="sexe_" style='width: 7%;'><input type="text" name="search_browser"
							value=" Sexe" class="search_init" /></th>
						<th id="adresse_" style='width: 19%;'><input type="text" name="search_browser"
							value=" Adresse" class="search_init" /></th>
						<th id="nationalite_" style='width: 16%;'><input type="text" name="search_browser"
							value=" Nationalite" class="search_init" /></th>
						<th id="effectuer_" style='width: 11%;'><input type="hidden" name="search_browser"
							value="" class="" /></th>

					</tr>
				</tfoot>
			</table>
</div>

<div id="vue_patient">

</div>

<div id="vue_liberer_patient">

</div>

<div id="vue_detail_hospi_patient">

</div>

<div id="hospitaliser">

    <div id="vue_patient_hospi">

    </div>
    <?php
    $form = $this->form;
    $form->setAttribute ( 'action', $this->url ( 'hospitalisation', array ('action' => 'en-courssss') ));
    $form->prepare ();
    echo $this->form ()->openTag ( $form );
    ?>
    <?php echo $this->formhidden($form->get('id_sh'));?>
    <?php echo $this->formhidden($form->get('id_hosp'));?>

    <table id="form_patient" style="margin-left: 195px; width: 80%;">  
      
      <tr class="comment-form-patient" style="width: 80%;">
         <td style="width: 30%;"> <?php echo $this->formRow($form->get('id_soins'));?></td> 
         <td id="duree_soin" style="width: 18%;"> <?php echo $this->formRow($form->get('duree'));?></td> 
         <td style="width: 30%;"> <?php echo $this->formRow($form->get('date_recommandee'));?></td> 
         <td style="width: 22%;"> <?php echo $this->formRow($form->get('heure_recommandee'));?></td> 
      </tr>
      
    </table>
    
    <table id="form_patient" style="margin-left: 195px; width: 80%;"> 
      <tr class="comment-form-patient">
         <td id="note_soin"  style="width: 40%; "> <?php echo $this->formRow($form->get('motif'));?></td>
         <td id="note_soin"  style="width: 40%; "> <?php echo $this->formRow($form->get('note'));?></td>
         <td  style="width: 10%;" id="ajouter"><a href='javascript:ajouter()'><img style='display: inline; margin-right: 10%;' src='/simens/public/images_icons/112.png' title='ajouter le soin'></a></td>   
         <td  style="width: 10%;"><a href='javascript:vider_tout()'><img id='test' style='display: inline; margin-right: 10%;' src='/simens/public/images_icons/118.png' title='vider tout'></a></td>           
      </tr>
    </table> 
    
    <div id="liste_soins">

    </div>
    
    <table id="form_patient" style="margin-left: 195px; width: 80%;"> 
    <tr class="comment-form-patient" style="width: 80%; height: 70px; vertical-align: bottom;">
         <td style="width: 33%;"></td>
         <td style="width: 33%; padding-left: 30px;"> 
            <?php echo $this->formSubmit($form->get('terminersoin')); ?>
         </td> 
         <td style="width: 33%;"></td>
      </tr>
    </table> 

    <?php echo $this->form()->closeTag();?>
    
</div>

<!--***********************************************************************************************-->                              

<!--==========================POP UP pour Confirmation Suppression=================================-->                              
                          
<!--***********************************************************************************************-->  
        <div id="confirmation" title="Confirmation de l'ajout" style="display:none;">
             <p style="font-size: 16px;">
                 <span style="float:left; margin:0 0px 20px 0; font-size:17px; ">
                 <img src="<?php echo $this->basepath().'/images_icons/warning_16.png';?>" />
                                
                 Etes-vous s&ucirc;r de vouloir ajouter le soin ?</span>
             </p>
         </div>
         
<!--***********************************************************************************************-->                              

<!--==========================POP UP pour Afficher les détails =================================-->                              
                          
<!--***********************************************************************************************-->  
        <div id="informations" title="D&eacute;tails des infos du soin" style="display:none;">
             
             <div id="info" style="font-size: 16px;">
                              
             </div>
             
        </div>
        
<!--***********************************************************************************************-->                              

<!--==========================POP UP pour Afficher les détails =================================-->                              
                          
<!--***********************************************************************************************-->  
        <div id="confirmationSup" title="Confirmation de la suppression" style="display:none;">
             
             <p style="font-size: 16px;">
                 <span style="float:left; margin:0 0px 20px 0; font-size:17px; ">
                 <img src="<?php echo $this->basepath().'/images_icons/warning_16.png';?>" />
                                
                 Etes-vous s&ucirc;r de vouloir supprimer ce soin ?</span>
             </p>
             
        </div>

<!--***********************************************************************************************-->                              

<!--==========================POP UP pour Afficher les détails =================================-->                              
                          
<!--***********************************************************************************************-->  
        <div id="modification" title="Modifier les donn&eacute;es du soin" style="display:none;">
             
            <div id="info_modif" style="font-size: 16px;">
                              
             </div>
             
        </div>
        
        
<script type="text/javascript">

$("#vue_patient").toggle(false);
$("#vue_liberer_patient").toggle(false);
$("#vue_detail_hospi_patient").toggle(false);
$("#hospitaliser").toggle(false);

var base_url = window.location.toString();
var tabUrl = base_url.split("public");

/***POUR LE MENU GAUCHE dans -elementgauche.phtml***/
$('#plus_dossier_personnel').toggle(true); 
$("#dossier_personnel").replaceWith("<li id='dossier_personnel' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:18px; font-family:Times New Roman;'> <img style='display: inline;' src='"+tabUrl[0]+"public/images_icons/moins-vert.PNG' alt='Liste' /> Hospitalisation </span></a></li>");
dep_dossier_personnel1();
$('#en_cours_style').css({'font-weight':'bold','color':'white','font-size':'18px'});
</script>