<!-- SCRIPT DU NOUVEAU CODE POUR LA GESTION DES IMAGES  -->
<?php 
    echo $this->headLink()->appendStylesheet($this->basePath().'/css/pikachoose/bottomRadiologie.css');
    echo $this->headScript()->appendFile($this->basePath().'/js/plugins/pikachoose/jquery.jcarousel.min.js');
    echo $this->headScript()->appendFile($this->basePath().'/js/plugins/pikachoose/jquery.pikachoose.min.js');
?>
<!-- les scripts des images dans examen morphologique   -->
<?php echo $this->headScript()->appendFile($this->basePath().'/js/plugins/fancybox/source/jquery.fancybox.js');?>
<?php echo $this->headLink()->appendStylesheet($this->basePath().'/js/plugins/fancybox/source/jquery.fancybox.css');?>



<!-- MES STYLES --> 
<?php echo $this->headLink()->appendStylesheet($this->basepath().'/css/hospitalisation/styleListeDemandesExamens.css');
      echo $this->headLink()->appendStylesheet($this->basepath().'/css/facturation/DatePicker.css'); 
?>
<!-- MES JS -->
<?php echo $this->headScript()->appendFile($this->basepath().'/js/hospitalisation/jsListeDemandesExamensMorpho.js');?>

<?php $form = $this->form; ?>

<style>
#toutLeContenu{ visibility: hidden }
</style>

<script>
var base_url = window.location.toString();
var tabUrl = base_url.split("public");

$('#plus_operationMorpho').toggle(true); 
$("#operationMorpho").replaceWith("<li id='operationMorpho' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:18px; font-family:Times New Roman;'> <img style='display: inline;' src='"+tabUrl[0]+"public/images_icons/moin-green2.png' alt='Liste' /> Demandes d'examen </span></a></li>");
dep3();
$('#recherche_styleMorpho').css({'font-weight':'bold','color':'white','font-size':'21px'});


$(window).load(function () {
	$('#wait').toggle(false);
	$('#toutLeContenu').fadeIn().css({'visibility':'visible'});
});

$(function() {
	$( "#tabs" ).tabs();
});
</script>

<div id="titre" style='font-family: police2; text-decoration: none; color: green; font-size: 20px; font-weight: bold; padding-left:20px;'>
	<iS style='font-size: 25px;'>&curren;</iS>
	LISTE DES PATIENTS
</div>
<div id="wait" style="color: gray; font-size: 20px; text-align: center; margin-top: 80px;" > <span> Chargement ... </span> </div>

<div id="toutLeContenu">
<div id="contenu"> 

            <table id="patient" class="table table-bordered tab_list_mini" >
				<thead>
					<tr style="height: 50px; width:100%;">
						<th id="nom" style='cursor: pointer;'>Nom</th>
						<th id="prenom" style='cursor: pointer;'>Prenom</th>
						<th id="date" style='cursor: pointer;'>Date. naiss</th>
						<th id="sexe" style='cursor: pointer;'>Sexe</th>
						<th id="adresse" style='cursor: pointer;'>Date & Heure Demande</th>
						<th id="nationalite" style='cursor: pointer;'>M&eacute;decin demandeur</th>
						<th id="effectuer">Options</th>
					</tr>
				</thead>

				<tbody id="donnees" class="liste_patient">

					<!-- ************ On affiche les patients en une liste ordonnï¿½e************ -->

				</tbody>

				<tfoot id="foot" class="foot_style">
					<tr>
						<th id="nom_" style='width: 16%;'><input type="text" name="search_browser"
							value=" Nom" class="search_init" /></th>
						<th id="prenom_" style='width: 18%;'><input type="text" name="search_browser"
							value=" Pr&eacute;nom" class="search_init" /></th>
						<th id="date_" style='width: 12%;'><input type="text" name="search_browser"
							value=" Date naissance" class="search_init" /></th>
						<th id="sexe_" style='width: 7%;'><input type="text" name="search_browser"
							value=" Sexe" class="search_init" /></th>
						<th id="adresse_" style='width: 20%;'><input type="text" name="search_browser"
							value=" Adresse" class="search_init" /></th>
						<th id="nationalite_" style='width: 20%;'><input type="text" name="search_browser"
							value=" Nationalite" class="search_init" /></th>
						<th id="effectuer_" style='width: 7%;'><input type="hidden" name="search_browser"
							value="" class="" /></th>

					</tr>
				</tfoot>
			</table>
</div>

<div id="vue_patient">

</div>

<div id="vue_detail_hospi_patient">

</div>

        
<!--***********************************************************************************************-->                              

<!--==========================POP UP pour Afficher les détails =================================-->                              
                          
<!--***********************************************************************************************-->  
        <div id="application_examen" title="Les r&eacute;sultats de l'examen" style="display:none;">
             
             <!-- POUR LA VISUALISATION DES RESULTATS ENTRES -->
             <!-- POUR LA VISUALISATION DES RESULTATS ENTRES -->
             <!-- POUR LA VISUALISATION DES RESULTATS ENTRES -->
             <div id="info" style="font-size: 16px;">
                              
             </div>
             
             <!-- POUR L'ENTRER DES RESULTATS -->
             <!-- POUR L'ENTRER DES RESULTATS -->
             <!-- POUR L'ENTRER DES RESULTATS -->
             <div id="info_examen" style="font-size: 16px;">
                <?php $form = $this->form;?>
                <?php echo $this->formhidden($form->get('Examen_id_cons'));?>

                <div id="formulaireModif">
                  <table id="form_patient" style="width: 100%;">  
                    <tr class="comment-form-patient" style="width: 100%;">
                      <td id='technique' style="width: 50%;"> <?php echo $this->formRow($form->get('technique_utilise'));?></td> 
                    </tr>
                  </table>
                
                  <table id="form_patient" style="width: 100%;">  
                    <tr class="comment-form-patient" style="width: 100%;">
                      <td style="width: 50%; "> <?php echo $this->formRow($form->get('resultat'));?></td> 
                      <td style="width: 50%; "> <?php echo $this->formRow($form->get('conclusion'));?></td> 
                    </tr>
                  </table>
                </div>
                           
                <!-- GESTION DES EXAMENS MORPHOLOGIQUES ***** GESTION DES EXAMENS MORPHOLOGIQUES  -->
                <!-- GESTION DES EXAMENS MORPHOLOGIQUES ***** GESTION DES EXAMENS MORPHOLOGIQUES  -->
                <!-- GESTION DES EXAMENS MORPHOLOGIQUES ***** GESTION DES EXAMENS MORPHOLOGIQUES  -->
                <!-- GESTION DES EXAMENS MORPHOLOGIQUES ***** GESTION DES EXAMENS MORPHOLOGIQUES  -->
                <?php echo  $this->headScript()->appendFile($this->basePath().'/js/hospitalisation/majComplementCons.js');?>
                
                            <!-- POP UP pour Confirmation Suppression -->
                            <div id="confirmation" title="Confirmation de la suppression" style="display:none;">
                              <p style="font-size: 15px;">
                                 <span style="float:left; margin:0 0px 20px 0; ">
                                 <img src="<?php echo $this->basePath().'/images_icons/warning_16.png';?>" />
                                 Etes-vous s&ucirc;r de vouloir supprimer l'image ?</span>
                              </p>
                            </div>
                            
                            <!-- NOUVEAU CODE POUR LA GESTION DES IMAGES  -->
                            <!-- NOUVEAU CODE POUR LA GESTION DES IMAGES  -->
                            <!-- NOUVEAU CODE POUR LA GESTION DES IMAGES  -->
                            
                                 <!-- RADIO RADIO RADIO  -->
                                 <!-- RADIO RADIO RADIO  -->
                                 <!-- RADIO RADIO RADIO  -->
                                 <!-- RADIO RADIO RADIO  -->
                                 <input type='hidden' id="typeExamen_tmp" />
                                 <input type='hidden' id="temoinEnregistrementImage" />
                                 <input type='hidden' id="temoinListeConcerneePourVisualisation" />
                                 <input type='hidden' id="temoinPourSupression" /> <!-- Pour savoir s'il faut supprimer ou pas -->
                            <table id="respondeee" class="imageRadio" style="width: 100%;">
                                   <tr style="width: 100%;">
                                       <td colspan='3' id="libelleInformation"> <i style='color: green; font-family: time new romans; font-size: 17px;'> Ajouter des images (radiologie) </i> </td>
                                   </tr>
                                   <tr style="width: 100%;">
                                       <th colspan="3"><div style="width:100%; margin-top: 1px; margin-bottom: 10px; border-bottom: 3px solid #ccc; "></div></th>
                                   </tr>
                                   <tr class="form-examen-morphologique" style="width: 100%; height: 240px;">
                                       <th style="width: 15%; vertical-align: top;"> </th>
                                       <th style="position: relative; width: 67%; padding-top: 10px"> 
                                           <!-- PIKACHOOSE -->
                                           <!-- PIKACHOOSE -->
                                           <div id="pika">
                                             <div id="pika2">
                                                <!-- EMPLACEMENT DES IMAGES -->
                                                <!-- EMPLACEMENT DES IMAGES -->
                                                <!-- EMPLACEMENT DES IMAGES -->
                                             </div>
                                           </div>
                                           <div id="AjoutImage" style="position: absolute; right: 25px; bottom: -20px;">
                                                  <input type='file' name="fichier" />
			                                      <!-- RECUPERER L'IMAGE -->
			                                      <input type='hidden' id="fichier_tmp" name="fichier_tmp" />
			                                      <!-- FICHIER TAMPON POUR RECUPERER L'IMAGE DANS LE CONTROLLER -->
                                           </div>
                                       </th>
                                       <th style="width: 18%; vertical-align: top;"> </th>
                                   </tr>
                            </table>
                            
                            
                                 <!-- ECHOGRAPHIE ECHOGRAPHIE ECHOGRAPHIE  -->
                                 <!-- ECHOGRAPHIE ECHOGRAPHIE ECHOGRAPHIE  -->
                                 <!-- ECHOGRAPHIE ECHOGRAPHIE ECHOGRAPHIE  -->
                                 <!-- ECHOGRAPHIE ECHOGRAPHIE ECHOGRAPHIE  -->
                            <table id="respondeee" class="imageEchographie" style="width: 100%;">
                                   <tr style="width: 100%;">
                                       <td colspan='3' id="libelleInformation2"> <i style='color: green; font-family: time new romans; font-size: 17px;'> Ajouter des images (radiologie) </i> </td>
                                   </tr>
                                   <tr style="width: 100%;">
                                       <th colspan="3"><div style="width:100%; margin-top: 1px; margin-bottom: 10px; border-bottom: 3px solid #ccc; "></div></th>
                                   </tr>
                                   <tr class="form-examen-morphologique" style="width: 100%; height: 240px;">
                                       <th style="width: 15%; vertical-align: top;"> </th>
                                       <th style="position: relative; width: 67%; padding-top: 10px"> 
                                           <!-- PIKACHOOSE -->
                                           <!-- PIKACHOOSE -->
                                           <div id="pika3">
                                             <div id="pika4">
                                                <!-- EMPLACEMENT DES IMAGES -->
                                                <!-- EMPLACEMENT DES IMAGES -->
                                                <!-- EMPLACEMENT DES IMAGES -->
                                             </div>
                                           </div>
                                           <div id="AjoutImageEchographie" style="position: absolute; right: 25px; bottom: -20px;">
                                                  <input type='file' name="fichierEchographie" />
			                                      <!-- RECUPERER L'IMAGE -->
			                                      <input type='hidden' id="fichierEchographie_tmp" name="fichierEchographie_tmp" />
			                                      <!-- FICHIER TAMPON POUR RECUPERER L'IMAGE DANS LE CONTROLLER -->
                                           </div>
                                       </th>
                                       <th style="width: 18%; vertical-align: top;"> </th>
                                   </tr>
                                  
                            </table>
                            
                            
                                 <!-- IRM IRM IRM  -->
                                 <!-- IRM IRM IRM  -->
                                 <!-- IRM IRM IRM  -->
                                 <!-- IRM IRM IRM  -->
                            <table id="respondeee" class="imageIRM" style="width: 100%;">
                                   <tr style="width: 100%;">
                                       <td colspan='3' id="libelleInformation3"> <i style='color: green; font-family: time new romans; font-size: 17px;'> Ajouter des images (IRM) </i> </td>
                                   </tr>
                                   <tr style="width: 100%;">
                                       <th colspan="3"><div style="width:100%; margin-top: 1px; margin-bottom: 10px; border-bottom: 3px solid #ccc; "></div></th>
                                   </tr>
                                   <tr class="form-examen-morphologique" style="width: 100%; height: 240px;">
                                       <th style="width: 15%; vertical-align: top;"> </th>
                                       <th style="position: relative; width: 67%; padding-top: 10px"> 
                                           <!-- PIKACHOOSE -->
                                           <!-- PIKACHOOSE -->
                                           <div id="pika5">
                                             <div id="pika6">
                                                <!-- EMPLACEMENT DES IMAGES -->
                                                <!-- EMPLACEMENT DES IMAGES -->
                                                <!-- EMPLACEMENT DES IMAGES -->
                                             </div>
                                           </div>
                                           <div id="AjoutImageIRM" style="position: absolute; right: 25px; bottom: -20px;">
                                                  <input type='file' name="fichierIRM" />
			                                      <!-- RECUPERER L'IMAGE -->
			                                      <input type='hidden' id="fichierIRM_tmp" name="fichierIRM_tmp" />
			                                      <!-- FICHIER TAMPON POUR RECUPERER L'IMAGE DANS LE CONTROLLER -->
                                           </div>
                                       </th>
                                       <th style="width: 18%; vertical-align: top;"> </th>
                                   </tr>
                                   
                            </table>
                            
                  <?php
                   echo $this->headLink()->appendStylesheet($this->basePath().'/js/plugins/jPlayer-2.9.2/dist/skin/blue.monday/css/jplayer.blue.monday.min.css');
                   echo $this->headScript()->appendFile($this->basePath().'/js/plugins/jPlayer-2.9.2/dist/jplayer/jquery.jplayer.min.js');
                   echo $this->headScript()->appendFile($this->basePath().'/js/plugins/jPlayer-2.9.2/dist/add-on/jplayer.playlist.min.js');
                   //echo $this->headScript()->appendFile($this->basePath().'/js/consultation/jsAjouterSuppimerVideos.js');
                  ?>
                                 <!-- SCANNER SCANNER SCANNER  -->
                                 <!-- SCANNER SCANNER SCANNER  -->
                                 <!-- SCANNER SCANNER SCANNER  -->
                                 <!-- SCANNER SCANNER SCANNER  -->
                            <table id="respondeee" class="imageScanner" style="width: 100%;">
                                   <tr style="width: 100%;">
                                       <td colspan='3' id="libelleInformation4"> <i style='color: green; font-family: time new romans; font-size: 17px;'> Ajouter des images (SCANNER) </i> </td>
                                   </tr>
                                   <tr style="width: 100%;">
                                       <th colspan="3"><div style="width:100%; margin-top: 1px; margin-bottom: 10px; border-bottom: 3px solid #ccc; "></div></th>
                                   </tr>
                                   <tr class="form-examen-morphologique" style="width: 100%; height: 240px;">
                                       <th style="position: relative; width: 95%; padding-top: 10px"> 
                                           
                                         <div id="tabs" >
                                             <ul>
                                               <li><a href="#tabs-1">Images</a></li>
                                               <li id='CompteRenduTabs'><a href="#tabs-2">Vid&eacute;os</a></li>
                                             </ul>
                                   
                                           <div id="tabs-1" style="height: 250px"> 
                                           
                                             <!-- PIKACHOOSE -->
                                             <!-- PIKACHOOSE -->
                                             <div id="pika7">
                                               <div id="pika8">
                                                <!-- EMPLACEMENT DES IMAGES -->
                                                <!-- EMPLACEMENT DES IMAGES -->
                                                <!-- EMPLACEMENT DES IMAGES -->
                                               </div>
                                             </div>
                                             <div id="AjoutImageScanner" style="position: absolute; right: 25px; bottom: -20px;">
                                                  <input type='file' name="fichierScanner" />
			                                      <!-- RECUPERER L'IMAGE -->
			                                      <input type='hidden' id="fichierScanner_tmp" name="fichierScanner_tmp" />
			                                      <!-- FICHIER TAMPON POUR RECUPERER L'IMAGE DANS LE CONTROLLER -->
                                             </div>
                                           
                                           </div>
                                           
                                           <div id="tabs-2" style="height: 250px; overflow: auto;">
                                             <!-- EMPLACEMENT DES VIDEOS -->
                                             <!-- EMPLACEMENT DES VIDEOS -->
                                             <!-- EMPLACEMENT DES VIDEOS -->
                                           </div>
                                           
                                         </div>
                                           
                                       </th>
                                   </tr>
                            </table>
                            
                            
                                 <!-- FIBROSCOPIE FIBROSCOPIE FIBROSCOPIE  -->
                                 <!-- FIBROSCOPIE FIBROSCOPIE FIBROSCOPIE  -->
                                 <!-- FIBROSCOPIE FIBROSCOPIE FIBROSCOPIE  -->
                                 <!-- FIBROSCOPIE FIBROSCOPIE FIBROSCOPIE  -->
                            <table id="respondeee" class="imageFibroscopie" style="width: 100%;">
                                   <tr style="width: 100%;">
                                       <td colspan='3' id="libelleInformation5"> <i style='color: green; font-family: time new romans; font-size: 17px;'> Ajouter des images (FIBROSCOPIE) </i> </td>
                                   </tr>
                                   <tr style="width: 100%;">
                                       <th colspan="3"><div style="width:100%; margin-top: 1px; margin-bottom: 10px; border-bottom: 3px solid #ccc; "></div></th>
                                   </tr>
                                   <tr class="form-examen-morphologique" style="width: 100%; height: 240px;">
                                       <th style="width: 15%; vertical-align: top;"> </th>
                                       <th style="position: relative; width: 67%; padding-top: 10px"> 
                                           <!-- PIKACHOOSE -->
                                           <!-- PIKACHOOSE -->
                                           <div id="pika9">
                                             <div id="pika10">
                                                <!-- EMPLACEMENT DES IMAGES -->
                                                <!-- EMPLACEMENT DES IMAGES -->
                                                <!-- EMPLACEMENT DES IMAGES -->
                                             </div>
                                           </div>
                                           <div id="AjoutImageFibroscopie" style="position: absolute; right: 25px; bottom: -20px;">
                                                  <input type='file' name="fichierFibroscopie" />
			                                      <!-- RECUPERER L'IMAGE -->
			                                      <input type='hidden' id="fichierFibroscopie_tmp" name="fichierFibroscopie_tmp" />
			                                      <!-- FICHIER TAMPON POUR RECUPERER L'IMAGE DANS LE CONTROLLER -->
                                           </div>
                                       </th>
                                       <th style="width: 18%; vertical-align: top;"> </th>
                                   </tr>
                            </table>
                <!-- FIN FIN GESTION DES EXAMENS MORPHOLOGIQUES ***** GESTION DES EXAMENS MORPHOLOGIQUES  -->
                <!-- FIN FIN GESTION DES EXAMENS MORPHOLOGIQUES ***** GESTION DES EXAMENS MORPHOLOGIQUES  -->
                <!-- FIN FIN GESTION DES EXAMENS MORPHOLOGIQUES ***** GESTION DES EXAMENS MORPHOLOGIQUES  -->

             </div>
             
             
             <div id="script_donnees">
             
             </div>
        
        </div>

</div>
        
<!--***********************************************************************************************-->                              

<!--==========================POP UP pour Afficher les détails =================================-->                              
                          
<!--***********************************************************************************************-->  
        <div id="envoyer_examen" title="Confirmation de l'envoi des r&eacute;sultats" style="display:none;">
             
              <p style="font-size: 16px;">
                 <span style="float:left; margin:0 0px 20px 0; font-size:17px; ">
                 <img src="<?php echo $this->basepath().'/images_icons/warning_16.png';?>" />
                                
                 Etes-vous s&ucirc;r de vouloir envoyer les r&eacute;sultats de l'examen ?</span>
             </p>
             
        </div>
        
        
<script type="text/javascript">
$(function(){
	initialisationListeRehercheExamensEffectuesMorpho();
	$('#temoinListeConcerneePourVisualisation').val(2);
});

$("#vue_detail_hospi_patient").toggle(false);
$("#vue_patient").toggle(false);
$("#hospitaliser").toggle(false);
</script>