<!-- MES STYLES --> 
<?php echo $this->headLink()->appendStylesheet($this->basepath().'/css/hospitalisation/styleSuiviPatient.css');
      echo $this->headLink()->appendStylesheet($this->basepath().'/css/facturation/DatePicker.css'); 
?>
<!-- MES JS -->
<?php echo $this->headScript()->appendFile($this->basepath().'/js/hospitalisation/jsSuiviPatient.js');?>

<?php $form = $this->form; ?>

<script type="text/javascript">
$(window).load(function () {
	$('#wait').toggle(false);
	$('#contenuSoins, #toutLeContenu').fadeIn().css({'visibility':'visible'});
});
</script>

<style>
#contenuSoins, #toutLeContenu{ visibility: hidden };
</style>

<div id="titre" style='font-family: police2; text-decoration: none; color: green; font-size: 20px; font-weight: bold; padding-left:20px;'>
	<iS style='font-size: 25px;'>&curren;</iS>
	LISTE DES SOINS
</div>
<div id="wait" style="color: gray; font-size: 20px; text-align: center; margin-top: 80px;" > <span> Chargement ... </span> </div>

<div id="toutLeContenu">
<div id="contenu"> 
            <div style="margin-right: 10px; float:right; font-size: 15px; margin-top:5px; font-family: Times New Roman; font-size: 14px; color: green;"> <i style='cursor:pointer;' id='afficherListeSoins2'> Soins </i> | <i style='cursor:pointer;' id='afficherListePatients2'> Patients </i> </div>
            <table id="patient" class="table table-bordered tab_list_mini" >
				<thead>
					<tr style="height: 50px; width:100%;">
						<th id="nom" style='cursor: pointer;'>Nom</th>
						<th id="prenom" style='cursor: pointer;'>Prenom</th>
						<th id="date" style='cursor: pointer;'>Date. naiss</th>
						<th id="sexe" style='cursor: pointer;'>Sexe</th>
						<th id="adresse" style='cursor: pointer;'>Date & Heure D&eacute;but</th>
						<th id="nationalite" style='cursor: pointer;'>Date fin pr&eacute;vue.</th>
						<th id="effectuer">Options</th>
					</tr>
				</thead>

				<tbody class="liste_patient">

					<!-- ************ On affiche les patients en une liste ordonnï¿½e************ -->

				</tbody>

				<tfoot id="foot" class="foot_style">
					<tr>
						<th id="nom_" style='width: 16%;'><input type="text" name="search_browser"
							value=" Nom" class="search_init" /></th>
						<th id="prenom_" style='width: 18%;'><input type="text" name="search_browser"
							value=" Pr&eacute;nom" class="search_init" /></th>
						<th id="date_" style='width: 12%;'><input type="text" name="search_browser"
							value=" Date naissance" class="search_init" /></th>
						<th id="sexe_" style='width: 7%;'><input type="text" name="search_browser"
							value=" Sexe" class="search_init" /></th>
						<th id="adresse_" style='width: 20%;'><input type="text" name="search_browser"
							value=" Adresse" class="search_init" /></th>
						<th id="nationalite_" style='width: 20%;'><input type="text" name="search_browser"
							value=" Nationalite" class="search_init" /></th>
						<th id="effectuer_" style='width: 7%;'><input type="hidden" name="search_browser"
							value="" class="" /></th>

					</tr>
				</tfoot>
			</table>
</div>

<div id="vue_patient">

</div>

<div id="vue_detail_hospi_patient">

</div>

</div>

<!--***********************************************************************************************-->                              

<!--=================== Pour la liste des soins ------ Pour la liste des soins ====================-->                              
                          
<!--***********************************************************************************************-->  
<div id="contenuSoins"> 

            <div style="margin-right: 10px; float:right; font-size: 15px; margin-top:5px; font-family: Times New Roman; font-size: 14px; color: green;"> <i style='cursor:pointer;' id='afficherListeSoins'> Soins </i> | <i style='cursor:pointer;' id='afficherListePatients'> Patients </i> </div>
            <div id="ListeDesSoinsDuJour" >
				<div style='width: 100px; height: 100px; margin:auto; margin-top: 60px;'> <img style='width: 100%; height: 100%;' src='/simens/public/images/loading/chargement_4.gif' /> </div>
			</div>
</div>

<!--***********************************************************************************************-->                              

<!--============================ POP UP pour Afficher les détails =================================-->                              
                          
<!--***********************************************************************************************-->  
        <div id="informations" title="D&eacute;tails des infos du soin" style="display:none;">
             
             <div id="info" style="font-size: 16px;">
                              
             </div>
             
        </div>
        
        
<!--***********************************************************************************************-->                              

<!--============================ POP UP pour Afficher les détails =================================-->                              
                          
<!--***********************************************************************************************-->  
        <div id="application_soin" title="Ajouter une note" style="display:none;">
             
             <div id="info_soin" style="font-size: 16px;">
                <?php $form = $this->form;?>
                <?php echo $this->formhidden($form->get('play'));?>
                <?php echo $this->formhidden($form->get('id_hosp'));?>

                <span id="HeureActu" style="position:absolute; right: 30px; top: 15px; color: orange; font-weight: bold; font-family: time new romans; font-size: 20px;"> --- </span>
                <table id="form_patient" style="width: 100%;">  
                   <tr class="comment-form-patient" style="width: 100%;">
                      <td style="width: 33%;"> <?php echo $this->formRow($form->get('note'));?></td> 
                   </tr>
                </table>

             </div>
        
        </div>

        
<!--***********************************************************************************************-->                              

<!--====================== POP UP pour Afficher les détails sur le soin ===========================-->                              
                          
<!--***********************************************************************************************-->  
        <div id="informationsSoinListe" title="D&eacute;tails des infos du soin" style="display:none;">
             
             <div id="infoSoinListe" style="font-size: 16px;">
                              
             </div>
             
        </div>
        
   
        
<script type="text/javascript">
function FaireClignoterImage (){
     $("#clignoterHeure, #alertHeureApplicationSoin").fadeOut(900).fadeIn(800);
}

$(function(){
 setInterval('FaireClignoterImage()',2200);
});


$("#vue_detail_hospi_patient").toggle(false);
$("#vue_patient").toggle(false);
$("#hospitaliser").toggle(false);


$("#contenu").toggle(false);

$('#afficherListeSoins').css({'font-weight':'bold', 'font-size': '17px' });

$("#afficherListeSoins").click(function(){
	$("#titre").replaceWith("<div id='titre' style='font-family: police2; color: green; font-size: 20px; font-weight: bold; padding-left:20px;'><iS style='font-size: 25px;'>&curren;</iS> LISTE DES SOINS </div>");
	$("#contenuSoins").toggle(true);
	$("#contenu").toggle(false);
	$('#afficherListePatients2').css({'font-weight':'normal', 'font-size': '14px' });
	$('#afficherListeSoins2').css({'font-weight':'bold', 'font-size': '17px' });
});

$("#afficherListePatients").click(function(){ 
    if($('#play').val() == 1){
      //Pour l audio player
        player.pause();
    	player.currentTime = 0;
    	temoinClickListePatient = 1;
    }
    
	$("#titre").replaceWith("<div id='titre' style='font-family: police2; color: green; font-size: 20px; font-weight: bold; padding-left:20px;'><iS style='font-size: 25px;'>&curren;</iS> LISTE DES PATIENTS </div>");
	$("#contenu").toggle(true);
	$("#contenuSoins").toggle(false);
	$('#afficherListeSoins2').css({'font-weight':'normal', 'font-size': '14px' });
	$('#afficherListePatients2').css({'font-weight':'bold', 'font-size': '17px' });

	$("#afficherListeSoins2").click(function(){
		temoinClickListePatient = 0;
		$('.listeDataTable').css({'margin-left':'-10'});
		$("#titre").replaceWith("<div id='titre' style='font-family: police2; color: green; font-size: 20px; font-weight: bold; padding-left:20px;'><iS style='font-size: 25px;'>&curren;</iS> LISTE DES SOINS </div>");
		$("#contenu").toggle(false);
		$("#contenuSoins").toggle(true);
		$('#afficherListePatients').css({'font-weight':'normal', 'font-size': '14px' });
		$('#afficherListeSoins').css({'font-weight':'bold', 'font-size': '17px' });
	});
});

listeSoinsAAppliquer();
//Raffraichissement de la liste des soins
//Raffraichissement de la liste des soins
//Raffraichissement de la liste des soins
var RaffraichirListeDesSoinsDuJourListe;
function RechargerListeSoins (){
	listeSoinsAAppliquer();
}
$(function(){
	RaffraichirListeDesSoinsDuJourListe = setInterval('RechargerListeSoins ()',16000);
});




var base_url = window.location.toString();
var tabUrl = base_url.split("public");

/***POUR LE MENU GAUCHE dans -elementgauche.phtml***/
$('#plus_dossier_personnel').toggle(true); 
$("#dossier_personnel").replaceWith("<li id='dossier_personnel' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:21px; font-family:Times New Roman;'> <img style='display: inline;' src='"+tabUrl[0]+"public/images_icons/moin-green2.png' alt='Liste' /> Hospitalisation </span></a></li>");
dep_dossier_personnel1();
$('#suivi_patient_style').css({'font-weight':'bold','color':'white','font-size':'21px'});
</script>